# Generated By: Claude Code (Claude Opus 4.6)

"""Tests for exporter orchestration module."""

from pathlib import Path
from unittest.mock import patch

import pytest

from calendar_fetcher.exporter import process_artifact, process_event, process_events
from calendar_fetcher.models import Artifact, CalendarEvent


@pytest.fixture
def sample_event():
    """Sample calendar event for testing."""
    return CalendarEvent(
        event_id="event123",
        calendar_id="cal@example.com",
        summary="Team Sync",
        start="2025-04-15T10:00:00Z",
        end="2025-04-15T11:00:00Z",
        description="Weekly sync meeting",
        meet_code="abc-defg-hij",
        attachments=[
            Artifact(
                type="attachment",
                title="Agenda Doc",
                source_url="https://docs.google.com/document/d/doc123",
                drive_file_id="doc123",
                mime_type="application/vnd.google-apps.document",
                source="attached",
            )
        ],
        api_response={"id": "event123", "summary": "Team Sync"},
    )


@pytest.fixture
def sample_artifact():
    """Sample artifact for testing."""
    return Artifact(
        type="attachment",
        title="Test Doc",
        source_url="https://docs.google.com/document/d/doc123",
        drive_file_id="doc123",
        mime_type="application/vnd.google-apps.document",
        source="attached",
    )


def test_process_artifact_google_doc(tmp_path, sample_artifact):
    """Test processing a Google Doc artifact via direct markdown export."""
    with patch("calendar_fetcher.exporter.drive_client") as mock_drive:
        expected_path = tmp_path / "2025-04-15_team-sync_test-doc_doc123.md"

        def mock_export(file_id, output_path):
            Path(output_path).write_text("# Exported Markdown")
            return output_path

        mock_drive.export_doc_as_markdown.side_effect = mock_export

        artifact = process_artifact(
            sample_artifact,
            tmp_path,
            date="2025-04-15",
            meeting_title="Team Sync",
            dryrun=False,
        )

        mock_drive.export_doc_as_markdown.assert_called_once_with(
            "doc123", str(expected_path)
        )
        assert expected_path.exists()
        assert expected_path.read_text() == "# Exported Markdown"
        assert artifact.local_file == str(expected_path)


def test_process_artifact_google_sheets(tmp_path):
    """Test processing a Google Sheets artifact."""
    artifact = Artifact(
        type="attachment",
        title="Budget Sheet",
        source_url="https://docs.google.com/spreadsheets/d/sheet123",
        drive_file_id="sheet123",
        mime_type="application/vnd.google-apps.spreadsheet",
        source="attached",
    )

    with patch("calendar_fetcher.exporter.drive_client") as mock_drive:
        # Mock sheet tabs
        mock_drive.fetch_sheet_tabs.return_value = [
            {"title": "Q1"},
            {"title": "Q2"},
        ]

        # Create output directory
        tmp_path.mkdir(parents=True, exist_ok=True)

        # Define expected paths
        csv_path_q1 = tmp_path / "2025-04-15_team-sync_budget-sheet_sheet123_q1.csv"
        csv_path_q2 = tmp_path / "2025-04-15_team-sync_budget-sheet_sheet123_q2.csv"

        # Mock fetch_sheet_tab_data to create files when called
        def mock_fetch_tab(file_id, tab_name, output_path):
            Path(output_path).write_text(f"data for {tab_name}")
            return output_path

        mock_drive.fetch_sheet_tab_data.side_effect = mock_fetch_tab

        result = process_artifact(
            artifact,
            tmp_path,
            date="2025-04-15",
            meeting_title="Team Sync",
            dryrun=False,
        )

        # Verify tabs were fetched
        mock_drive.fetch_sheet_tabs.assert_called_once_with("sheet123")
        # Verify each tab was exported
        assert mock_drive.fetch_sheet_tab_data.call_count == 2

        # Verify files were created with correct content
        assert csv_path_q1.exists()
        assert csv_path_q1.read_text() == "data for Q1"
        assert csv_path_q2.exists()
        assert csv_path_q2.read_text() == "data for Q2"

        # Verify local_file is set to first file
        assert result.local_file == str(csv_path_q1)


def test_process_artifact_slides_pdf(tmp_path):
    """Test processing a Google Slides artifact."""
    artifact = Artifact(
        type="attachment",
        title="Presentation",
        source_url="https://docs.google.com/presentation/d/slides123",
        drive_file_id="slides123",
        mime_type="application/vnd.google-apps.presentation",
        source="attached",
    )

    with patch("calendar_fetcher.exporter.drive_client") as mock_drive:
        output_path = tmp_path / "2025-04-15_team-sync_presentation_slides123.pdf"

        # Mock export to create the file and return the path
        def mock_export(file_id, path):
            Path(path).write_bytes(b"%PDF-1.4")
            return path

        mock_drive.export_slides_as_pdf.side_effect = mock_export

        result = process_artifact(
            artifact,
            tmp_path,
            date="2025-04-15",
            meeting_title="Team Sync",
            dryrun=False,
        )

        # Verify export was called
        mock_drive.export_slides_as_pdf.assert_called_once_with(
            "slides123", str(output_path)
        )
        # Verify file content and local_file is set
        assert output_path.read_bytes() == b"%PDF-1.4"
        assert result.local_file == str(output_path)


def test_process_artifact_skip_existing(tmp_path, sample_artifact):
    """Test that existing files are skipped."""
    existing_file = tmp_path / "2025-04-15_team-sync_test-doc_doc123.md"
    existing_file.write_text("existing content")

    with patch("calendar_fetcher.exporter.drive_client") as mock_drive:
        result = process_artifact(
            sample_artifact,
            tmp_path,
            date="2025-04-15",
            meeting_title="Team Sync",
            dryrun=False,
        )

        # Should NOT call export since file exists
        mock_drive.export_doc_as_markdown.assert_not_called()
        # File should remain unchanged
        assert existing_file.read_text() == "existing content"
        # local_file should be set to existing file
        assert result.local_file == str(existing_file)


def test_process_artifact_error_sets_note(tmp_path, sample_artifact):
    """Test that export failure sets note on artifact."""
    with patch("calendar_fetcher.exporter.drive_client") as mock_drive:
        mock_drive.export_doc_as_markdown.return_value = None

        result = process_artifact(
            sample_artifact,
            tmp_path,
            date="2025-04-15",
            meeting_title="Team Sync",
            dryrun=False,
        )

        # Verify note is set
        assert result.note is not None
        assert "Failed" in result.note
        # local_file should remain None
        assert result.local_file is None


def test_process_artifact_dryrun(tmp_path, sample_artifact, capsys):
    """Test that dryrun mode prints but doesn't download."""
    with patch("calendar_fetcher.exporter.drive_client") as mock_drive:
        result = process_artifact(
            sample_artifact,
            tmp_path,
            date="2025-04-15",
            meeting_title="Team Sync",
            dryrun=True,
        )

        # Should NOT call drive client
        mock_drive.export_doc_as_markdown.assert_not_called()

        # Should print what would happen
        captured = capsys.readouterr()
        assert "would download" in captured.out.lower()

        # local_file should remain None
        assert result.local_file is None


def test_process_artifact_unsupported_mime(tmp_path):
    """Test that unsupported MIME type sets note."""
    artifact = Artifact(
        type="attachment",
        title="Unknown File",
        source_url="https://example.com/file.xyz",
        drive_file_id="file123",
        mime_type="application/unknown",
        source="attached",
    )

    result = process_artifact(
        artifact,
        tmp_path,
        date="2025-04-15",
        meeting_title="Team Sync",
        dryrun=False,
    )

    # Verify note is set
    assert "unsupported type" in result.note


def test_process_event_with_meet(tmp_path, sample_event):
    """Test processing event with Meet code."""
    with (
        patch("calendar_fetcher.exporter.drive_client") as mock_drive,
        patch("calendar_fetcher.exporter.meet_client") as mock_meet,
        patch("calendar_fetcher.exporter.metadata") as mock_metadata,
    ):
        # Mock Meet API response
        transcript_artifact = Artifact(
            type="transcript",
            title="Transcript",
            source_url="https://docs.google.com/document/d/transcript123",
            drive_file_id="transcript123",
            mime_type="application/vnd.google-apps.document",
        )
        mock_meet.get_all_meet_data.return_value = (
            [transcript_artifact],
            {"conference_record": {"name": "conferenceRecords/abc"}},
        )

        # Mock doc export
        mock_drive.export_doc_as_markdown.return_value = str(tmp_path / "doc.md")

        record = process_event(sample_event, tmp_path, dryrun=False)

        # Verify Meet API was called
        mock_meet.get_all_meet_data.assert_called_once_with("abc-defg-hij")

        # Verify record contains both attachment and transcript
        assert len(record.artifacts) == 2
        assert record.artifacts[0].type == "attachment"
        assert record.artifacts[1].type == "transcript"

        # Verify metadata was written
        mock_metadata.write_metadata.assert_called_once()
        call_args = mock_metadata.write_metadata.call_args
        # write_metadata(metadata, output_dir, filename) - positional args
        assert call_args[0][1] == tmp_path


def test_process_event_without_meet(tmp_path, sample_event):
    """Test processing event without Meet code."""
    sample_event.meet_code = None

    with (
        patch("calendar_fetcher.exporter.drive_client") as mock_drive,
        patch("calendar_fetcher.exporter.meet_client") as mock_meet,
        patch("calendar_fetcher.exporter.metadata"),
    ):
        mock_drive.export_doc_as_markdown.return_value = str(tmp_path / "doc.md")

        record = process_event(sample_event, tmp_path, dryrun=False)

        # Verify Meet API was NOT called
        mock_meet.get_all_meet_data.assert_not_called()

        # Verify only attachment is in record
        assert len(record.artifacts) == 1
        assert record.artifacts[0].type == "attachment"


def test_process_event_writes_metadata(tmp_path, sample_event):
    """Test that metadata is written for each event."""
    with (
        patch("calendar_fetcher.exporter.drive_client") as mock_drive,
        patch("calendar_fetcher.exporter.meet_client") as mock_meet,
        patch("calendar_fetcher.exporter.metadata") as mock_metadata,
    ):
        mock_meet.get_all_meet_data.return_value = ([], {})
        mock_drive.export_doc_as_markdown.return_value = str(tmp_path / "doc.md")
        mock_metadata.metadata_filename.return_value = "2025-04-15_team-sync.meta.json"

        process_event(sample_event, tmp_path, dryrun=False)

        # Verify metadata functions were called
        assert mock_metadata.build_meeting_metadata.call_count == 1
        assert mock_metadata.metadata_filename.call_count == 1
        assert mock_metadata.write_metadata.call_count == 1


def test_process_events_returns_records(tmp_path):
    """Test processing multiple events."""
    events = [
        CalendarEvent(
            event_id="event1",
            calendar_id="cal@example.com",
            summary="Event 1",
            start="2025-04-15T10:00:00Z",
            end="2025-04-15T11:00:00Z",
            api_response={},
        ),
        CalendarEvent(
            event_id="event2",
            calendar_id="cal@example.com",
            summary="Event 2",
            start="2025-04-15T14:00:00Z",
            end="2025-04-15T15:00:00Z",
            api_response={},
        ),
    ]

    with (
        patch("calendar_fetcher.exporter.meet_client") as mock_meet,
        patch("calendar_fetcher.exporter.metadata"),
    ):
        mock_meet.get_all_meet_data.return_value = ([], {})

        records = process_events(events, tmp_path, dryrun=False)

        # Verify all events were processed
        assert len(records) == 2
        assert records[0].event.event_id == "event1"
        assert records[1].event.event_id == "event2"


def test_process_events_logs_progress(tmp_path, caplog):
    """Test that progress is logged during processing."""
    import logging

    caplog.set_level(logging.INFO)

    events = [
        CalendarEvent(
            event_id="event1",
            calendar_id="cal@example.com",
            summary="Test Event",
            start="2025-04-15T10:00:00Z",
            end="2025-04-15T11:00:00Z",
            api_response={},
        )
    ]

    with (
        patch("calendar_fetcher.exporter.meet_client") as mock_meet,
        patch("calendar_fetcher.exporter.metadata"),
    ):
        mock_meet.get_all_meet_data.return_value = ([], {})

        process_events(events, tmp_path, dryrun=False)

        # Verify progress was logged
        assert "test event" in caplog.text.lower() or "event1" in caplog.text.lower()
