# Generated By: Claude Code (Claude Opus 4.6)

"""Tests for date parsing utilities."""

from datetime import date

from calendar_fetcher.date_utils import parse_human_date, strip_markdown_formatting


class TestStripMarkdownFormatting:
    def test_strips_strikethrough(self):
        assert (
            strip_markdown_formatting("~~Dec 5, 2024~~ Dec 12, 2024") == "Dec 12, 2024"
        )

    def test_strips_bold_asterisks(self):
        assert strip_markdown_formatting("**Cancelled**") == "Cancelled"

    def test_strips_italic_asterisks(self):
        assert (
            strip_markdown_formatting("*Oct 10, 2024 Call canceled*")
            == "Oct 10, 2024 Call canceled"
        )

    def test_strips_underscores(self):
        assert strip_markdown_formatting("_emphasized_") == "emphasized"

    def test_strips_backticks(self):
        assert strip_markdown_formatting("`code`") == "code"

    def test_strips_mixed_formatting(self):
        assert strip_markdown_formatting("~~old~~ **new** _stuff_") == "new stuff"

    def test_plain_text_unchanged(self):
        assert strip_markdown_formatting("plain text") == "plain text"

    def test_empty_string(self):
        assert strip_markdown_formatting("") == ""


class TestParseHumanDate:
    def test_abbreviated_month(self):
        assert parse_human_date("Apr 30, 2026") == date(2026, 4, 30)

    def test_full_month(self):
        assert parse_human_date("April 30, 2026") == date(2026, 4, 30)

    def test_iso_format(self):
        assert parse_human_date("2026-04-30") == date(2026, 4, 30)

    def test_with_surrounding_text(self):
        assert parse_human_date("Apr 30, 2026 | [Meeting Title](link)") == date(
            2026, 4, 30
        )

    def test_with_trailing_text(self):
        assert parse_human_date("Feb 26, 2026 Cancelled") == date(2026, 2, 26)

    def test_single_digit_day(self):
        assert parse_human_date("Aug 1, 2024") == date(2024, 8, 1)

    def test_no_date(self):
        assert parse_human_date("Five Dysfunctions of a Team Reminder") is None

    def test_empty_string(self):
        assert parse_human_date("") is None

    def test_action_items_heading(self):
        assert parse_human_date("Action Items {#action-items}") is None

    def test_iso_with_surrounding_text(self):
        assert parse_human_date("2026-04-30 | [Meeting Title](link)") == date(
            2026, 4, 30
        )

    def test_after_stripping_markdown(self):
        text = strip_markdown_formatting("~~Dec 5, 2024~~ Dec 12, 2024 | [Title](link)")
        assert parse_human_date(text) == date(2024, 12, 12)

    def test_after_stripping_italic(self):
        text = strip_markdown_formatting("*Oct 10, 2024 Call canceled*")
        assert parse_human_date(text) == date(2024, 10, 10)
