# Generated By: Claude Code (Claude Opus 4.6)

"""Tests for gws CLI runner module."""

import json
import subprocess
from unittest.mock import MagicMock, patch

import pytest

from calendar_fetcher.gws import GWSError, check_auth_scopes, run_gws


class TestRunGWS:
    """Tests for run_gws function."""

    def test_run_gws_returns_parsed_json(self):
        """Verify run_gws parses JSON from stdout."""
        mock_result = MagicMock()
        mock_result.returncode = 0
        mock_result.stdout = '{"key": "value", "number": 42}'
        mock_result.stderr = ""

        with patch("subprocess.run", return_value=mock_result) as mock_run:
            result = run_gws("calendar", "events", "list")

        assert result == {"key": "value", "number": 42}
        mock_run.assert_called_once()

    def test_run_gws_constructs_command_correctly(self):
        """Verify command includes gws, args, --format, --params."""
        mock_result = MagicMock()
        mock_result.returncode = 0
        mock_result.stdout = "{}"
        mock_result.stderr = ""

        params = {"calendarId": "primary", "timeMin": "2024-01-01T00:00:00Z"}

        with patch("subprocess.run", return_value=mock_result) as mock_run:
            run_gws(
                "calendar",
                "events",
                "list",
                params=params,
                format="json",
            )

        call_args = mock_run.call_args[0][0]
        assert call_args[0] == "gws"
        assert "calendar" in call_args
        assert "events" in call_args
        assert "list" in call_args
        assert "--format" in call_args
        assert "json" in call_args
        assert "--params" in call_args
        params_index = call_args.index("--params")
        assert json.loads(call_args[params_index + 1]) == params

    def test_run_gws_raises_on_nonzero_exit(self):
        """Verify GWSError raised with stderr message."""
        mock_result = MagicMock()
        mock_result.returncode = 1
        mock_result.stdout = ""
        mock_result.stderr = "Error: Invalid credentials"

        with patch("subprocess.run", return_value=mock_result):
            with pytest.raises(GWSError) as exc_info:
                run_gws("calendar", "events", "list")

        assert "failed (exit 1)" in str(exc_info.value)
        assert "Invalid credentials" in str(exc_info.value)

    def test_run_gws_with_output_file(self):
        """Verify -o flag added to command."""
        mock_result = MagicMock()
        mock_result.returncode = 0
        mock_result.stdout = "{}"
        mock_result.stderr = ""

        with patch("subprocess.run", return_value=mock_result) as mock_run:
            run_gws("drive", "files", "export", output_file="/tmp/test.pdf")

        call_args = mock_run.call_args[0][0]
        assert "-o" in call_args
        assert "/tmp/test.pdf" in call_args

    def test_run_gws_returns_empty_dict_on_empty_stdout(self):
        """Verify empty stdout returns {}."""
        mock_result = MagicMock()
        mock_result.returncode = 0
        mock_result.stdout = ""
        mock_result.stderr = ""

        with patch("subprocess.run", return_value=mock_result):
            result = run_gws("auth", "status")

        assert result == {}

    def test_run_gws_retries_on_timeout(self):
        """Verify retry behavior when stderr contains 'timeout'."""
        # First call fails with timeout, second succeeds
        fail_result = MagicMock()
        fail_result.returncode = 1
        fail_result.stdout = ""
        fail_result.stderr = "Error: Request timed out"

        success_result = MagicMock()
        success_result.returncode = 0
        success_result.stdout = '{"status": "ok"}'
        success_result.stderr = ""

        with patch(
            "subprocess.run", side_effect=[fail_result, success_result]
        ) as mock_run:
            result = run_gws("calendar", "events", "list")

        assert result == {"status": "ok"}
        assert mock_run.call_count == 2

    def test_run_gws_no_retry_on_non_timeout_error(self):
        """Verify no retry for other errors."""
        mock_result = MagicMock()
        mock_result.returncode = 1
        mock_result.stdout = ""
        mock_result.stderr = "Error: Permission denied"

        with patch("subprocess.run", return_value=mock_result) as mock_run:
            with pytest.raises(GWSError):
                run_gws("calendar", "events", "list")

        # Should only be called once (no retry)
        assert mock_run.call_count == 1

    def test_run_gws_raises_on_timeout(self):
        """Verify GWSError raised when subprocess times out."""
        with patch(
            "subprocess.run",
            side_effect=subprocess.TimeoutExpired(cmd="gws", timeout=60),
        ):
            with pytest.raises(GWSError) as exc_info:
                run_gws("calendar", "events", "list")

        assert "timed out after 60 seconds" in str(exc_info.value)


class TestCheckAuthScopes:
    """Tests for check_auth_scopes function."""

    def test_check_auth_scopes_passes_with_all_scopes(self):
        """Verify no error when all required scopes present."""
        mock_result = MagicMock()
        mock_result.returncode = 0
        mock_result.stdout = json.dumps(
            {
                "scopes": [
                    "https://www.googleapis.com/auth/calendar.readonly",
                    "https://www.googleapis.com/auth/documents.readonly",
                    "https://www.googleapis.com/auth/drive.readonly",
                    "https://www.googleapis.com/auth/meetings.space.readonly",
                ]
            }
        )
        mock_result.stderr = ""

        with patch("subprocess.run", return_value=mock_result):
            # Should not raise
            check_auth_scopes()

    def test_check_auth_scopes_fails_missing_scope(self):
        """Verify raises SystemExit when scope missing."""
        mock_result = MagicMock()
        mock_result.returncode = 0
        mock_result.stdout = json.dumps(
            {
                "scopes": [
                    "https://www.googleapis.com/auth/calendar.readonly",
                    "https://www.googleapis.com/auth/documents.readonly",
                ]
            }
        )
        mock_result.stderr = ""

        with patch("subprocess.run", return_value=mock_result):
            with pytest.raises(SystemExit) as exc_info:
                check_auth_scopes(upload=False)

        assert exc_info.value.code == 1

    def test_check_auth_scopes_upload_needs_drive_write(self):
        """Verify upload=True fails if drive is readonly."""
        # Has drive.readonly but not full drive scope
        mock_result = MagicMock()
        mock_result.returncode = 0
        mock_result.stdout = json.dumps(
            {
                "scopes": [
                    "https://www.googleapis.com/auth/calendar.readonly",
                    "https://www.googleapis.com/auth/documents.readonly",
                    "https://www.googleapis.com/auth/drive.readonly",
                    "https://www.googleapis.com/auth/meetings.space.readonly",
                ]
            }
        )
        mock_result.stderr = ""

        with patch("subprocess.run", return_value=mock_result):
            with pytest.raises(SystemExit) as exc_info:
                check_auth_scopes(upload=True)

        assert exc_info.value.code == 1

    def test_check_auth_scopes_upload_passes_with_drive_write(self):
        """Verify upload=True passes when drive write scope present."""
        mock_result = MagicMock()
        mock_result.returncode = 0
        mock_result.stdout = json.dumps(
            {
                "scopes": [
                    "https://www.googleapis.com/auth/calendar.readonly",
                    "https://www.googleapis.com/auth/documents.readonly",
                    "https://www.googleapis.com/auth/drive",  # Write scope
                    "https://www.googleapis.com/auth/meetings.space.readonly",
                ]
            }
        )
        mock_result.stderr = ""

        with patch("subprocess.run", return_value=mock_result):
            # Should not raise
            check_auth_scopes(upload=True)
