# Generated By: Claude Code (Claude Opus 4.6)

"""Tests for drive_client upload functionality."""

from pathlib import Path
from unittest.mock import patch

from calendar_fetcher.drive_client import (
    list_folder_files,
    upload_file,
    upload_new_files,
)
from calendar_fetcher.gws import GWSError


@patch("calendar_fetcher.drive_client.run_gws")
def test_list_folder_files_success(mock_run_gws):
    """Test listing files in a folder returns set of filenames."""
    mock_run_gws.return_value = {
        "files": [
            {"name": "file1.txt"},
            {"name": "file2.pdf"},
            {"name": "file3.json"},
        ]
    }

    result = list_folder_files("folder123")

    assert result == {"file1.txt", "file2.pdf", "file3.json"}
    mock_run_gws.assert_called_once_with(
        "drive",
        "files",
        "list",
        params={
            "q": '"folder123" in parents',
            "fields": "nextPageToken,files(name)",
            "pageSize": 1000,
        },
    )


@patch("calendar_fetcher.drive_client.run_gws")
def test_list_folder_files_empty(mock_run_gws):
    """Test listing empty folder returns empty set."""
    mock_run_gws.return_value = {"files": []}

    result = list_folder_files("folder123")

    assert result == set()


@patch("calendar_fetcher.drive_client.run_gws")
def test_list_folder_files_error(mock_run_gws):
    """Test GWSError is caught and empty set returned."""
    mock_run_gws.side_effect = GWSError("API error")

    result = list_folder_files("folder123")

    assert result == set()


@patch("calendar_fetcher.drive_client.run_gws")
def test_upload_file_placeholder(mock_run_gws):
    """Test upload_file returns None (placeholder implementation)."""
    # For now, upload_file is a placeholder
    result = upload_file(Path("/tmp/test.txt"), "folder123")

    # Placeholder should return None
    assert result is None


@patch("calendar_fetcher.drive_client.list_folder_files")
@patch("calendar_fetcher.drive_client.upload_file")
def test_upload_new_files_uploads_missing(mock_upload, mock_list, tmp_path):
    """Test files not in folder get uploaded."""
    # Setup: folder has file1.txt, local has file1.txt and file2.txt
    mock_list.return_value = {"file1.txt"}
    mock_upload.return_value = "file_id_123"

    # Create local files
    (tmp_path / "file1.txt").write_text("content1")
    (tmp_path / "file2.txt").write_text("content2")

    result = upload_new_files(tmp_path, "folder123", dryrun=False)

    # Should upload only file2.txt
    assert result == 1
    mock_upload.assert_called_once()
    call_args = mock_upload.call_args[0]
    assert call_args[0].name == "file2.txt"
    assert call_args[1] == "folder123"


@patch("calendar_fetcher.drive_client.list_folder_files")
@patch("calendar_fetcher.drive_client.upload_file")
def test_upload_new_files_skips_existing(mock_upload, mock_list, tmp_path):
    """Test files already in folder are skipped."""
    # Setup: folder already has all files
    mock_list.return_value = {"file1.txt", "file2.txt"}

    # Create local files
    (tmp_path / "file1.txt").write_text("content1")
    (tmp_path / "file2.txt").write_text("content2")

    result = upload_new_files(tmp_path, "folder123", dryrun=False)

    # Should not upload anything
    assert result == 0
    mock_upload.assert_not_called()


@patch("calendar_fetcher.drive_client.list_folder_files")
@patch("calendar_fetcher.drive_client.upload_file")
def test_upload_new_files_dryrun(mock_upload, mock_list, tmp_path):
    """Test dryrun mode doesn't upload and returns 0."""
    mock_list.return_value = set()

    # Create local files
    (tmp_path / "file1.txt").write_text("content1")
    (tmp_path / "file2.txt").write_text("content2")

    result = upload_new_files(tmp_path, "folder123", dryrun=True)

    # Should not upload anything in dryrun mode
    assert result == 0
    mock_upload.assert_not_called()
