# Generated By: Claude Code (Claude Opus 4.6)

from calendar_fetcher.naming import extract_date, slugify, build_filename


def test_slugify_basic():
    assert slugify("Team Standup") == "team-standup"


def test_slugify_underscores_become_dashes():
    assert slugify("my_meeting_notes") == "my-meeting-notes"


def test_slugify_strips_nonalpha():
    assert slugify("Q2 Roadmap (Draft)!") == "q2-roadmap-draft"


def test_slugify_collapses_dashes():
    assert slugify("a - b -- c") == "a-b-c"


def test_slugify_strips_leading_trailing_dashes():
    assert slugify("--hello--") == "hello"


def test_slugify_empty_string():
    assert slugify("") == ""


def test_build_filename_no_tab():
    result = build_filename(
        date="2026-04-01",
        meeting_title="Team Standup",
        document_title="Meeting Notes",
        document_id="1BxOa7k9Rj",
        ext="md",
    )
    assert result == "2026-04-01_team-standup_meeting-notes_1BxOa7k9Rj.md"


def test_build_filename_with_tab():
    result = build_filename(
        date="2026-04-01",
        meeting_title="Team Standup",
        document_title="Q2 Roadmap",
        document_id="3FyPq2m8Xw",
        ext="csv",
        tab_name="Revenue",
    )
    assert result == "2026-04-01_team-standup_q2-roadmap_3FyPq2m8Xw_revenue.csv"


def test_build_filename_preserves_document_id():
    """Document ID is not slugified — it's used as-is."""
    result = build_filename(
        date="2026-04-01",
        meeting_title="Test",
        document_title="Doc",
        document_id="AbC_123-xYz",
        ext="md",
    )
    assert "AbC_123-xYz" in result


def test_build_filename_slides_pdf():
    result = build_filename(
        date="2026-04-01",
        meeting_title="Design Review",
        document_title="Architecture Deck",
        document_id="5HzLn4p6Yt",
        ext="pdf",
    )
    assert result == "2026-04-01_design-review_architecture-deck_5HzLn4p6Yt.pdf"


def test_extract_date_valid_iso():
    assert extract_date("2024-01-15T10:00:00-05:00") == "2024-01-15"


def test_extract_date_date_only():
    assert extract_date("2024-07-04") == "2024-07-04"


def test_extract_date_empty_string():
    assert extract_date("") == ""


def test_extract_date_short_string():
    assert extract_date("2024-01") == ""
