# Generated By: Claude Code (Claude Opus 4.6)

"""Tests for consolidator module."""

import json
from pathlib import Path

import pytest

from unittest.mock import patch

from calendar_fetcher.consolidator import (
    DocInfo,
    consolidate,
    _build_metadata_header,
    _create_tab,
    _delete_tab,
    _read_consolidate_state,
    _read_existing_tabs,
    _scan_doc_artifacts,
    _write_consolidate_state,
)


@pytest.fixture
def populated_output_dir(tmp_path):
    """Create an output directory with .meta.json and .md files."""
    meta1 = {
        "event_id": "evt1",
        "calendar_id": "primary",
        "summary": "Weekly Engineering Sync",
        "start": "2026-03-26T13:25:00-04:00",
        "end": "2026-03-26T14:25:00-04:00",
        "recurring_event_id": "rec1",
        "artifacts": [
            {
                "type": "attachment",
                "title": "Meeting Notes",
                "source_url": "https://docs.google.com/document/d/abc123/edit",
                "drive_file_id": "abc123",
                "local_file": str(tmp_path / "2026-03-26_weekly_notes_abc123.md"),
                "mime_type": "application/vnd.google-apps.document",
            }
        ],
        "api_responses": {
            "calendar": {
                "attendees": [
                    {
                        "email": "alice@example.com",
                        "displayName": "Alice",
                        "responseStatus": "accepted",
                    },
                    {
                        "email": "bob@example.com",
                        "displayName": "Bob",
                        "responseStatus": "declined",
                    },
                ]
            },
            "meet": {},
        },
    }
    with open(tmp_path / "2026-03-26_weekly-sync.meta.json", "w") as f:
        json.dump(meta1, f)

    md_path = tmp_path / "2026-03-26_weekly_notes_abc123.md"
    md_path.write_text("# Meeting Notes\n\nContent here.\n")

    return tmp_path


class TestScanDocArtifacts:
    """Tests for _scan_doc_artifacts."""

    def test_finds_google_doc_artifacts(self, populated_output_dir):
        result = _scan_doc_artifacts(populated_output_dir)
        assert "abc123" in result
        info = result["abc123"]
        assert isinstance(info, DocInfo)
        assert info.file_id == "abc123"
        assert info.meeting_summary == "Weekly Engineering Sync"
        assert info.recurring is True
        assert len(info.attendees) == 2

    def test_skips_non_doc_artifacts(self, tmp_path):
        meta = {
            "summary": "Test",
            "start": "2026-03-26T10:00:00Z",
            "recurring_event_id": None,
            "artifacts": [
                {
                    "type": "attachment",
                    "title": "Slides",
                    "drive_file_id": "slides1",
                    "local_file": "/tmp/slides.pdf",
                    "mime_type": "application/vnd.google-apps.presentation",
                }
            ],
            "api_responses": {"calendar": {}, "meet": {}},
        }
        with open(tmp_path / "test.meta.json", "w") as f:
            json.dump(meta, f)
        result = _scan_doc_artifacts(tmp_path)
        assert result == {}

    def test_skips_artifacts_without_local_file(self, tmp_path):
        meta = {
            "summary": "Test",
            "start": "2026-03-26T10:00:00Z",
            "recurring_event_id": None,
            "artifacts": [
                {
                    "type": "attachment",
                    "title": "Notes",
                    "drive_file_id": "doc1",
                    "mime_type": "application/vnd.google-apps.document",
                }
            ],
            "api_responses": {"calendar": {}, "meet": {}},
        }
        with open(tmp_path / "test.meta.json", "w") as f:
            json.dump(meta, f)
        result = _scan_doc_artifacts(tmp_path)
        assert result == {}

    def test_multi_meeting_uses_latest(self, tmp_path):
        for i, (date, summary) in enumerate(
            [
                ("2026-03-20T10:00:00Z", "Old Meeting"),
                ("2026-03-26T10:00:00Z", "New Meeting"),
            ]
        ):
            meta = {
                "summary": summary,
                "start": date,
                "recurring_event_id": None,
                "artifacts": [
                    {
                        "type": "attachment",
                        "title": "Shared Doc",
                        "drive_file_id": "shared1",
                        "local_file": str(tmp_path / "shared.md"),
                        "mime_type": "application/vnd.google-apps.document",
                    }
                ],
                "api_responses": {"calendar": {}, "meet": {}},
            }
            with open(tmp_path / f"meeting{i}.meta.json", "w") as f:
                json.dump(meta, f)
        (tmp_path / "shared.md").write_text("content")
        result = _scan_doc_artifacts(tmp_path)
        assert result["shared1"].meeting_summary == "New Meeting"

    def test_empty_directory(self, tmp_path):
        result = _scan_doc_artifacts(tmp_path)
        assert result == {}


class TestStripEmbeddedImages:
    """Tests for _strip_embedded_images."""

    def test_strips_reference_style_base64_images(self):
        from calendar_fetcher.consolidator import _strip_embedded_images

        content = (
            "Some text\n"
            "[image1]: <data:image/png;base64,iVBORw0KGgoAAAAN...>\n"
            "More text\n"
        )
        result = _strip_embedded_images(content)
        assert "data:image" not in result
        assert "[image1]: [image removed]" in result
        assert "Some text" in result
        assert "More text" in result

    def test_strips_inline_base64_images(self):
        from calendar_fetcher.consolidator import _strip_embedded_images

        content = "Look at this ![chart](data:image/png;base64,abc123) here\n"
        result = _strip_embedded_images(content)
        assert "data:image" not in result
        assert "[image removed]" in result
        assert "Look at this" in result

    def test_preserves_normal_images(self):
        from calendar_fetcher.consolidator import _strip_embedded_images

        content = "![photo](https://example.com/img.png)\n"
        result = _strip_embedded_images(content)
        assert result == content

    def test_no_images_returns_unchanged(self):
        from calendar_fetcher.consolidator import _strip_embedded_images

        content = "Just plain text\nNo images here\n"
        result = _strip_embedded_images(content)
        assert result == content


class TestBuildMetadataHeader:
    """Tests for _build_metadata_header."""

    def test_basic_header(self):
        info = DocInfo(
            file_id="abc123",
            local_path=Path("/tmp/notes.md"),
            local_mtime=0.0,
            meeting_summary="Weekly Engineering Sync",
            meeting_start="2026-03-26T13:25:00-04:00",
            recurring=True,
            attendees=[
                {"displayName": "Alice", "responseStatus": "accepted"},
                {"displayName": "Bob", "responseStatus": "declined"},
            ],
        )
        header = _build_metadata_header(info)
        assert "Meeting: Weekly Engineering Sync" in header
        assert "Date: 2026-03-26 13:25" in header
        assert "Recurring: Yes" in header
        assert "Alice (accepted)" in header
        assert "~~Bob~~ (declined)" in header
        assert "Source: https://docs.google.com/document/d/abc123/edit" in header
        assert header.endswith("---\n")

    def test_not_recurring(self):
        info = DocInfo(
            file_id="xyz",
            local_path=Path("/tmp/notes.md"),
            local_mtime=0.0,
            meeting_summary="One-off",
            meeting_start="2026-03-26T10:00:00Z",
            recurring=False,
            attendees=[],
        )
        header = _build_metadata_header(info)
        assert "Recurring: No" in header

    def test_no_attendees(self):
        info = DocInfo(
            file_id="xyz",
            local_path=Path("/tmp/notes.md"),
            local_mtime=0.0,
            meeting_summary="Solo",
            meeting_start="2026-03-26T10:00:00Z",
            recurring=False,
            attendees=[],
        )
        header = _build_metadata_header(info)
        assert "Attendees:" in header

    def test_attendee_without_display_name(self):
        info = DocInfo(
            file_id="xyz",
            local_path=Path("/tmp/notes.md"),
            local_mtime=0.0,
            meeting_summary="Test",
            meeting_start="2026-03-26T10:00:00Z",
            recurring=False,
            attendees=[{"email": "user@example.com", "responseStatus": "accepted"}],
        )
        header = _build_metadata_header(info)
        assert "user@example.com (accepted)" in header


class TestConsolidateState:
    """Tests for consolidate state read/write."""

    def test_read_state_missing_file(self, tmp_path):
        result = _read_consolidate_state(tmp_path)
        assert result == {}

    def test_read_state_no_consolidate_key(self, tmp_path):
        with open(tmp_path / "fetcher-state.json", "w") as f:
            json.dump({"modified_on": "2026-04-03T15:00:00Z"}, f)
        result = _read_consolidate_state(tmp_path)
        assert result == {}

    def test_write_and_read_state(self, tmp_path):
        state = {
            "last_run": "2026-04-03T15:00:00Z",
            "output_doc_id": "doc123",
            "tabs": {"abc123": {"tab_id": "t.12345", "source_mtime": "1712160600.0"}},
        }
        _write_consolidate_state(tmp_path, state)
        result = _read_consolidate_state(tmp_path)
        assert result == state

    def test_write_state_preserves_existing_keys(self, tmp_path):
        with open(tmp_path / "fetcher-state.json", "w") as f:
            json.dump({"modified_on": "2026-04-03T10:00:00Z"}, f)
        state = {
            "last_run": "2026-04-03T15:00:00Z",
            "output_doc_id": "doc1",
            "tabs": {},
        }
        _write_consolidate_state(tmp_path, state)
        with open(tmp_path / "fetcher-state.json") as f:
            full = json.load(f)
        assert full["modified_on"] == "2026-04-03T10:00:00Z"
        assert full["consolidate_state"] == state


class TestTabOperations:
    """Tests for Docs API tab operations (mocked)."""

    def test_read_existing_tabs(self):
        doc_response = {
            "tabs": [
                {"tabProperties": {"tabId": "t.abc", "title": "file_id_1"}},
                {"tabProperties": {"tabId": "t.def", "title": "file_id_2"}},
            ]
        }
        with patch("calendar_fetcher.consolidator.run_gws", return_value=doc_response):
            result = _read_existing_tabs("doc123")
        assert result == {"file_id_1": "t.abc", "file_id_2": "t.def"}

    def test_read_existing_tabs_empty_doc(self):
        with patch("calendar_fetcher.consolidator.run_gws", return_value={}):
            result = _read_existing_tabs("doc123")
        assert result == {}

    def test_create_tab(self):
        create_response = {
            "replies": [{"addDocumentTab": {"tabProperties": {"tabId": "t.new123"}}}]
        }
        insert_response = {"replies": [{}]}
        with patch(
            "calendar_fetcher.consolidator.run_gws_write",
            side_effect=[create_response, insert_response],
        ) as mock_write:
            tab_id = _create_tab("doc123", "file_id_abc", "Header\n---\nContent")
        assert tab_id == "t.new123"
        assert mock_write.call_count == 2
        first_json = mock_write.call_args_list[0][1]["json_body"]
        assert "addDocumentTab" in first_json["requests"][0]
        second_json = mock_write.call_args_list[1][1]["json_body"]
        assert (
            second_json["requests"][0]["insertText"]["endOfSegmentLocation"]["tabId"]
            == "t.new123"
        )

    def test_create_tab_chunks_large_content(self):
        """Verify large content is split into multiple insertText calls."""
        import calendar_fetcher.consolidator as mod

        create_response = {
            "replies": [{"addDocumentTab": {"tabProperties": {"tabId": "t.big"}}}]
        }
        insert_response = {"replies": [{}]}

        # Content larger than _MAX_TEXT_BYTES
        large_content = "x" * (mod._MAX_TEXT_BYTES + 1000)

        with patch(
            "calendar_fetcher.consolidator.run_gws_write",
            side_effect=[
                create_response,
                insert_response,
                insert_response,
            ],
        ) as mock_write:
            tab_id = _create_tab("doc123", "big_doc", large_content)

        assert tab_id == "t.big"
        # 1 create + 2 inserts (content split into 2 chunks)
        assert mock_write.call_count == 3

    def test_delete_tab(self):
        with patch(
            "calendar_fetcher.consolidator.run_gws_write",
            return_value={"replies": [{}]},
        ) as mock_write:
            _delete_tab("doc123", "t.old456")
        call_json = mock_write.call_args[1]["json_body"]
        assert call_json["requests"][0]["deleteTab"]["tabId"] == "t.old456"


class TestConsolidate:
    """Tests for the main consolidate function."""

    def test_creates_tabs_for_new_docs(self, populated_output_dir):
        doc_response = {"tabs": []}
        create_response = {
            "replies": [{"addDocumentTab": {"tabProperties": {"tabId": "t.new1"}}}]
        }
        insert_response = {"replies": [{}]}
        with (
            patch("calendar_fetcher.consolidator.run_gws", return_value=doc_response),
            patch(
                "calendar_fetcher.consolidator.run_gws_write",
                side_effect=[create_response, insert_response],
            ) as mock_write,
        ):
            consolidate(populated_output_dir, "output_doc_id")
        assert mock_write.call_count == 2

    def test_skips_unchanged_docs(self, populated_output_dir):
        md_file = populated_output_dir / "2026-03-26_weekly_notes_abc123.md"
        mtime = md_file.stat().st_mtime
        state = {
            "consolidate_state": {
                "last_run": "2026-04-03T15:00:00Z",
                "output_doc_id": "output_doc_id",
                "tabs": {
                    "abc123": {"tab_id": "t.existing", "source_mtime": str(mtime)}
                },
            }
        }
        with open(populated_output_dir / "fetcher-state.json", "w") as f:
            json.dump(state, f)
        doc_response = {
            "tabs": [{"tabProperties": {"tabId": "t.existing", "title": "abc123"}}]
        }
        with (
            patch("calendar_fetcher.consolidator.run_gws", return_value=doc_response),
            patch("calendar_fetcher.consolidator.run_gws_write") as mock_write,
        ):
            consolidate(populated_output_dir, "output_doc_id")
        mock_write.assert_not_called()

    def test_recreates_tab_for_changed_doc(self, populated_output_dir):
        state = {
            "consolidate_state": {
                "last_run": "2026-04-03T15:00:00Z",
                "output_doc_id": "output_doc_id",
                "tabs": {"abc123": {"tab_id": "t.old", "source_mtime": "0.0"}},
            }
        }
        with open(populated_output_dir / "fetcher-state.json", "w") as f:
            json.dump(state, f)
        doc_response = {
            "tabs": [{"tabProperties": {"tabId": "t.old", "title": "abc123"}}]
        }
        delete_response = {"replies": [{}]}
        create_response = {
            "replies": [{"addDocumentTab": {"tabProperties": {"tabId": "t.new1"}}}]
        }
        insert_response = {"replies": [{}]}
        with (
            patch("calendar_fetcher.consolidator.run_gws", return_value=doc_response),
            patch(
                "calendar_fetcher.consolidator.run_gws_write",
                side_effect=[delete_response, create_response, insert_response],
            ) as mock_write,
        ):
            consolidate(populated_output_dir, "output_doc_id")
        assert mock_write.call_count == 3

    def test_writes_state_after_consolidation(self, populated_output_dir):
        doc_response = {"tabs": []}
        create_response = {
            "replies": [{"addDocumentTab": {"tabProperties": {"tabId": "t.new1"}}}]
        }
        insert_response = {"replies": [{}]}
        with (
            patch("calendar_fetcher.consolidator.run_gws", return_value=doc_response),
            patch(
                "calendar_fetcher.consolidator.run_gws_write",
                side_effect=[create_response, insert_response],
            ),
        ):
            consolidate(populated_output_dir, "output_doc_id")
        with open(populated_output_dir / "fetcher-state.json") as f:
            full_state = json.load(f)
        cs = full_state["consolidate_state"]
        assert cs["output_doc_id"] == "output_doc_id"
        assert "abc123" in cs["tabs"]
        assert cs["tabs"]["abc123"]["tab_id"] == "t.new1"

    def test_no_docs_found(self, tmp_path):
        with (
            patch("calendar_fetcher.consolidator.run_gws") as mock_gws,
            patch("calendar_fetcher.consolidator.run_gws_write") as mock_write,
        ):
            consolidate(tmp_path, "output_doc_id")
        mock_gws.assert_not_called()
        mock_write.assert_not_called()
