# Generated By: Claude Code (Claude Opus 4.6)

"""Tests for calendar_fetcher.models dataclasses."""

from calendar_fetcher.models import Artifact, CalendarEvent, MeetingRecord


def test_artifact_creation_required_fields():
    """Artifact can be created with required fields."""
    artifact = Artifact(
        type="attachment",
        title="Meeting Notes",
        source_url="https://example.com/notes.pdf",
    )
    assert artifact.type == "attachment"
    assert artifact.title == "Meeting Notes"
    assert artifact.source_url == "https://example.com/notes.pdf"


def test_artifact_defaults():
    """Artifact optional fields default to None."""
    artifact = Artifact(
        type="transcript",
        title="Transcript",
        source_url="https://example.com/transcript.txt",
    )
    assert artifact.drive_file_id is None
    assert artifact.local_file is None
    assert artifact.mime_type is None
    assert artifact.source is None
    assert artifact.note is None


def test_artifact_all_fields():
    """Artifact can be created with all fields."""
    artifact = Artifact(
        type="recording",
        title="Meeting Recording",
        source_url="https://example.com/recording.mp4",
        drive_file_id="file123",
        local_file="/path/to/recording.mp4",
        mime_type="video/mp4",
        source="attached",
        note="Main recording",
    )
    assert artifact.type == "recording"
    assert artifact.title == "Meeting Recording"
    assert artifact.source_url == "https://example.com/recording.mp4"
    assert artifact.drive_file_id == "file123"
    assert artifact.local_file == "/path/to/recording.mp4"
    assert artifact.mime_type == "video/mp4"
    assert artifact.source == "attached"
    assert artifact.note == "Main recording"


def test_calendar_event_creation_required_fields():
    """CalendarEvent can be created with required fields."""
    event = CalendarEvent(
        event_id="evt123",
        calendar_id="cal456",
        summary="Team Standup",
        start="2026-04-01T10:00:00Z",
        end="2026-04-01T10:30:00Z",
    )
    assert event.event_id == "evt123"
    assert event.calendar_id == "cal456"
    assert event.summary == "Team Standup"
    assert event.start == "2026-04-01T10:00:00Z"
    assert event.end == "2026-04-01T10:30:00Z"


def test_calendar_event_defaults():
    """CalendarEvent optional fields have proper defaults."""
    event = CalendarEvent(
        event_id="evt123",
        calendar_id="cal456",
        summary="Team Standup",
        start="2026-04-01T10:00:00Z",
        end="2026-04-01T10:30:00Z",
    )
    assert event.description == ""
    assert event.recurring_event_id is None
    assert event.meet_code is None
    assert event.attachments == []
    assert event.api_response == {}


def test_calendar_event_all_fields():
    """CalendarEvent can be created with all fields."""
    artifact = Artifact(
        type="attachment",
        title="Agenda",
        source_url="https://example.com/agenda.pdf",
    )
    event = CalendarEvent(
        event_id="evt123",
        calendar_id="cal456",
        summary="Team Standup",
        start="2026-04-01T10:00:00Z",
        end="2026-04-01T10:30:00Z",
        description="Daily standup meeting",
        recurring_event_id="recurring123",
        meet_code="abc-defg-hij",
        attachments=[artifact],
        api_response={"kind": "calendar#event"},
    )
    assert event.event_id == "evt123"
    assert event.calendar_id == "cal456"
    assert event.summary == "Team Standup"
    assert event.start == "2026-04-01T10:00:00Z"
    assert event.end == "2026-04-01T10:30:00Z"
    assert event.description == "Daily standup meeting"
    assert event.recurring_event_id == "recurring123"
    assert event.meet_code == "abc-defg-hij"
    assert len(event.attachments) == 1
    assert event.attachments[0] == artifact
    assert event.api_response == {"kind": "calendar#event"}


def test_meeting_record_creation():
    """MeetingRecord links an event to artifacts."""
    event = CalendarEvent(
        event_id="evt123",
        calendar_id="cal456",
        summary="Team Meeting",
        start="2026-04-01T10:00:00Z",
        end="2026-04-01T11:00:00Z",
    )
    artifact = Artifact(
        type="transcript",
        title="Meeting Transcript",
        source_url="https://example.com/transcript.txt",
    )
    record = MeetingRecord(
        event=event,
        artifacts=[artifact],
    )
    assert record.event == event
    assert len(record.artifacts) == 1
    assert record.artifacts[0] == artifact


def test_meeting_record_defaults():
    """MeetingRecord defaults to empty lists and dicts."""
    event = CalendarEvent(
        event_id="evt123",
        calendar_id="cal456",
        summary="Team Meeting",
        start="2026-04-01T10:00:00Z",
        end="2026-04-01T11:00:00Z",
    )
    record = MeetingRecord(event=event)
    assert record.event == event
    assert record.artifacts == []
    assert record.meet_api_response == {}


def test_meeting_record_all_fields():
    """MeetingRecord can be created with all fields."""
    event = CalendarEvent(
        event_id="evt123",
        calendar_id="cal456",
        summary="Team Meeting",
        start="2026-04-01T10:00:00Z",
        end="2026-04-01T11:00:00Z",
    )
    artifact = Artifact(
        type="recording",
        title="Meeting Recording",
        source_url="https://example.com/recording.mp4",
    )
    record = MeetingRecord(
        event=event,
        artifacts=[artifact],
        meet_api_response={"conferenceId": "conf123"},
    )
    assert record.event == event
    assert len(record.artifacts) == 1
    assert record.artifacts[0] == artifact
    assert record.meet_api_response == {"conferenceId": "conf123"}
