# Generated By: Claude Code (Claude Opus 4.6)

"""Tests for Drive API client module."""

from unittest.mock import MagicMock, patch

from calendar_fetcher.drive_client import (
    export_doc_as_markdown,
    export_slides_as_pdf,
    fetch_sheet_tab_data,
    fetch_sheet_tabs,
    get_file_metadata,
    list_folder_files,
)
from calendar_fetcher.gws import GWSError


class TestGetFileMetadata:
    """Tests for get_file_metadata function."""

    def test_get_file_metadata_success(self):
        """Verify returns metadata dict on success."""
        mock_response = {
            "id": "file123",
            "name": "Test Doc",
            "mimeType": "application/vnd.google-apps.document",
        }

        with patch("calendar_fetcher.drive_client.run_gws", return_value=mock_response):
            result = get_file_metadata("file123")

        assert result == mock_response

    def test_get_file_metadata_access_denied(self):
        """Verify returns None when GWSError raised."""
        with patch(
            "calendar_fetcher.drive_client.run_gws",
            side_effect=GWSError("Access denied"),
        ):
            result = get_file_metadata("file123")

        assert result is None

    def test_get_file_metadata_not_found(self):
        """Verify returns None when file not found."""
        with patch(
            "calendar_fetcher.drive_client.run_gws",
            side_effect=GWSError("File not found"),
        ):
            result = get_file_metadata("file123")

        assert result is None


class TestExportDocAsMarkdown:
    """Tests for export_doc_as_markdown function."""

    def test_export_doc_as_markdown_success(self, tmp_path):
        """Verify exports doc as markdown via Drive API."""
        output_path = tmp_path / "doc.md"

        with patch(
            "calendar_fetcher.drive_client.run_gws", return_value={}
        ) as mock_run:
            output_path.write_text("# Test Doc")
            result = export_doc_as_markdown("doc123", str(output_path))

        assert result == str(output_path)
        mock_run.assert_called_once_with(
            "drive",
            "files",
            "export",
            params={"fileId": "doc123", "mimeType": "text/markdown"},
            output_file=str(output_path),
        )

    def test_export_doc_as_markdown_error(self, tmp_path):
        """Verify returns None on GWSError."""
        output_path = tmp_path / "doc.md"

        with patch(
            "calendar_fetcher.drive_client.run_gws",
            side_effect=GWSError("Export failed"),
        ):
            result = export_doc_as_markdown("doc123", str(output_path))

        assert result is None


class TestFetchSheetTabs:
    """Tests for fetch_sheet_tabs function."""

    def test_fetch_sheet_tabs_success(self):
        """Verify returns tab properties list."""
        mock_response = {
            "sheets": [
                {"properties": {"title": "Sheet1", "sheetId": 0}},
                {"properties": {"title": "Sheet2", "sheetId": 1}},
            ]
        }

        with patch("calendar_fetcher.drive_client.run_gws", return_value=mock_response):
            result = fetch_sheet_tabs("sheet123")

        assert len(result) == 2
        assert result[0] == {"title": "Sheet1", "sheetId": 0}
        assert result[1] == {"title": "Sheet2", "sheetId": 1}

    def test_fetch_sheet_tabs_error(self):
        """Verify returns empty list on GWSError."""
        with patch(
            "calendar_fetcher.drive_client.run_gws",
            side_effect=GWSError("API error"),
        ):
            result = fetch_sheet_tabs("sheet123")

        assert result == []

    def test_fetch_sheet_tabs_empty(self):
        """Verify handles empty sheets response."""
        mock_response = {}

        with patch("calendar_fetcher.drive_client.run_gws", return_value=mock_response):
            result = fetch_sheet_tabs("sheet123")

        assert result == []


class TestFetchSheetTabData:
    """Tests for fetch_sheet_tab_data function."""

    def test_fetch_sheet_tab_data_success(self, tmp_path):
        """Verify exports sheet tab as CSV via Sheets values API."""
        output_path = tmp_path / "output.csv"
        mock_response = {}

        with patch(
            "calendar_fetcher.drive_client.run_gws", return_value=mock_response
        ) as mock_run:
            output_path.write_text("col1,col2\nval1,val2\n")
            result = fetch_sheet_tab_data("sheet123", "Sheet1", str(output_path))

        assert result == str(output_path)
        mock_run.assert_called_once_with(
            "sheets",
            "spreadsheets",
            "values",
            "get",
            params={"spreadsheetId": "sheet123", "range": "'Sheet1'"},
            output_file=str(output_path),
            format="csv",
        )

    def test_fetch_sheet_tab_data_error(self, tmp_path):
        """Verify returns None on GWSError."""
        output_path = tmp_path / "output.csv"

        with patch(
            "calendar_fetcher.drive_client.run_gws",
            side_effect=GWSError("Export failed"),
        ):
            result = fetch_sheet_tab_data("sheet123", "Sheet1", str(output_path))

        assert result is None


class TestExportSlidesAsPdf:
    """Tests for export_slides_as_pdf function."""

    def test_export_slides_as_pdf_success(self, tmp_path):
        """Verify exports slides as PDF."""
        output_path = tmp_path / "slides.pdf"
        mock_response = {}

        with patch(
            "calendar_fetcher.drive_client.run_gws", return_value=mock_response
        ) as mock_run:
            # Create the file to simulate export
            output_path.write_bytes(b"PDF content")
            result = export_slides_as_pdf("slides123", str(output_path))

        assert result == str(output_path)
        mock_run.assert_called_once_with(
            "drive",
            "files",
            "export",
            params={"fileId": "slides123", "mimeType": "application/pdf"},
            output_file=str(output_path),
        )

    def test_export_slides_as_pdf_error(self, tmp_path):
        """Verify returns None on GWSError."""
        output_path = tmp_path / "slides.pdf"

        with patch(
            "calendar_fetcher.drive_client.run_gws",
            side_effect=GWSError("Export failed"),
        ):
            result = export_slides_as_pdf("slides123", str(output_path))

        assert result is None


class TestListFolderFiles:
    """Tests for list_folder_files function."""

    @patch("calendar_fetcher.drive_client.run_gws")
    def test_list_folder_files_paginates(self, mock_run_gws: MagicMock) -> None:
        """Verify pagination follows nextPageToken until exhausted."""
        mock_run_gws.side_effect = [
            {
                "files": [{"name": "file1.txt"}, {"name": "file2.txt"}],
                "nextPageToken": "token_page2",
            },
            {
                "files": [{"name": "file3.txt"}, {"name": "file4.txt"}],
            },
        ]

        result = list_folder_files("folder123")

        assert result == {"file1.txt", "file2.txt", "file3.txt", "file4.txt"}
        assert mock_run_gws.call_count == 2

        # First call has no pageToken
        first_params = mock_run_gws.call_args_list[0][1]["params"]
        assert "pageToken" not in first_params

        # Second call includes pageToken from first response
        second_params = mock_run_gws.call_args_list[1][1]["params"]
        assert second_params["pageToken"] == "token_page2"

    @patch("calendar_fetcher.drive_client.run_gws")
    def test_list_folder_files_single_page(self, mock_run_gws: MagicMock) -> None:
        """Verify single page response works without pagination."""
        mock_run_gws.return_value = {
            "files": [{"name": "only_file.txt"}],
        }

        result = list_folder_files("folder123")

        assert result == {"only_file.txt"}
        assert mock_run_gws.call_count == 1

    @patch("calendar_fetcher.drive_client.run_gws")
    def test_list_folder_files_error(self, mock_run_gws: MagicMock) -> None:
        """Verify returns empty set on GWSError."""
        mock_run_gws.side_effect = GWSError("API error")

        result = list_folder_files("folder123")

        assert result == set()
