# Generated By: Claude Code (Claude Sonnet 4.5)

"""Tests for cache module."""

import time

from calendar_fetcher.cache import FileCache


class TestFileCache:
    """Tests for FileCache class."""

    def test_cache_miss_returns_none(self, tmp_path):
        """Verify get returns None for missing key."""
        cache_path = tmp_path / "cache.json"
        cache = FileCache(cache_path)

        result = cache.get("nonexistent")

        assert result is None

    def test_cache_set_and_get(self, tmp_path):
        """Verify set and get work correctly."""
        cache_path = tmp_path / "cache.json"
        cache = FileCache(cache_path)

        test_value = {"name": "John Doe", "email": "john@example.com"}
        cache.set("12345", test_value)
        result = cache.get("12345")

        assert result == test_value

    def test_cache_expired_returns_none(self, tmp_path):
        """Verify expired entries return None."""
        cache_path = tmp_path / "cache.json"
        cache = FileCache(cache_path, ttl_days=1)

        # Manually write an expired entry
        old_timestamp = time.time() - (2 * 86400)  # 2 days ago
        cache._data["old_key"] = {
            "value": {"name": "Old User"},
            "timestamp": old_timestamp,
        }
        cache._save()

        result = cache.get("old_key")

        assert result is None

    def test_cache_persists_to_disk(self, tmp_path):
        """Verify cache persists across instances."""
        cache_path = tmp_path / "cache.json"

        # First cache instance
        cache1 = FileCache(cache_path)
        test_value = {"name": "Jane Doe", "email": "jane@example.com"}
        cache1.set("67890", test_value)

        # Second cache instance reading same file
        cache2 = FileCache(cache_path)
        result = cache2.get("67890")

        assert result == test_value

    def test_cache_handles_corrupt_file(self, tmp_path):
        """Verify cache loads without error when file has invalid JSON."""
        cache_path = tmp_path / "cache.json"

        # Write invalid JSON
        cache_path.write_text("{invalid json content")

        # Should not raise exception
        cache = FileCache(cache_path)

        # Should have empty data
        assert cache._data == {}

    def test_cache_creates_parent_directory(self, tmp_path):
        """Verify cache creates parent directories when needed."""
        cache_path = tmp_path / "nested" / "dirs" / "cache.json"
        cache = FileCache(cache_path)

        test_value = {"name": "Test User"}
        cache.set("key1", test_value)

        assert cache_path.exists()
        assert cache_path.parent.is_dir()
        result = cache.get("key1")
        assert result == test_value
