# Generated By: Claude Code (Claude Opus 4.6)

"""Tests for CLI argument parsing."""

import argparse
import json
from datetime import date, timedelta
from pathlib import Path
from unittest.mock import patch

import pytest

from calendar_fetcher.__main__ import create_parser
from calendar_fetcher import config


def test_fetch_defaults():
    """Verify fetch subcommand uses defaults from config."""
    parser = create_parser()
    args = parser.parse_args(["fetch"])

    assert args.calendar_id == config.DEFAULT_CALENDAR_ID
    assert args.output_dir == config.DEFAULT_OUTPUT_DIR
    assert args.lookback_days == config.DEFAULT_LOOKBACK_DAYS
    assert args.date is None
    assert args.drive_folder_id is None
    assert args.debug is False
    assert args.dryrun is False
    assert args.quiet is False
    assert args.log_file is None


def test_fetch_with_date():
    """Verify --date option sets the date."""
    parser = create_parser()
    args = parser.parse_args(["fetch", "--date", "2024-03-15"])

    assert args.date == "2024-03-15"


def test_fetch_with_all_options():
    """Verify all fetch options can be set (using --date, not --lookback-days)."""
    parser = create_parser()
    args = parser.parse_args(
        [
            "fetch",
            "--calendar-id",
            "test@example.com",
            "--output-dir",
            "/tmp/output",
            "--date",
            "2024-03-15",
            "--drive-folder-id",
            "abc123",
            "--debug",
            "--dryrun",
            "-q",
            "--log-file",
            "/tmp/test.log",
        ]
    )

    assert args.calendar_id == "test@example.com"
    assert args.output_dir == "/tmp/output"
    assert args.date == "2024-03-15"
    assert args.drive_folder_id == "abc123"
    assert args.debug is True
    assert args.dryrun is True
    assert args.quiet is True
    assert args.log_file == "/tmp/test.log"


def test_refresh_metadata_defaults():
    """Verify refresh-metadata subcommand uses defaults."""
    parser = create_parser()
    args = parser.parse_args(["refresh-metadata"])

    assert args.output_dir == config.DEFAULT_OUTPUT_DIR
    assert args.debug is False
    assert args.quiet is False
    assert args.log_file is None


def test_status_defaults():
    """Verify status subcommand uses defaults."""
    parser = create_parser()
    args = parser.parse_args(["status"])

    assert args.output_dir == config.DEFAULT_OUTPUT_DIR


def test_list_calendars_no_args():
    """Verify list-calendars accepts no arguments."""
    parser = create_parser()
    args = parser.parse_args(["list-calendars"])

    assert args.subcommand == "list-calendars"


def test_debug_flag():
    """Verify --debug flag sets debug=True."""
    parser = create_parser()
    args = parser.parse_args(["fetch", "--debug"])

    assert args.debug is True


def test_quiet_flag():
    """Verify -q flag sets quiet=True."""
    parser = create_parser()
    args = parser.parse_args(["fetch", "-q"])

    assert args.quiet is True


def test_dryrun_flag():
    """Verify --dryrun flag sets dryrun=True."""
    parser = create_parser()
    args = parser.parse_args(["fetch", "--dryrun"])

    assert args.dryrun is True


# Handler tests


@patch("calendar_fetcher.__main__.metadata")
@patch("calendar_fetcher.__main__.exporter")
@patch("calendar_fetcher.__main__.calendar_client")
@patch("calendar_fetcher.__main__.check_auth_scopes")
def test_handle_fetch_processes_events(
    mock_check_auth, mock_calendar_client, mock_exporter, mock_metadata
):
    """Verify list_events called with correct date range, parse_event called.

    For each event, process_events called, build_and_write_index called.
    """
    from calendar_fetcher.__main__ import handle_fetch

    # Setup mocks
    mock_events = [{"id": "event1"}, {"id": "event2"}]
    mock_parsed_events = [{"event_id": "event1"}, {"event_id": "event2"}]
    mock_calendar_client.list_events.return_value = mock_events
    mock_calendar_client.parse_event.side_effect = mock_parsed_events
    mock_metadata.read_fetch_state.return_value = None

    # Create args
    args = argparse.Namespace(
        calendar_id="primary",
        output_dir="calendar-artifacts",
        lookback_days=7,
        date=None,
        drive_folder_id=None,
        dryrun=False,
        quiet=True,
    )

    # Execute
    handle_fetch(args)

    # Compute expected date range (no state file → anchor from today)
    today = date.today()
    lookback = today - timedelta(days=7)
    expected_time_min = f"{lookback.isoformat()}T00:00:00Z"
    expected_time_max = f"{today.isoformat()}T23:59:59Z"

    # Verify calls
    mock_check_auth.assert_called_once_with(upload=False)
    mock_calendar_client.list_events.assert_called_once_with(
        "primary", expected_time_min, expected_time_max
    )
    assert mock_calendar_client.parse_event.call_count == 2
    mock_calendar_client.parse_event.assert_any_call({"id": "event1"}, "primary")
    mock_calendar_client.parse_event.assert_any_call({"id": "event2"}, "primary")
    mock_exporter.process_events.assert_called_once_with(
        mock_parsed_events, Path("calendar-artifacts"), dryrun=False
    )
    mock_metadata.build_and_write_index.assert_called_once_with(
        Path("calendar-artifacts")
    )


@patch("calendar_fetcher.__main__.metadata")
@patch("calendar_fetcher.__main__.exporter")
@patch("calendar_fetcher.__main__.calendar_client")
@patch("calendar_fetcher.__main__.check_auth_scopes")
def test_handle_fetch_with_specific_date(
    mock_check_auth, mock_calendar_client, mock_exporter, mock_metadata
):
    """Verify --date produces correct time_min/time_max."""
    from calendar_fetcher.__main__ import handle_fetch

    # Setup mocks
    mock_calendar_client.list_events.return_value = []

    # Create args
    args = argparse.Namespace(
        calendar_id="primary",
        output_dir="calendar-artifacts",
        lookback_days=7,
        date="2024-03-15",
        drive_folder_id=None,
        dryrun=False,
        quiet=True,
    )

    # Execute
    handle_fetch(args)

    # Verify date range
    mock_calendar_client.list_events.assert_called_once_with(
        "primary", "2024-03-15T00:00:00Z", "2024-03-15T23:59:59Z"
    )


@patch("calendar_fetcher.__main__.metadata")
@patch("calendar_fetcher.__main__.exporter")
@patch("calendar_fetcher.__main__.calendar_client")
@patch("calendar_fetcher.__main__.check_auth_scopes")
def test_handle_fetch_dryrun_skips_index(
    mock_check_auth, mock_calendar_client, mock_exporter, mock_metadata
):
    """Verify dryrun=True, build_and_write_index NOT called."""
    from calendar_fetcher.__main__ import handle_fetch

    # Setup mocks
    mock_calendar_client.list_events.return_value = []
    mock_metadata.read_fetch_state.return_value = None

    # Create args
    args = argparse.Namespace(
        calendar_id="primary",
        output_dir="calendar-artifacts",
        lookback_days=7,
        date=None,
        drive_folder_id=None,
        dryrun=True,
        quiet=True,
    )

    # Execute
    handle_fetch(args)

    # Verify exporter called with dryrun=True
    mock_exporter.process_events.assert_called_once()
    assert mock_exporter.process_events.call_args[1]["dryrun"] is True

    # Verify index NOT built and state NOT written
    mock_metadata.build_and_write_index.assert_not_called()
    mock_metadata.write_fetch_state.assert_not_called()


@patch("calendar_fetcher.__main__.metadata")
def test_handle_refresh_metadata_calls_refresh(mock_metadata):
    """Verify refresh_all_metadata and build_and_write_index both called."""
    from calendar_fetcher.__main__ import handle_refresh_metadata

    # Setup mocks
    mock_metadata.refresh_all_metadata.return_value = 5

    # Create args
    args = argparse.Namespace(output_dir="calendar-artifacts", quiet=True)

    # Execute
    handle_refresh_metadata(args)

    # Verify calls
    mock_metadata.refresh_all_metadata.assert_called_once_with(
        Path("calendar-artifacts")
    )
    mock_metadata.build_and_write_index.assert_called_once_with(
        Path("calendar-artifacts")
    )


def test_handle_status_counts_files(tmp_path, capsys):
    """Create tmp_path with mock .meta.json files with artifacts.

    Verify output includes correct counts.
    """
    from calendar_fetcher.__main__ import handle_status

    # Create metadata files
    meta1 = tmp_path / "meeting1.meta.json"
    meta1.write_text(
        json.dumps(
            {
                "artifacts": [
                    {"local_file": "file1.pdf"},
                    {"local_file": "file2.pdf"},
                    {"local_file": None},
                ]
            }
        )
    )

    meta2 = tmp_path / "meeting2.meta.json"
    meta2.write_text(
        json.dumps(
            {
                "artifacts": [
                    {"local_file": "file3.pdf"},
                ]
            }
        )
    )

    meta3 = tmp_path / "meeting3.meta.json"
    meta3.write_text(json.dumps({"artifacts": []}))

    # Create args
    args = argparse.Namespace(output_dir=str(tmp_path))

    # Execute
    handle_status(args)

    # Verify output
    captured = capsys.readouterr()
    assert "Total meetings: 3" in captured.out
    assert "Total downloaded files: 3" in captured.out


@patch("calendar_fetcher.__main__.run_gws")
def test_handle_list_calendars_prints_calendars(mock_run_gws, capsys):
    """Verify run_gws called with calendarList list, verify output printed."""
    from calendar_fetcher.__main__ import handle_list_calendars

    # Setup mocks
    mock_run_gws.return_value = {
        "items": [
            {"id": "primary", "summary": "Primary Calendar"},
            {"id": "test@example.com", "summary": "Test Calendar"},
        ]
    }

    # Create args
    args = argparse.Namespace()

    # Execute
    handle_list_calendars(args)

    # Verify run_gws called correctly
    mock_run_gws.assert_called_once_with("calendar", "calendarList", "list")

    # Verify output
    captured = capsys.readouterr()
    assert "Primary Calendar" in captured.out
    assert "primary" in captured.out
    assert "Test Calendar" in captured.out
    assert "test@example.com" in captured.out


def test_main_resolves_tilde_in_output_dir():
    """Verify ~ in --output-dir is expanded to home directory."""
    from calendar_fetcher.__main__ import main

    with patch("calendar_fetcher.__main__.handle_fetch") as mock_handler:
        with patch(
            "sys.argv",
            ["calendar-fetcher", "fetch", "--output-dir", "~/my-artifacts"],
        ):
            main()

        resolved = mock_handler.call_args[0][0].output_dir
        assert "~" not in resolved
        assert resolved == str(Path.home() / "my-artifacts")


def test_main_resolves_tilde_in_log_file():
    """Verify ~ in --log-file is expanded to home directory."""
    from calendar_fetcher.__main__ import main

    with (
        patch("calendar_fetcher.__main__.handle_fetch") as mock_handler,
        patch("calendar_fetcher.__main__.configure_logging"),
    ):
        with patch(
            "sys.argv",
            [
                "calendar-fetcher",
                "fetch",
                "--log-file",
                "~/logs/fetch.log",
            ],
        ):
            main()

        resolved = mock_handler.call_args[0][0].log_file
        assert "~" not in resolved
        assert resolved == str(Path.home() / "logs" / "fetch.log")


def test_main_resolves_relative_output_dir():
    """Verify relative --output-dir is resolved to absolute path."""
    from calendar_fetcher.__main__ import main

    with patch("calendar_fetcher.__main__.handle_fetch") as mock_handler:
        with patch(
            "sys.argv",
            ["calendar-fetcher", "fetch", "--output-dir", "relative/path"],
        ):
            main()

        resolved = mock_handler.call_args[0][0].output_dir
        assert Path(resolved).is_absolute()


@patch("calendar_fetcher.__main__.metadata")
@patch("calendar_fetcher.__main__.exporter")
@patch("calendar_fetcher.__main__.calendar_client")
@patch("calendar_fetcher.__main__.check_auth_scopes")
def test_handle_fetch_anchors_lookback_from_state(
    mock_check_auth, mock_calendar_client, mock_exporter, mock_metadata
):
    """Verify lookback is anchored from state file date, not today."""
    from calendar_fetcher.__main__ import handle_fetch

    mock_calendar_client.list_events.return_value = []
    # Simulate last run was 2026-03-28 (Friday)
    mock_metadata.read_fetch_state.return_value = date(2026, 3, 28)

    args = argparse.Namespace(
        calendar_id="primary",
        output_dir="calendar-artifacts",
        lookback_days=7,
        date=None,
        drive_folder_id=None,
        dryrun=False,
        quiet=True,
    )

    handle_fetch(args)

    # time_min should be 2026-03-28 - 7 = 2026-03-21
    call_args = mock_calendar_client.list_events.call_args[0]
    assert call_args[1] == "2026-03-21T00:00:00Z"
    # time_max should be today
    today = date.today()
    assert call_args[2] == f"{today.isoformat()}T23:59:59Z"


@patch("calendar_fetcher.__main__.metadata")
@patch("calendar_fetcher.__main__.exporter")
@patch("calendar_fetcher.__main__.calendar_client")
@patch("calendar_fetcher.__main__.check_auth_scopes")
def test_handle_fetch_writes_state_after_success(
    mock_check_auth, mock_calendar_client, mock_exporter, mock_metadata
):
    """Verify write_fetch_state is called after successful non-dryrun fetch."""
    from calendar_fetcher.__main__ import handle_fetch

    mock_calendar_client.list_events.return_value = []
    mock_metadata.read_fetch_state.return_value = None

    args = argparse.Namespace(
        calendar_id="primary",
        output_dir="calendar-artifacts",
        lookback_days=7,
        date=None,
        drive_folder_id=None,
        dryrun=False,
        quiet=True,
    )

    handle_fetch(args)

    mock_metadata.write_fetch_state.assert_called_once_with(Path("calendar-artifacts"))


def test_lookback_days_non_default_value():
    """Verify --lookback-days accepts a non-default integer value."""
    parser = create_parser()
    args = parser.parse_args(["fetch", "--lookback-days", "14"])

    assert args.lookback_days == 14


def test_lookback_days_invalid_value():
    """Verify --lookback-days rejects non-integer input."""
    parser = create_parser()

    with pytest.raises(SystemExit):
        parser.parse_args(["fetch", "--lookback-days", "not-a-number"])


def test_date_and_lookback_days_mutually_exclusive():
    """Verify --date and --lookback-days cannot be used together."""
    parser = create_parser()

    with pytest.raises(SystemExit):
        parser.parse_args(["fetch", "--date", "2026-03-28", "--lookback-days", "7"])


def test_consolidate_subcommand_requires_output_doc_id():
    """Verify consolidate requires --output-doc-id."""
    parser = create_parser()
    with pytest.raises(SystemExit):
        parser.parse_args(["consolidate"])


def test_consolidate_subcommand_parses_args():
    """Verify consolidate parses all arguments."""
    parser = create_parser()
    args = parser.parse_args(
        [
            "consolidate",
            "--output-doc-id",
            "doc123",
            "--output-dir",
            "/tmp/artifacts",
            "--debug",
        ]
    )
    assert args.subcommand == "consolidate"
    assert args.output_doc_id == "doc123"
    assert args.output_dir == "/tmp/artifacts"
    assert args.debug is True


@patch("calendar_fetcher.__main__.consolidator")
@patch("calendar_fetcher.__main__.check_auth_scopes")
def test_handle_consolidate_calls_consolidator(
    mock_check_auth, mock_consolidator, tmp_path
):
    """Verify handle_consolidate calls auth check and consolidator."""
    from calendar_fetcher.__main__ import handle_consolidate

    mock_consolidator.consolidate.return_value = (1, 0, 0)
    args = argparse.Namespace(
        output_doc_id="doc123", output_dir=str(tmp_path), quiet=True
    )
    handle_consolidate(args)
    mock_check_auth.assert_called_once_with(consolidate=True)
    mock_consolidator.consolidate.assert_called_once_with(tmp_path, "doc123")


def test_handle_consolidate_exits_on_missing_dir(tmp_path):
    """Verify handle_consolidate exits if output dir doesn't exist."""
    from calendar_fetcher.__main__ import handle_consolidate

    args = argparse.Namespace(
        output_doc_id="doc123",
        output_dir=str(tmp_path / "nonexistent"),
        quiet=True,
    )
    with patch("calendar_fetcher.__main__.check_auth_scopes"):
        with pytest.raises(SystemExit) as exc_info:
            handle_consolidate(args)
    assert exc_info.value.code == 1
