# Generated By: Claude Code (Claude Opus 4.6)

"""Tests for calendar_client module."""

from unittest.mock import MagicMock, patch

from calendar_fetcher.calendar_client import (
    extract_attachments,
    extract_description_links,
    extract_meet_code,
    list_events,
    parse_event,
)


class TestListEvents:
    """Tests for list_events function."""

    @patch("calendar_fetcher.calendar_client.run_gws")
    def test_list_events_calls_gws_correctly(self, mock_run_gws: MagicMock) -> None:
        """Verify params passed to run_gws."""
        mock_run_gws.return_value = {"items": []}

        list_events(
            calendar_id="test@example.com",
            time_min="2024-01-01T00:00:00Z",
            time_max="2024-01-31T23:59:59Z",
        )

        mock_run_gws.assert_called_once_with(
            "calendar",
            "events",
            "list",
            params={
                "calendarId": "test@example.com",
                "timeMin": "2024-01-01T00:00:00Z",
                "timeMax": "2024-01-31T23:59:59Z",
                "singleEvents": True,
                "orderBy": "startTime",
            },
        )

    @patch("calendar_fetcher.calendar_client.run_gws")
    def test_list_events_paginates(self, mock_run_gws: MagicMock) -> None:
        """Verify pagination follows nextPageToken until exhausted."""
        mock_run_gws.side_effect = [
            {
                "items": [{"id": "event1"}],
                "nextPageToken": "token_page2",
            },
            {
                "items": [{"id": "event2"}],
                "nextPageToken": "token_page3",
            },
            {
                "items": [{"id": "event3"}],
            },
        ]

        result = list_events(
            calendar_id="test@example.com",
            time_min="2024-01-01T00:00:00Z",
            time_max="2024-01-31T23:59:59Z",
        )

        assert len(result) == 3
        assert [e["id"] for e in result] == ["event1", "event2", "event3"]
        assert mock_run_gws.call_count == 3

        # First call has no pageToken
        first_params = mock_run_gws.call_args_list[0][1]["params"]
        assert "pageToken" not in first_params

        # Second call includes pageToken from first response
        second_params = mock_run_gws.call_args_list[1][1]["params"]
        assert second_params["pageToken"] == "token_page2"

        # Third call includes pageToken from second response
        third_params = mock_run_gws.call_args_list[2][1]["params"]
        assert third_params["pageToken"] == "token_page3"

    @patch("calendar_fetcher.calendar_client.run_gws")
    def test_list_events_returns_items(self, mock_run_gws: MagicMock) -> None:
        """Return event items from API response."""
        mock_run_gws.return_value = {
            "items": [
                {"id": "event1", "summary": "Test Event 1"},
                {"id": "event2", "summary": "Test Event 2"},
            ]
        }

        result = list_events(
            calendar_id="test@example.com",
            time_min="2024-01-01T00:00:00Z",
            time_max="2024-01-31T23:59:59Z",
        )

        assert len(result) == 2
        assert result[0]["id"] == "event1"
        assert result[1]["id"] == "event2"

    @patch("calendar_fetcher.calendar_client.run_gws")
    def test_list_events_returns_empty_on_no_items(
        self, mock_run_gws: MagicMock
    ) -> None:
        """Response has no items key."""
        mock_run_gws.return_value = {}

        result = list_events(
            calendar_id="test@example.com",
            time_min="2024-01-01T00:00:00Z",
            time_max="2024-01-31T23:59:59Z",
        )

        assert result == []

    @patch("calendar_fetcher.calendar_client.run_gws")
    def test_list_events_filters_working_location(
        self, mock_run_gws: MagicMock
    ) -> None:
        """Verify workingLocation events are excluded."""
        mock_run_gws.return_value = {
            "items": [
                {"id": "event1", "summary": "Team Sync"},
                {"id": "wl1", "summary": "Home", "eventType": "workingLocation"},
                {"id": "event2", "summary": "Design Review"},
            ]
        }

        result = list_events(
            calendar_id="test@example.com",
            time_min="2024-01-01T00:00:00Z",
            time_max="2024-01-31T23:59:59Z",
        )

        assert len(result) == 2
        assert result[0]["id"] == "event1"
        assert result[1]["id"] == "event2"


class TestExtractAttachments:
    """Tests for extract_attachments function."""

    def test_extract_attachments_with_attachments(self) -> None:
        """Event with attachments list."""
        event = {
            "attachments": [
                {
                    "fileId": "file123",
                    "fileUrl": "https://drive.google.com/file/d/file123/view",
                    "mimeType": "application/pdf",
                    "title": "Report.pdf",
                },
                {
                    "fileId": "file456",
                    "fileUrl": "https://drive.google.com/file/d/file456/view",
                    "mimeType": "application/vnd.google-apps.spreadsheet",
                    "title": "Data.xlsx",
                },
            ]
        }

        result = extract_attachments(event)

        assert len(result) == 2
        assert result[0].type == "attachment"
        assert result[0].source == "attached"
        assert result[0].drive_file_id == "file123"
        assert result[0].source_url == "https://drive.google.com/file/d/file123/view"
        assert result[0].mime_type == "application/pdf"
        assert result[0].title == "Report.pdf"

        assert result[1].type == "attachment"
        assert result[1].source == "attached"
        assert result[1].drive_file_id == "file456"
        assert result[1].title == "Data.xlsx"

    def test_extract_attachments_no_attachments(self) -> None:
        """Event without attachments key."""
        event = {"id": "event123", "summary": "Test Event"}

        result = extract_attachments(event)

        assert result == []

    def test_extract_attachments_missing_file_id(self) -> None:
        """Attachment without fileId is skipped."""
        event = {
            "attachments": [
                {
                    "fileUrl": "https://example.com/file",
                    "mimeType": "application/pdf",
                    "title": "Document.pdf",
                },
                {
                    "fileId": "file123",
                    "fileUrl": "https://drive.google.com/file/d/file123/view",
                    "mimeType": "application/pdf",
                    "title": "Valid.pdf",
                },
            ]
        }

        result = extract_attachments(event)

        assert len(result) == 1
        assert result[0].drive_file_id == "file123"
        assert result[0].title == "Valid.pdf"

    def test_extract_attachments_missing_title(self) -> None:
        """Attachment without title uses empty string default."""
        event = {
            "attachments": [
                {
                    "fileId": "file123",
                    "fileUrl": "https://drive.google.com/file/d/file123/view",
                    "mimeType": "application/pdf",
                }
            ]
        }

        result = extract_attachments(event)

        assert len(result) == 1
        assert result[0].title == ""
        assert result[0].drive_file_id == "file123"

    def test_extract_attachments_missing_url(self) -> None:
        """Attachment without fileUrl uses empty string default."""
        event = {
            "attachments": [
                {
                    "fileId": "file123",
                    "title": "Document.pdf",
                    "mimeType": "application/pdf",
                }
            ]
        }

        result = extract_attachments(event)

        assert len(result) == 1
        assert result[0].source_url == ""
        assert result[0].drive_file_id == "file123"


class TestExtractDescriptionLinks:
    """Tests for extract_description_links function."""

    def test_extract_description_links_docs_url(self) -> None:
        """Description contains docs.google.com/document/d/ID/edit."""
        event = {
            "description": (
                "Check the doc: " "https://docs.google.com/document/d/ABC123XYZ/edit"
            )
        }

        result = extract_description_links(event)

        assert len(result) == 1
        assert result[0].type == "attachment"
        assert result[0].source == "description_link"
        assert result[0].drive_file_id == "ABC123XYZ"
        assert (
            result[0].source_url == "https://docs.google.com/document/d/ABC123XYZ/edit"
        )

    def test_extract_description_links_sheets_url(self) -> None:
        """Description contains docs.google.com/spreadsheets/d/ID/edit."""
        event = {
            "description": (
                "See spreadsheet: "
                "https://docs.google.com/spreadsheets/d/SHEET456/edit#gid=0"
            )
        }

        result = extract_description_links(event)

        assert len(result) == 1
        assert result[0].type == "attachment"
        assert result[0].source == "description_link"
        assert result[0].drive_file_id == "SHEET456"
        assert (
            result[0].source_url
            == "https://docs.google.com/spreadsheets/d/SHEET456/edit#gid=0"
        )

    def test_extract_description_links_slides_url(self) -> None:
        """Description contains docs.google.com/presentation/d/ID/edit."""
        event = {
            "description": (
                "Presentation: "
                "https://docs.google.com/presentation/d/SLIDES789/edit?usp=sharing"
            )
        }

        result = extract_description_links(event)

        assert len(result) == 1
        assert result[0].drive_file_id == "SLIDES789"
        assert (
            result[0].source_url
            == "https://docs.google.com/presentation/d/SLIDES789/edit?usp=sharing"
        )

    def test_extract_description_links_ignores_non_gws(self) -> None:
        """Description with github.com link returns empty list."""
        event = {"description": "Code at https://github.com/user/repo"}

        result = extract_description_links(event)

        assert result == []

    def test_extract_description_links_href_attribute(self) -> None:
        """Description with href attribute."""
        event = {
            "description": (
                '<a href="https://docs.google.com/document/d/HTML123/edit">'
                "Meeting Notes</a>"
            )
        }

        result = extract_description_links(event)

        assert len(result) == 1
        assert result[0].drive_file_id == "HTML123"
        assert result[0].source_url == "https://docs.google.com/document/d/HTML123/edit"

    def test_extract_description_links_deduplicates(self) -> None:
        """Same doc ID appears twice, returns one artifact."""
        event = {
            "description": (
                "Doc link: https://docs.google.com/document/d/DUP999/edit\n"
                "Same doc again: "
                "https://docs.google.com/document/d/DUP999/edit?usp=sharing"
            )
        }

        result = extract_description_links(event)

        assert len(result) == 1
        assert result[0].drive_file_id == "DUP999"

    def test_extract_description_links_multiple_different(self) -> None:
        """Multiple different docs in description."""
        event = {
            "description": (
                "Doc: https://docs.google.com/document/d/DOC1/edit\n"
                "Sheet: https://docs.google.com/spreadsheets/d/SHEET1/edit\n"
                "Slides: https://docs.google.com/presentation/d/SLIDE1/edit"
            )
        }

        result = extract_description_links(event)

        assert len(result) == 3
        file_ids = {a.drive_file_id for a in result}
        assert file_ids == {"DOC1", "SHEET1", "SLIDE1"}

    def test_extract_description_links_no_description(self) -> None:
        """Event without description key."""
        event = {"id": "event123"}

        result = extract_description_links(event)

        assert result == []


class TestExtractMeetCode:
    """Tests for extract_meet_code function."""

    def test_extract_meet_code_from_entry_points(self) -> None:
        """ConferenceData with video entryPoint."""
        event = {
            "conferenceData": {
                "entryPoints": [
                    {
                        "entryPointType": "video",
                        "uri": "https://meet.google.com/abc-defg-hij",
                        "label": "abc-defg-hij",
                    }
                ]
            }
        }

        result = extract_meet_code(event)

        assert result == "abc-defg-hij"

    def test_extract_meet_code_from_conference_id(self) -> None:
        """ConferenceData with conferenceId."""
        event = {
            "conferenceData": {
                "conferenceId": "xyz-uvwx-rst",
                "entryPoints": [
                    {
                        "entryPointType": "phone",
                        "uri": "tel:+1234567890",
                    }
                ],
            }
        }

        result = extract_meet_code(event)

        assert result == "xyz-uvwx-rst"

    def test_extract_meet_code_parses_from_uri(self) -> None:
        """Video entryPoint without label, parse from uri."""
        event = {
            "conferenceData": {
                "entryPoints": [
                    {
                        "entryPointType": "video",
                        "uri": "https://meet.google.com/parsed-code-here",
                    }
                ]
            }
        }

        result = extract_meet_code(event)

        assert result == "parsed-code-here"

    def test_extract_meet_code_none_without_conference(self) -> None:
        """No conferenceData returns None."""
        event = {"id": "event123", "summary": "Test Event"}

        result = extract_meet_code(event)

        assert result is None


class TestParseEvent:
    """Tests for parse_event function."""

    def test_parse_event_full(self) -> None:
        """Complete event with attachments, description links, meet code."""
        event = {
            "id": "event123",
            "summary": "Team Sync",
            "start": {"dateTime": "2024-01-15T10:00:00-05:00"},
            "end": {"dateTime": "2024-01-15T11:00:00-05:00"},
            "description": "Agenda: https://docs.google.com/document/d/AGENDA123/edit",
            "recurringEventId": "recurring456",
            "attachments": [
                {
                    "fileId": "file789",
                    "fileUrl": "https://drive.google.com/file/d/file789/view",
                    "mimeType": "application/pdf",
                    "title": "Notes.pdf",
                }
            ],
            "conferenceData": {
                "conferenceId": "meet-code-xyz",
            },
        }

        result = parse_event(event, calendar_id="user@example.com")

        assert result.event_id == "event123"
        assert result.calendar_id == "user@example.com"
        assert result.summary == "Team Sync"
        assert result.start == "2024-01-15T10:00:00-05:00"
        assert result.end == "2024-01-15T11:00:00-05:00"
        assert (
            result.description
            == "Agenda: https://docs.google.com/document/d/AGENDA123/edit"
        )
        assert result.recurring_event_id == "recurring456"
        assert result.meet_code == "meet-code-xyz"
        assert len(result.attachments) == 2  # 1 attached + 1 description link
        assert result.api_response == event

        # Check attached file
        attached = [a for a in result.attachments if a.source == "attached"]
        assert len(attached) == 1
        assert attached[0].drive_file_id == "file789"

        # Check description link
        desc_links = [a for a in result.attachments if a.source == "description_link"]
        assert len(desc_links) == 1
        assert desc_links[0].drive_file_id == "AGENDA123"

    def test_parse_event_minimal(self) -> None:
        """Minimal event with only required fields."""
        event = {
            "id": "minimal123",
            "start": {"dateTime": "2024-02-01T14:00:00Z"},
            "end": {"dateTime": "2024-02-01T15:00:00Z"},
        }

        result = parse_event(event, calendar_id="calendar@example.com")

        assert result.event_id == "minimal123"
        assert result.calendar_id == "calendar@example.com"
        assert result.summary == ""
        assert result.description == ""
        assert result.recurring_event_id is None
        assert result.meet_code is None
        assert result.attachments == []

    def test_parse_event_all_day(self) -> None:
        """All-day event uses date instead of dateTime."""
        event = {
            "id": "allday123",
            "summary": "Holiday",
            "start": {"date": "2024-07-04"},
            "end": {"date": "2024-07-05"},
        }

        result = parse_event(event, calendar_id="calendar@example.com")

        assert result.start == "2024-07-04"
        assert result.end == "2024-07-05"
