# Generated By: Claude Code (Claude Opus 4.6)

"""Tests for section extraction from meeting notes."""

from datetime import date

from calendar_fetcher.section_extractor import (
    _find_date_heading_level,
    _parse_heading_date,
    extract_section,
)

SAMPLE_DOC = """\
# Weekly Sync Agenda

Regular attendees: Alice, Bob, Charlie

Standing topics:
- Status updates
- Blockers

---

## Apr 30, 2026 | [Weekly Sync](https://meet.google.com/abc)

Attendees: Alice, Bob

Notes
* Alice: shipped feature X
* Bob: working on Y

Action items
- [ ] Alice follow up on Z

---

## Apr 23, 2026 | [Weekly Sync](https://meet.google.com/abc)

Attendees: Alice, Charlie

Notes
* Alice: planning feature X
* Charlie: reviewed PR

---

## Apr 16, 2026 | [Weekly Sync](https://meet.google.com/abc)

Attendees: Bob, Charlie

Notes
* Bob: started Y
* Charlie: docs update"""


class TestParseHeadingDate:
    def test_abbreviated_month_with_pipe(self):
        assert _parse_heading_date("Apr 30, 2026 | [Title](link)") == date(2026, 4, 30)

    def test_cancelled_bold(self):
        assert _parse_heading_date("Feb 26, 2026 **Cancelled**") == date(2026, 2, 26)

    def test_strikethrough_rescheduled(self):
        result = _parse_heading_date("~~Dec 5, 2024~~ Dec 12, 2024 | [Title](link)")
        assert result == date(2024, 12, 12)

    def test_italic_cancelled(self):
        assert _parse_heading_date("*Oct 10, 2024 Call canceled*") == date(2024, 10, 10)

    def test_non_date_heading(self):
        assert _parse_heading_date("Five Dysfunctions of a Team Reminder") is None

    def test_empty(self):
        assert _parse_heading_date("") is None

    def test_iso_format(self):
        assert _parse_heading_date("2026-04-30 | [Title](link)") == date(2026, 4, 30)

    def test_full_month_name(self):
        assert _parse_heading_date("April 30, 2026 | [Title](link)") == date(
            2026, 4, 30
        )


class TestFindDateHeadingLevel:
    def test_all_h2(self):
        lines = [
            "# Title",
            "",
            "## Apr 30, 2026 | Meeting",
            "notes",
            "## Apr 23, 2026 | Meeting",
            "notes",
        ]
        assert _find_date_heading_level(lines) == 2

    def test_no_date_headings(self):
        lines = [
            "# Title",
            "## Section A",
            "## Section B",
        ]
        assert _find_date_heading_level(lines) is None

    def test_mixed_levels_majority_wins(self):
        lines = [
            "# Apr 30, 2026",
            "## Apr 23, 2026",
            "## Apr 16, 2026",
            "## Apr 9, 2026",
        ]
        assert _find_date_heading_level(lines) == 2

    def test_empty_lines(self):
        assert _find_date_heading_level([]) is None


class TestExtractSection:
    def test_middle_section(self):
        result = extract_section(SAMPLE_DOC, "2026-04-23")
        assert result is not None
        assert "Apr 23, 2026" in result
        assert "planning feature X" in result
        assert "Regular attendees" in result  # preamble included
        assert "Apr 30, 2026" not in result
        assert "Apr 16, 2026" not in result

    def test_first_section(self):
        result = extract_section(SAMPLE_DOC, "2026-04-30")
        assert result is not None
        assert "Apr 30, 2026" in result
        assert "shipped feature X" in result
        assert "Regular attendees" in result
        assert "Apr 23, 2026" not in result

    def test_last_section(self):
        result = extract_section(SAMPLE_DOC, "2026-04-16")
        assert result is not None
        assert "Apr 16, 2026" in result
        assert "started Y" in result
        assert "Regular attendees" in result
        assert "Apr 23, 2026" not in result

    def test_no_match(self):
        assert extract_section(SAMPLE_DOC, "2026-05-01") is None

    def test_no_date_structure(self):
        content = "# Just a Document\n\nSome content without date headings.\n"
        assert extract_section(content, "2026-04-30") is None

    def test_idempotent(self):
        first = extract_section(SAMPLE_DOC, "2026-04-23")
        assert first is not None
        second = extract_section(first, "2026-04-23")
        assert second is not None
        assert second == first

    def test_trailing_separator_stripped(self):
        result = extract_section(SAMPLE_DOC, "2026-04-30")
        assert result is not None
        assert not result.rstrip().endswith("---")

    def test_cancelled_meeting(self):
        doc = """\
# Notes

## Apr 30, 2026 | Meeting

Real notes here.

---

## Apr 23, 2026 **Cancelled**

---

## Apr 16, 2026 | Meeting

Older notes."""
        result = extract_section(doc, "2026-04-23")
        assert result is not None
        assert "Cancelled" in result

    def test_preamble_separator(self):
        result = extract_section(SAMPLE_DOC, "2026-04-30")
        assert result is not None
        assert "\n\n---\n\n" in result

    def test_no_preamble(self):
        doc = """\
## Apr 30, 2026 | Meeting

Notes here.

## Apr 23, 2026 | Meeting

Older notes."""
        result = extract_section(doc, "2026-04-30")
        assert result is not None
        assert result.startswith("## Apr 30, 2026")
        assert "---" not in result.split("## Apr 30")[0]

    def test_iso_date_headings(self):
        doc = """\
# Notes

## 2026-04-30 | Meeting

Notes here.

## 2026-04-23 | Meeting

Older notes."""
        result = extract_section(doc, "2026-04-30")
        assert result is not None
        assert "2026-04-30" in result
        assert "2026-04-23" not in result
