# Generated By: Claude Code (Claude Opus 4.6)

"""Tests for Meet API client module."""

from unittest.mock import patch

from calendar_fetcher.meet_client import (
    get_all_meet_data,
    get_conference_record,
    get_participants,
    get_recordings,
    get_transcripts,
)
from calendar_fetcher.models import Artifact


class TestGetConferenceRecord:
    """Tests for get_conference_record function."""

    def test_get_conference_record_found(self):
        """Verify returns first conference record when found."""
        mock_response = {
            "conferenceRecords": [
                {
                    "name": "conferenceRecords/abc-123",
                    "space": {"meetingCode": "abc-defg-hij"},
                }
            ]
        }

        with patch("calendar_fetcher.meet_client.run_gws", return_value=mock_response):
            result = get_conference_record("abc-defg-hij")

        assert result == {
            "name": "conferenceRecords/abc-123",
            "space": {"meetingCode": "abc-defg-hij"},
        }

    def test_get_conference_record_not_found(self):
        """Verify returns None when no conference records found."""
        mock_response = {}

        with patch("calendar_fetcher.meet_client.run_gws", return_value=mock_response):
            result = get_conference_record("abc-defg-hij")

        assert result is None

    def test_get_conference_record_empty_list(self):
        """Verify returns None when conferenceRecords is empty list."""
        mock_response = {"conferenceRecords": []}

        with patch("calendar_fetcher.meet_client.run_gws", return_value=mock_response):
            result = get_conference_record("abc-defg-hij")

        assert result is None


class TestGetTranscripts:
    """Tests for get_transcripts function."""

    def test_get_transcripts_with_data(self):
        """Verify returns Artifact list with correct fields."""
        mock_response = {
            "transcripts": [
                {
                    "name": "conferenceRecords/abc/transcripts/xyz",
                    "docsDestination": {
                        "document": "doc123",
                        "exportUri": "https://docs.google.com/document/d/doc123/export",
                    },
                }
            ]
        }

        with patch("calendar_fetcher.meet_client.run_gws", return_value=mock_response):
            result = get_transcripts("conferenceRecords/abc-123")

        assert len(result) == 1
        assert isinstance(result[0], Artifact)
        assert result[0].type == "transcript"
        assert result[0].title == "Transcript"
        assert (
            result[0].source_url == "https://docs.google.com/document/d/doc123/export"
        )
        assert result[0].drive_file_id == "doc123"
        assert result[0].mime_type == "application/vnd.google-apps.document"

    def test_get_transcripts_empty(self):
        """Verify returns empty list when no transcripts."""
        mock_response = {}

        with patch("calendar_fetcher.meet_client.run_gws", return_value=mock_response):
            result = get_transcripts("conferenceRecords/abc-123")

        assert result == []

    def test_get_transcripts_empty_list(self):
        """Verify returns empty list when transcripts is empty list."""
        mock_response = {"transcripts": []}

        with patch("calendar_fetcher.meet_client.run_gws", return_value=mock_response):
            result = get_transcripts("conferenceRecords/abc-123")

        assert result == []


class TestGetRecordings:
    """Tests for get_recordings function."""

    def test_get_recordings_with_data(self):
        """Verify returns Artifact list with recording note."""
        mock_response = {
            "recordings": [
                {
                    "name": "conferenceRecords/abc/recordings/rec1",
                    "driveDestination": {
                        "file": "file456",
                        "exportUri": "https://drive.google.com/file/d/file456/view",
                    },
                }
            ]
        }

        with patch("calendar_fetcher.meet_client.run_gws", return_value=mock_response):
            result = get_recordings("conferenceRecords/abc-123")

        assert len(result) == 1
        assert isinstance(result[0], Artifact)
        assert result[0].type == "recording"
        assert result[0].title == "Recording"
        assert result[0].source_url == "https://drive.google.com/file/d/file456/view"
        assert result[0].drive_file_id == "file456"
        assert (
            result[0].note
            == "Recording download may be restricted by organization policy"
        )

    def test_get_recordings_empty(self):
        """Verify returns empty list when no recordings."""
        mock_response = {}

        with patch("calendar_fetcher.meet_client.run_gws", return_value=mock_response):
            result = get_recordings("conferenceRecords/abc-123")

        assert result == []

    def test_get_recordings_empty_list(self):
        """Verify returns empty list when recordings is empty list."""
        mock_response = {"recordings": []}

        with patch("calendar_fetcher.meet_client.run_gws", return_value=mock_response):
            result = get_recordings("conferenceRecords/abc-123")

        assert result == []


class TestGetParticipants:
    """Tests for get_participants function."""

    def test_get_participants_with_data(self):
        """Verify returns raw participant dicts."""
        mock_response = {
            "participants": [
                {
                    "name": "conferenceRecords/abc/participants/12345",
                    "signedinUser": {
                        "displayName": "John Doe",
                        "user": "users/12345",
                    },
                },
                {
                    "name": "conferenceRecords/abc/participants/67890",
                    "signedinUser": {
                        "displayName": "Jane Smith",
                        "user": "users/67890",
                    },
                },
            ]
        }

        with patch("calendar_fetcher.meet_client.run_gws", return_value=mock_response):
            result = get_participants("conferenceRecords/abc-123")

        assert len(result) == 2
        assert result[0]["signedinUser"]["displayName"] == "John Doe"
        assert result[1]["signedinUser"]["displayName"] == "Jane Smith"

    def test_get_participants_empty(self):
        """Verify returns empty list when no participants."""
        mock_response = {}

        with patch("calendar_fetcher.meet_client.run_gws", return_value=mock_response):
            result = get_participants("conferenceRecords/abc-123")

        assert result == []

    def test_get_participants_empty_list(self):
        """Verify returns empty list when participants is empty list."""
        mock_response = {"participants": []}

        with patch("calendar_fetcher.meet_client.run_gws", return_value=mock_response):
            result = get_participants("conferenceRecords/abc-123")

        assert result == []


class TestGetAllMeetData:
    """Tests for get_all_meet_data function."""

    def test_get_all_meet_data_full(self):
        """Verify orchestrates all calls and returns artifacts + api response."""
        conference_response = {
            "conferenceRecords": [
                {
                    "name": "conferenceRecords/abc-123",
                    "space": {"meetingCode": "abc-defg-hij"},
                }
            ]
        }

        transcripts_response = {
            "transcripts": [
                {
                    "name": "conferenceRecords/abc-123/transcripts/xyz",
                    "docsDestination": {
                        "document": "doc123",
                        "exportUri": "https://docs.google.com/document/d/doc123/export",
                    },
                }
            ]
        }

        recordings_response = {
            "recordings": [
                {
                    "name": "conferenceRecords/abc-123/recordings/rec1",
                    "driveDestination": {
                        "file": "file456",
                        "exportUri": "https://drive.google.com/file/d/file456/view",
                    },
                }
            ]
        }

        participants_response = {
            "participants": [
                {
                    "name": "conferenceRecords/abc-123/participants/12345",
                    "signedinUser": {
                        "displayName": "John Doe",
                        "user": "users/12345",
                    },
                }
            ]
        }

        def mock_run_gws(*args, **kwargs):
            if args[0] == "meet" and args[2] == "list":
                return conference_response
            elif args[0] == "meet" and args[2] == "transcripts":
                return transcripts_response
            elif args[0] == "meet" and args[2] == "recordings":
                return recordings_response
            elif args[0] == "meet" and args[2] == "participants":
                return participants_response
            return {}

        with patch("calendar_fetcher.meet_client.run_gws", side_effect=mock_run_gws):
            artifacts, api_response = get_all_meet_data("abc-defg-hij")

        assert len(artifacts) == 2
        assert artifacts[0].type == "transcript"
        assert artifacts[1].type == "recording"

        assert "conference_record" in api_response
        assert "transcripts" in api_response
        assert "recordings" in api_response
        assert "participants" in api_response
        assert api_response["conference_record"]["name"] == "conferenceRecords/abc-123"
        assert len(api_response["participants"]) == 1

    def test_get_all_meet_data_no_conference(self):
        """Verify returns empty results when no conference record found."""
        mock_response = {}

        with patch("calendar_fetcher.meet_client.run_gws", return_value=mock_response):
            artifacts, api_response = get_all_meet_data("abc-defg-hij")

        assert artifacts == []
        assert api_response == {}
