# Generated By: Claude Code (Claude Opus 4.6)

"""Tests for metadata module."""

import json

import pytest

from calendar_fetcher.metadata import (
    build_and_write_index,
    build_index_entry,
    build_meeting_metadata,
    metadata_filename,
    refresh_all_metadata,
    write_metadata,
)
from calendar_fetcher.models import Artifact, CalendarEvent, MeetingRecord


@pytest.fixture
def sample_event():
    """Sample calendar event for testing."""
    return CalendarEvent(
        event_id="evt123",
        calendar_id="cal456",
        summary="Weekly Sync",
        start="2026-03-15T14:00:00Z",
        end="2026-03-15T15:00:00Z",
        description="Team sync meeting",
        recurring_event_id="rec789",
        meet_code="abc-defg-hij",
        api_response={
            "id": "evt123",
            "summary": "Weekly Sync",
            "start": {"dateTime": "2026-03-15T14:00:00Z"},
            "end": {"dateTime": "2026-03-15T15:00:00Z"},
        },
    )


@pytest.fixture
def sample_artifacts():
    """Sample artifacts for testing."""
    return [
        Artifact(
            type="transcript",
            title="Meeting Transcript",
            source_url="https://drive.google.com/file/d/trans123",
            drive_file_id="trans123",
            local_file="2026-03-15_weekly-sync_transcript.txt",
            mime_type="text/plain",
            source="description_link",
            note="Auto-generated",
        ),
        Artifact(
            type="recording",
            title="Meeting Recording",
            source_url="https://drive.google.com/file/d/rec456",
            drive_file_id="rec456",
            local_file=None,  # Not downloaded yet
            mime_type="video/mp4",
            source="description_link",
            note=None,
        ),
        Artifact(
            type="attachment",
            title="Slides",
            source_url="https://docs.google.com/presentation/d/slides789",
            drive_file_id="slides789",
            local_file="2026-03-15_weekly-sync_slides.pdf",
            mime_type="application/pdf",
            source="attached",
            note=None,
        ),
    ]


@pytest.fixture
def sample_meeting(sample_event, sample_artifacts):
    """Sample meeting record for testing."""
    return MeetingRecord(
        event=sample_event,
        artifacts=sample_artifacts,
        meet_api_response={
            "conferenceRecords": [
                {
                    "name": "conferenceRecords/abc-defg-hij",
                    "startTime": "2026-03-15T14:00:00Z",
                }
            ]
        },
    )


def test_build_meeting_metadata(sample_meeting):
    """Test building metadata dict from meeting record."""
    metadata = build_meeting_metadata(sample_meeting)

    assert metadata["event_id"] == "evt123"
    assert metadata["calendar_id"] == "cal456"
    assert metadata["summary"] == "Weekly Sync"
    assert metadata["start"] == "2026-03-15T14:00:00Z"
    assert metadata["end"] == "2026-03-15T15:00:00Z"
    assert metadata["recurring_event_id"] == "rec789"
    assert metadata["meet_code"] == "abc-defg-hij"
    assert len(metadata["artifacts"]) == 3
    assert metadata["api_responses"]["calendar"]["id"] == "evt123"
    assert "conferenceRecords" in metadata["api_responses"]["meet"]


def test_build_meeting_metadata_excludes_none():
    """Test that None values are excluded from artifact dicts."""
    event = CalendarEvent(
        event_id="evt1",
        calendar_id="cal1",
        summary="Test",
        start="2026-03-15T10:00:00Z",
        end="2026-03-15T11:00:00Z",
    )
    artifacts = [
        Artifact(
            type="transcript",
            title="Transcript",
            source_url="https://example.com/file",
            drive_file_id=None,  # Should be excluded
            local_file=None,  # Should be excluded
            mime_type="text/plain",
            source=None,  # Should be excluded
            note=None,  # Should be excluded
        )
    ]
    meeting = MeetingRecord(event=event, artifacts=artifacts)

    metadata = build_meeting_metadata(meeting)

    artifact = metadata["artifacts"][0]
    assert "type" in artifact
    assert "title" in artifact
    assert "source_url" in artifact
    assert "mime_type" in artifact
    assert "drive_file_id" not in artifact
    assert "local_file" not in artifact
    assert "source" not in artifact
    assert "note" not in artifact


def test_metadata_filename(sample_meeting):
    """Test metadata filename generation."""
    filename = metadata_filename(sample_meeting)

    assert filename == "2026-03-15_weekly-sync.meta.json"


def test_metadata_filename_slugifies_title():
    """Test that metadata filename slugifies the meeting title."""
    event = CalendarEvent(
        event_id="evt1",
        calendar_id="cal1",
        summary="Q1 Planning: Strategy & Goals!",
        start="2026-03-20T09:00:00Z",
        end="2026-03-20T10:00:00Z",
    )
    meeting = MeetingRecord(event=event)

    filename = metadata_filename(meeting)

    assert filename == "2026-03-20_q1-planning-strategy-goals.meta.json"


def test_build_index_entry(sample_meeting):
    """Test building index entry from metadata."""
    metadata = build_meeting_metadata(sample_meeting)
    filename = "2026-03-15_weekly-sync.meta.json"

    entry = build_index_entry(metadata, filename)

    assert entry["date"] == "2026-03-15"
    assert entry["summary"] == "Weekly Sync"
    assert entry["event_id"] == "evt123"
    assert entry["metadata_file"] == "2026-03-15_weekly-sync.meta.json"
    assert len(entry["downloaded_files"]) == 2
    assert "2026-03-15_weekly-sync_transcript.txt" in entry["downloaded_files"]
    assert "2026-03-15_weekly-sync_slides.pdf" in entry["downloaded_files"]


def test_build_index_entry_no_downloaded_files():
    """Test index entry with no downloaded files."""
    metadata = {
        "event_id": "evt1",
        "summary": "Test Meeting",
        "start": "2026-03-15T10:00:00Z",
        "artifacts": [
            {
                "type": "recording",
                "title": "Recording",
                "source_url": "https://example.com",
            }
        ],
    }

    entry = build_index_entry(metadata, "test.meta.json")

    assert entry["downloaded_files"] == []


def test_write_metadata(tmp_path):
    """Test writing metadata to disk."""
    metadata = {
        "event_id": "evt123",
        "summary": "Test Meeting",
        "start": "2026-03-15T10:00:00Z",
    }
    filename = "test.meta.json"

    written_path = write_metadata(metadata, tmp_path, filename)

    assert written_path == tmp_path / filename
    assert written_path.exists()

    with open(written_path) as f:
        loaded = json.load(f)

    assert loaded == metadata


def test_write_metadata_creates_directory(tmp_path):
    """Test that write_metadata creates output directory if missing."""
    output_dir = tmp_path / "nested" / "path"
    metadata = {"event_id": "evt1"}
    filename = "test.meta.json"

    written_path = write_metadata(metadata, output_dir, filename)

    assert written_path.exists()
    assert output_dir.exists()


def test_build_and_write_index(tmp_path, sample_meeting):
    """Test building and writing the index from sidecar files."""
    # Write a few metadata files
    metadata1 = build_meeting_metadata(sample_meeting)
    filename1 = metadata_filename(sample_meeting)
    write_metadata(metadata1, tmp_path, filename1)

    # Create another meeting for different date
    event2 = CalendarEvent(
        event_id="evt456",
        calendar_id="cal456",
        summary="Another Meeting",
        start="2026-03-10T14:00:00Z",
        end="2026-03-10T15:00:00Z",
    )
    meeting2 = MeetingRecord(event=event2)
    metadata2 = build_meeting_metadata(meeting2)
    filename2 = metadata_filename(meeting2)
    write_metadata(metadata2, tmp_path, filename2)

    # Build index
    index_path = build_and_write_index(tmp_path)

    assert index_path == tmp_path / "index.json"
    assert index_path.exists()

    with open(index_path) as f:
        index = json.load(f)

    assert len(index) == 2
    # Should be sorted by date descending
    assert index[0]["date"] == "2026-03-15"
    assert index[1]["date"] == "2026-03-10"


def test_build_and_write_index_empty_directory(tmp_path):
    """Test building index in directory with no metadata files."""
    index_path = build_and_write_index(tmp_path)

    assert index_path.exists()

    with open(index_path) as f:
        index = json.load(f)

    assert index == []


def test_refresh_all_metadata(tmp_path):
    """Test refreshing metadata from api_responses."""
    # Create initial metadata with outdated top-level fields
    initial_metadata = {
        "event_id": "evt123",
        "calendar_id": "cal456",
        "summary": "Old Title",
        "start": "2026-03-15T14:00:00Z",
        "end": "2026-03-15T15:00:00Z",
        "recurring_event_id": "rec789",
        "meet_code": "abc-defg-hij",
        "artifacts": [],
        "api_responses": {
            "calendar": {
                "id": "evt123",
                "summary": "Updated Title",
                "start": {"dateTime": "2026-03-15T14:30:00Z"},
                "end": {"dateTime": "2026-03-15T15:30:00Z"},
                "recurringEventId": "rec999",
            },
            "meet": {},
        },
    }
    write_metadata(initial_metadata, tmp_path, "test.meta.json")

    # Refresh
    count = refresh_all_metadata(tmp_path)

    assert count == 1

    # Verify updated metadata
    with open(tmp_path / "test.meta.json") as f:
        updated = json.load(f)

    assert updated["summary"] == "Updated Title"
    assert updated["start"] == "2026-03-15T14:30:00Z"
    assert updated["end"] == "2026-03-15T15:30:00Z"
    assert updated["recurring_event_id"] == "rec999"
    # event_id and calendar_id should not change
    assert updated["event_id"] == "evt123"
    assert updated["calendar_id"] == "cal456"


def test_refresh_all_metadata_multiple_files(tmp_path):
    """Test refreshing multiple metadata files."""
    for i in range(3):
        metadata = {
            "event_id": f"evt{i}",
            "calendar_id": "cal1",
            "summary": "Old",
            "start": "2026-03-15T10:00:00Z",
            "end": "2026-03-15T11:00:00Z",
            "recurring_event_id": None,
            "meet_code": None,
            "artifacts": [],
            "api_responses": {
                "calendar": {
                    "id": f"evt{i}",
                    "summary": f"Updated {i}",
                    "start": {"dateTime": "2026-03-15T10:00:00Z"},
                    "end": {"dateTime": "2026-03-15T11:00:00Z"},
                },
                "meet": {},
            },
        }
        write_metadata(metadata, tmp_path, f"test{i}.meta.json")

    count = refresh_all_metadata(tmp_path)

    assert count == 3

    for i in range(3):
        with open(tmp_path / f"test{i}.meta.json") as f:
            updated = json.load(f)
        assert updated["summary"] == f"Updated {i}"
