# Generated By: Claude Code (Claude Opus 4.6)

"""CLI entry point for calendar-fetcher."""

import argparse
import json
import logging
import logging.handlers
import sys
import types
from datetime import date, timedelta
from pathlib import Path

from calendar_fetcher import calendar_client, config, exporter, metadata
from calendar_fetcher.gws import check_auth_scopes, run_gws

logger = logging.getLogger(__name__)


def _install_excepthook(*, logger: logging.Logger) -> None:
    def _hook(
        exc_type: type[BaseException],
        exc_value: BaseException,
        exc_tb: types.TracebackType | None,
    ) -> None:
        if issubclass(exc_type, KeyboardInterrupt):
            sys.__excepthook__(exc_type, exc_value, exc_tb)
            return
        logger.critical("uncaught exception", exc_info=(exc_type, exc_value, exc_tb))

    sys.excepthook = _hook


def create_parser() -> argparse.ArgumentParser:
    """Create and configure the argument parser."""
    parser = argparse.ArgumentParser(
        prog="calendar-fetcher",
        description="fetch and download artifacts from Google Calendar meetings",
    )
    subparsers = parser.add_subparsers(dest="subcommand", required=True)

    # fetch subcommand
    fetch_parser = subparsers.add_parser("fetch", help="fetch calendar events")
    fetch_parser.add_argument(
        "--calendar-id",
        default=config.DEFAULT_CALENDAR_ID,
        help="calendar identifier (default: primary)",
    )
    fetch_parser.add_argument(
        "--output-dir",
        default=config.DEFAULT_OUTPUT_DIR,
        help="output directory for artifacts (default: calendar-artifacts)",
    )
    fetch_parser.add_argument(
        "--lookback-days",
        type=int,
        default=config.DEFAULT_LOOKBACK_DAYS,
        help="number of days to look back (default: 7)",
    )
    fetch_parser.add_argument(
        "--date",
        help="process only a specific date (YYYY-MM-DD)",
    )
    fetch_parser.add_argument(
        "--drive-folder-id",
        help="upload to Drive folder",
    )
    fetch_parser.add_argument(
        "--debug",
        action="store_true",
        help="enable debug logging",
    )
    fetch_parser.add_argument(
        "--dryrun",
        action="store_true",
        help="log what would happen but don't download",
    )
    fetch_parser.add_argument(
        "-q",
        "--quiet",
        action="store_true",
        help="suppress info output",
    )
    fetch_parser.add_argument(
        "--log-file",
        help="write logs to file",
    )

    # refresh-metadata subcommand
    refresh_parser = subparsers.add_parser(
        "refresh-metadata",
        help="refresh metadata from api responses",
    )
    refresh_parser.add_argument(
        "--output-dir",
        default=config.DEFAULT_OUTPUT_DIR,
        help="output directory (default: calendar-artifacts)",
    )
    refresh_parser.add_argument(
        "--debug",
        action="store_true",
        help="enable debug logging",
    )
    refresh_parser.add_argument(
        "-q",
        "--quiet",
        action="store_true",
        help="suppress info output",
    )
    refresh_parser.add_argument(
        "--log-file",
        help="write logs to file",
    )

    # status subcommand
    status_parser = subparsers.add_parser("status", help="show artifact statistics")
    status_parser.add_argument(
        "--output-dir",
        default=config.DEFAULT_OUTPUT_DIR,
        help="output directory (default: calendar-artifacts)",
    )

    # list-calendars subcommand
    subparsers.add_parser("list-calendars", help="list available calendars")

    return parser


def configure_logging(
    *, debug: bool = False, quiet: bool = False, log_file: str | None = None
) -> None:
    """Configure logging based on CLI flags."""
    # Debug overrides quiet
    if debug:
        level = logging.DEBUG
    elif quiet:
        level = logging.WARNING
    else:
        level = logging.INFO

    # Configure format
    log_format = "%(asctime)s %(levelname)s %(name)s: %(message)s"

    # Configure handlers
    handler: logging.Handler
    if log_file:
        Path(log_file).parent.mkdir(parents=True, exist_ok=True)
        handler = logging.handlers.RotatingFileHandler(
            log_file,
            maxBytes=config.LOG_MAX_BYTES,
            backupCount=config.LOG_BACKUP_COUNT,
            encoding="utf-8",
        )
    else:
        handler = logging.StreamHandler(sys.stderr)

    handler.setFormatter(logging.Formatter(log_format))

    # Configure root logger
    root_logger = logging.getLogger()
    root_logger.setLevel(level)
    root_logger.addHandler(handler)

    # Install excepthook
    _install_excepthook(logger=logging.getLogger("calendar_fetcher"))


def handle_fetch(args: argparse.Namespace) -> None:
    """Handle the fetch subcommand."""
    # Check auth scopes
    check_auth_scopes(upload=bool(args.drive_folder_id))

    # Compute date range
    if args.date:
        time_min = f"{args.date}T00:00:00Z"
        time_max = f"{args.date}T23:59:59Z"
    else:
        today = date.today()
        lookback = today - timedelta(days=args.lookback_days)
        time_min = f"{lookback.isoformat()}T00:00:00Z"
        time_max = f"{today.isoformat()}T23:59:59Z"

    # Fetch events
    events = calendar_client.list_events(args.calendar_id, time_min, time_max)
    parsed_events = [calendar_client.parse_event(e, args.calendar_id) for e in events]

    # Process events
    output_dir = Path(args.output_dir)
    exporter.process_events(parsed_events, output_dir, dryrun=args.dryrun)

    # Build index
    if not args.dryrun:
        metadata.build_and_write_index(output_dir)

    # Print summary
    if not args.quiet:
        print(f"Processed {len(parsed_events)} events")


def handle_refresh_metadata(args: argparse.Namespace) -> None:
    """Handle the refresh-metadata subcommand."""
    output_dir = Path(args.output_dir)
    count = metadata.refresh_all_metadata(output_dir)
    metadata.build_and_write_index(output_dir)

    if not args.quiet:
        print(f"Refreshed {count} metadata files")


def handle_status(args: argparse.Namespace) -> None:
    """Handle the status subcommand."""
    output_dir = Path(args.output_dir)

    # Scan for metadata files
    meta_files = list(output_dir.glob("*.meta.json"))
    total_meetings = len(meta_files)

    # Count downloaded files
    total_files = 0
    for meta_file in meta_files:
        with open(meta_file) as f:
            data = json.load(f)
        total_files += sum(
            1
            for artifact in data.get("artifacts", [])
            if artifact.get("local_file") is not None
        )

    print(f"Total meetings: {total_meetings}")
    print(f"Total downloaded files: {total_files}")


def handle_list_calendars(args: argparse.Namespace) -> None:
    """Handle the list-calendars subcommand."""
    result = run_gws("calendar", "calendarList", "list")
    items = result.get("items", [])

    for item in items:
        calendar_id = item.get("id", "")
        summary = item.get("summary", "")
        print(f"{calendar_id}: {summary}")


def main() -> None:
    """Main entry point for the CLI."""
    parser = create_parser()
    args = parser.parse_args()

    # Configure logging if the subcommand supports it
    if hasattr(args, "debug"):
        configure_logging(
            debug=args.debug,
            quiet=args.quiet,
            log_file=args.log_file,
        )

    # Dispatch to subcommand handler
    if args.subcommand == "fetch":
        handle_fetch(args)
    elif args.subcommand == "refresh-metadata":
        handle_refresh_metadata(args)
    elif args.subcommand == "status":
        handle_status(args)
    elif args.subcommand == "list-calendars":
        handle_list_calendars(args)


if __name__ == "__main__":
    main()
