# Generated By: Claude Code (Claude Opus 4.6)

"""CLI entry point for calendar-fetcher."""

import argparse
import json
import logging
import logging.handlers
import sys
import types
from datetime import date, timedelta
from pathlib import Path

from calendar_fetcher import calendar_client, config, consolidator, exporter, metadata
from calendar_fetcher.gws import check_auth_scopes, run_gws

logger = logging.getLogger(__name__)


def _install_excepthook(*, logger: logging.Logger) -> None:
    def _hook(
        exc_type: type[BaseException],
        exc_value: BaseException,
        exc_tb: types.TracebackType | None,
    ) -> None:
        if issubclass(exc_type, KeyboardInterrupt):
            sys.__excepthook__(exc_type, exc_value, exc_tb)
            return
        logger.critical("uncaught exception", exc_info=(exc_type, exc_value, exc_tb))

    sys.excepthook = _hook


def _add_common_args(parser: argparse.ArgumentParser) -> None:
    """Add logging arguments shared by all subcommands."""
    parser.add_argument(
        "--debug",
        action="store_true",
        help="enable debug logging",
    )
    parser.add_argument(
        "-q",
        "--quiet",
        action="store_true",
        help="suppress info output",
    )
    parser.add_argument(
        "--log-file",
        help="write logs to file",
    )


def _add_output_dir_arg(parser: argparse.ArgumentParser) -> None:
    """Add --output-dir argument shared by most subcommands."""
    parser.add_argument(
        "--output-dir",
        default=config.DEFAULT_OUTPUT_DIR,
        help="output directory (default: calendar-artifacts)",
    )


def create_parser() -> argparse.ArgumentParser:
    """Create and configure the argument parser."""
    parser = argparse.ArgumentParser(
        prog="calendar-fetcher",
        description="fetch and download artifacts from Google Calendar meetings",
    )
    subparsers = parser.add_subparsers(dest="subcommand", required=True)

    # fetch subcommand
    fetch_parser = subparsers.add_parser(
        "fetch",
        help="fetch meeting artifacts for a date range",
        description="query Google Calendar for events and download attached "
        "documents, Meet transcripts, and recordings as portable files",
    )
    fetch_parser.add_argument(
        "--calendar-id",
        default=config.DEFAULT_CALENDAR_ID,
        help="calendar identifier (default: primary)",
    )
    _add_output_dir_arg(fetch_parser)
    date_group = fetch_parser.add_mutually_exclusive_group()
    date_group.add_argument(
        "--lookback-days",
        type=int,
        default=config.DEFAULT_LOOKBACK_DAYS,
        help="number of days to look back (default: 7)",
    )
    date_group.add_argument(
        "--date",
        help="process only a specific date (YYYY-MM-DD)",
    )
    fetch_parser.add_argument(
        "--drive-folder-id",
        help="upload to Drive folder",
    )
    fetch_parser.add_argument(
        "--dryrun",
        action="store_true",
        help="log what would happen but don't download",
    )
    _add_common_args(fetch_parser)

    # refresh-metadata subcommand
    refresh_parser = subparsers.add_parser(
        "refresh-metadata",
        help="regenerate metadata from stored api responses",
        description="re-extract top-level fields from the raw api responses "
        "stored in .meta.json files without calling any Google APIs",
    )
    _add_output_dir_arg(refresh_parser)
    _add_common_args(refresh_parser)

    # status subcommand
    status_parser = subparsers.add_parser(
        "status",
        help="show counts of meetings and downloaded artifacts",
        description="scan the output directory and report how many meetings "
        "have been processed and how many artifacts downloaded",
    )
    _add_output_dir_arg(status_parser)
    _add_common_args(status_parser)

    # list-calendars subcommand
    list_parser = subparsers.add_parser(
        "list-calendars",
        help="list available calendars",
        description="show all calendars accessible by the authenticated account",
    )
    _add_common_args(list_parser)

    # consolidate subcommand
    consolidate_parser = subparsers.add_parser(
        "consolidate",
        help="push fetched google docs into a single output document",
        description="consolidate fetched Google Docs into a single Google Doc "
        "with one tab per source document, including meeting metadata headers",
    )
    consolidate_parser.add_argument(
        "--output-doc-id",
        required=True,
        help="Google Doc ID to write tabs into",
    )
    _add_output_dir_arg(consolidate_parser)
    _add_common_args(consolidate_parser)

    return parser


def configure_logging(
    *, debug: bool = False, quiet: bool = False, log_file: str | None = None
) -> None:
    """Configure logging based on CLI flags."""
    # Debug overrides quiet
    if debug:
        level = logging.DEBUG
    elif quiet:
        level = logging.WARNING
    else:
        level = logging.INFO

    # Configure format
    log_format = "%(asctime)s %(levelname)s %(name)s: %(message)s"

    # Configure handlers
    handler: logging.Handler
    if log_file:
        Path(log_file).parent.mkdir(parents=True, exist_ok=True)
        handler = logging.handlers.RotatingFileHandler(
            log_file,
            maxBytes=config.LOG_MAX_BYTES,
            backupCount=config.LOG_BACKUP_COUNT,
            encoding="utf-8",
        )
    else:
        handler = logging.StreamHandler(sys.stderr)

    handler.setFormatter(logging.Formatter(log_format))

    # Configure root logger
    root_logger = logging.getLogger()
    root_logger.setLevel(level)
    root_logger.addHandler(handler)


def handle_fetch(args: argparse.Namespace) -> None:
    """Handle the fetch subcommand."""
    # Check auth scopes
    check_auth_scopes(upload=bool(args.drive_folder_id))

    # Compute date range
    output_dir = Path(args.output_dir)
    if args.date:
        time_min = f"{args.date}T00:00:00Z"
        time_max = f"{args.date}T23:59:59Z"
    else:
        today = date.today()
        anchor = metadata.read_fetch_state(output_dir) or today
        lookback = anchor - timedelta(days=args.lookback_days)
        time_min = f"{lookback.isoformat()}T00:00:00Z"
        time_max = f"{today.isoformat()}T23:59:59Z"

    # Fetch events
    events = calendar_client.list_events(args.calendar_id, time_min, time_max)
    parsed_events = [calendar_client.parse_event(e, args.calendar_id) for e in events]

    # Process events
    exporter.process_events(parsed_events, output_dir, dryrun=args.dryrun)

    # Build index and update state
    if not args.dryrun:
        metadata.build_and_write_index(output_dir)
        metadata.write_fetch_state(output_dir)

    # Print summary
    if not args.quiet:
        print(f"Processed {len(parsed_events)} events")


def handle_refresh_metadata(args: argparse.Namespace) -> None:
    """Handle the refresh-metadata subcommand."""
    output_dir = Path(args.output_dir)
    count = metadata.refresh_all_metadata(output_dir)
    extracted = exporter.apply_section_extraction_to_dir(output_dir)
    metadata.build_and_write_index(output_dir)

    if not args.quiet:
        parts = [f"Refreshed {count} metadata files"]
        if extracted:
            parts.append(f"{extracted} sections extracted")
        print(", ".join(parts))


def handle_status(args: argparse.Namespace) -> None:
    """Handle the status subcommand."""
    output_dir = Path(args.output_dir)

    # Scan for metadata files
    meta_files = list(output_dir.glob("*.meta.json"))
    total_meetings = len(meta_files)

    # Count downloaded files
    total_files = 0
    for meta_file in meta_files:
        try:
            with open(meta_file, encoding="utf-8") as f:
                data = json.load(f)
        except json.JSONDecodeError:
            logger.warning(f"Skipping malformed metadata file: {meta_file}")
            continue
        total_files += sum(
            1
            for artifact in data.get("artifacts", [])
            if artifact.get("local_file") is not None
        )

    print(f"Total meetings: {total_meetings}")
    print(f"Total downloaded files: {total_files}")


def handle_list_calendars(args: argparse.Namespace) -> None:
    """Handle the list-calendars subcommand."""
    result = run_gws("calendar", "calendarList", "list")
    items = result.get("items", [])

    if not items:
        print("No calendars found")
        return

    # Find max summary length for alignment
    max_summary = max(len(item.get("summary", "")) for item in items)
    col_width = min(max_summary, 40)

    for item in items:
        summary = item.get("summary", "")
        calendar_id = item.get("id", "")
        primary = " (primary)" if item.get("primary") else ""
        print(f"{summary:<{col_width}}  {calendar_id}{primary}")


def handle_consolidate(args: argparse.Namespace) -> None:
    """Handle the consolidate subcommand."""
    check_auth_scopes(consolidate=True)

    output_dir = Path(args.output_dir)
    if not output_dir.exists():
        print(f"Error: Output directory does not exist: {output_dir}", file=sys.stderr)
        raise SystemExit(config.EXIT_ERROR)

    created, updated, skipped = consolidator.consolidate(output_dir, args.output_doc_id)

    if not args.quiet:
        print(
            f"Consolidation complete: {created} created, "
            f"{updated} updated, {skipped} skipped"
        )


def main() -> int:
    """Main entry point for the CLI."""
    parser = create_parser()
    args = parser.parse_args()

    # Resolve paths: expand ~ and make absolute
    if hasattr(args, "output_dir"):
        args.output_dir = str(Path(args.output_dir).expanduser().resolve())
    if hasattr(args, "log_file") and args.log_file:
        args.log_file = str(Path(args.log_file).expanduser().resolve())

    # Install excepthook unconditionally
    _install_excepthook(logger=logging.getLogger("calendar_fetcher"))

    # Configure logging
    configure_logging(
        debug=args.debug,
        quiet=args.quiet,
        log_file=args.log_file,
    )

    # Dispatch to subcommand handler
    if args.subcommand == "fetch":
        handle_fetch(args)
    elif args.subcommand == "refresh-metadata":
        handle_refresh_metadata(args)
    elif args.subcommand == "status":
        handle_status(args)
    elif args.subcommand == "list-calendars":
        handle_list_calendars(args)
    elif args.subcommand == "consolidate":
        handle_consolidate(args)

    return config.EXIT_SUCCESS


if __name__ == "__main__":
    raise SystemExit(main())
