# Generated By: Claude Code (Claude Sonnet 4.5)

"""Simple file-based JSON cache with TTL."""

import json
import logging
import time
from pathlib import Path

logger = logging.getLogger(__name__)

DEFAULT_TTL_DAYS = 30


class FileCache:
    """JSON file-backed cache with per-entry TTL expiration."""

    def __init__(self, cache_path: Path, *, ttl_days: int = DEFAULT_TTL_DAYS):
        self._path = cache_path
        self._ttl_seconds = ttl_days * 86400
        self._data: dict = self._load()

    def get(self, key: str) -> dict | None:
        """Return cached value for key, or None if missing/expired."""
        entry = self._data.get(key)
        if entry is None:
            return None
        if time.time() - entry.get("timestamp", 0) > self._ttl_seconds:
            return None
        return entry.get("value")

    def set(self, key: str, value: dict) -> None:
        """Store value with current timestamp."""
        self._data[key] = {"value": value, "timestamp": time.time()}
        self._save()

    def _load(self) -> dict:
        """Load cache from disk."""
        if not self._path.exists():
            return {}
        try:
            return json.loads(self._path.read_text())
        except (json.JSONDecodeError, OSError) as e:
            logger.warning(f"Failed to load cache from {self._path}: {e}")
            return {}

    def _save(self) -> None:
        """Write cache to disk."""
        self._path.parent.mkdir(parents=True, exist_ok=True)
        self._path.write_text(json.dumps(self._data))
