# Generated By: Claude Code (Claude Opus 4.6)

"""Calendar client for querying events and extracting artifacts."""

import re
from calendar_fetcher.gws import run_gws
from calendar_fetcher.models import Artifact, CalendarEvent


def list_events(calendar_id: str, time_min: str, time_max: str) -> list[dict]:
    """
    Query Google Calendar events for a time range.

    Args:
        calendar_id: Calendar identifier (email address)
        time_min: RFC3339 timestamp for start of range
        time_max: RFC3339 timestamp for end of range

    Returns:
        List of event dicts from the API response
    """
    response = run_gws(
        "calendar",
        "events",
        "list",
        params={
            "calendarId": calendar_id,
            "timeMin": time_min,
            "timeMax": time_max,
            "singleEvents": True,
            "orderBy": "startTime",
        },
    )
    events = response.get("items", [])
    # Filter out working location events (all-day events like "Home", "Office")
    return [e for e in events if e.get("eventType") != "workingLocation"]


def extract_attachments(event: dict) -> list[Artifact]:
    """
    Extract attachments from a calendar event.

    Args:
        event: Calendar event dict from API

    Returns:
        List of Artifact objects for attached files
    """
    attachments = event.get("attachments", [])
    artifacts = []
    for attachment in attachments:
        file_id = attachment.get("fileId")
        if not file_id:
            continue  # skip attachments without file ID
        artifacts.append(
            Artifact(
                type="attachment",
                source="attached",
                drive_file_id=file_id,
                source_url=attachment.get("fileUrl", ""),
                mime_type=attachment.get("mimeType"),
                title=attachment.get("title", ""),
            )
        )
    return artifacts


def extract_description_links(event: dict) -> list[Artifact]:
    """
    Extract Google Workspace document links from event description.

    Matches URLs for Google Docs, Sheets, and Slides. Parses both plain URLs
    and HTML href attributes. Deduplicates by document ID.

    Args:
        event: Calendar event dict from API

    Returns:
        List of Artifact objects for document links
    """
    description = event.get("description", "")
    if not description:
        return []

    # Pattern to match Google Workspace document URLs
    # Captures: 1) doc type (document|spreadsheets|presentation) 2) file ID
    pattern = (
        r"https://docs\.google\.com/"
        r'(document|spreadsheets|presentation)/d/([A-Za-z0-9_-]+)(?:/[^\s"<]*)?'
    )

    seen_ids = set()
    artifacts = []

    for match in re.finditer(pattern, description):
        file_id = match.group(2)
        if file_id in seen_ids:
            continue
        seen_ids.add(file_id)

        artifacts.append(
            Artifact(
                type="attachment",
                source="description_link",
                drive_file_id=file_id,
                source_url=match.group(0),
                title="",  # No title available from link
            )
        )

    return artifacts


def extract_meet_code(event: dict) -> str | None:
    """
    Extract Google Meet conference code from event.

    Args:
        event: Calendar event dict from API

    Returns:
        Meet code string or None if no conference data
    """
    conference_data = event.get("conferenceData")
    if not conference_data:
        return None

    # Check conferenceId first
    if "conferenceId" in conference_data:
        return conference_data["conferenceId"]

    # Look for video entryPoint
    entry_points = conference_data.get("entryPoints", [])
    for entry in entry_points:
        if entry.get("entryPointType") == "video":
            # Try label first, then parse from URI
            if "label" in entry:
                return entry["label"]
            if "uri" in entry:
                # Extract code from https://meet.google.com/abc-defg-hij
                uri = entry["uri"]
                if "meet.google.com/" in uri:
                    return uri.split("meet.google.com/")[-1].split("?")[0]

    return None


def parse_event(event: dict, calendar_id: str) -> CalendarEvent:
    """
    Parse a calendar event dict into a CalendarEvent object.

    Combines all artifact extraction functions and maps event fields.

    Args:
        event: Calendar event dict from API
        calendar_id: Calendar identifier

    Returns:
        CalendarEvent with all fields populated
    """
    # Extract start/end times (handle all-day events)
    start_data = event.get("start", {})
    end_data = event.get("end", {})
    start = start_data.get("dateTime", start_data.get("date", ""))
    end = end_data.get("dateTime", end_data.get("date", ""))

    # Combine artifacts from attachments and description links
    attachments = extract_attachments(event)
    description_links = extract_description_links(event)
    all_attachments = attachments + description_links

    return CalendarEvent(
        event_id=event["id"],
        calendar_id=calendar_id,
        summary=event.get("summary", ""),
        start=start,
        end=end,
        description=event.get("description", ""),
        recurring_event_id=event.get("recurringEventId"),
        meet_code=extract_meet_code(event),
        attachments=all_attachments,
        api_response=event,
    )
