# Generated By: Claude Code (Claude Sonnet 4.5)

"""Paths, defaults, and constants for calendar-fetcher."""

DEFAULT_CALENDAR_ID = "primary"
DEFAULT_LOOKBACK_DAYS = 7
DEFAULT_OUTPUT_DIR = "calendar-artifacts"

EXIT_SUCCESS = 0
EXIT_ERROR = 1

LOG_MAX_BYTES = 2 * 1024 * 1024
LOG_BACKUP_COUNT = 1

STATE_FILENAME = "fetcher-state.json"

# Supported Google Workspace MIME types and their export formats.
EXPORT_MIME_MAP = {
    "application/vnd.google-apps.document": "md",
    "application/vnd.google-apps.spreadsheet": "csv",
    "application/vnd.google-apps.presentation": "pdf",
}
