# Generated By: Claude Code (Claude Opus 4.6)

"""Consolidate fetched Google Docs into a single output Google Doc with tabs."""

import json
import logging
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

from calendar_fetcher.gws import run_gws, run_gws_write

logger = logging.getLogger(__name__)

GOOGLE_DOC_MIME = "application/vnd.google-apps.document"


@dataclass
class DocInfo:
    """Info about a fetched Google Doc and its meeting context."""

    file_id: str
    local_path: Path
    local_mtime: float
    meeting_summary: str
    meeting_start: str
    recurring: bool
    attendees: list[dict] = field(default_factory=list)


def _scan_doc_artifacts(output_dir: Path) -> dict[str, DocInfo]:
    """Scan .meta.json files, return map of file_id -> DocInfo for Google Docs."""
    docs: dict[str, DocInfo] = {}

    for meta_file in sorted(output_dir.glob("*.meta.json")):
        try:
            with open(meta_file, encoding="utf-8") as f:
                meta = json.load(f)
        except (json.JSONDecodeError, OSError):
            logger.warning(f"Skipping malformed metadata file: {meta_file}")
            continue

        summary = meta.get("summary", "")
        start = meta.get("start", "")
        recurring = meta.get("recurring_event_id") is not None
        attendees = (
            meta.get("api_responses", {}).get("calendar", {}).get("attendees", [])
        )

        for artifact in meta.get("artifacts", []):
            if artifact.get("mime_type") != GOOGLE_DOC_MIME:
                continue
            local_file = artifact.get("local_file")
            if not local_file:
                continue
            file_id = artifact.get("drive_file_id")
            if not file_id:
                continue

            local_path = Path(local_file)
            if not local_path.exists():
                logger.debug(f"Local file missing, skipping: {local_file}")
                continue

            local_mtime = local_path.stat().st_mtime

            if file_id in docs and docs[file_id].meeting_start >= start:
                continue

            docs[file_id] = DocInfo(
                file_id=file_id,
                local_path=local_path,
                local_mtime=local_mtime,
                meeting_summary=summary,
                meeting_start=start,
                recurring=recurring,
                attendees=attendees,
            )

    return docs


def _format_meeting_date(iso_str: str) -> str:
    """Format ISO timestamp as 'YYYY-MM-DD HH:MM TZ' for display."""
    try:
        dt = datetime.fromisoformat(iso_str)
        if dt.tzinfo is not None:
            tz_name = dt.strftime("%Z") or dt.strftime("%z")
        else:
            tz_name = "UTC"
        return f"{dt.strftime('%Y-%m-%d %H:%M')} {tz_name}"
    except (ValueError, TypeError):
        return iso_str


def _build_metadata_header(info: DocInfo) -> str:
    """Build curated metadata header string from DocInfo."""
    parts = []
    parts.append(f"Meeting: {info.meeting_summary}")
    parts.append(f"Date: {_format_meeting_date(info.meeting_start)}")
    parts.append(f"Recurring: {'Yes' if info.recurring else 'No'}")

    attendee_strs = []
    for att in info.attendees:
        name = att.get("displayName") or att.get("email", "unknown")
        status = att.get("responseStatus", "unknown")
        if status == "declined":
            attendee_strs.append(f"~~{name}~~ ({status})")
        else:
            attendee_strs.append(f"{name} ({status})")
    parts.append(f"Attendees: {', '.join(attendee_strs)}")

    parts.append(f"Source: https://docs.google.com/document/d/{info.file_id}/edit")
    parts.append("---")

    return "\n".join(parts) + "\n"


# Matches markdown reference-style image definitions with base64 data:
#   [imageN]: <data:image/png;base64,...>
_BASE64_REF_RE = re.compile(r"^\[([^\]]+)\]:\s*<data:image/[^>]+>\s*$", re.MULTILINE)
# Matches inline markdown images with base64 data:
#   ![alt](data:image/png;base64,...)
_BASE64_INLINE_RE = re.compile(r"!\[[^\]]*\]\(data:image/[^)]+\)")


def _strip_embedded_images(content: str) -> str:
    """Remove base64-encoded images from markdown content.

    The Docs insertText API is plain text only and cannot render images.
    Base64 image data is just noise that bloats the document.
    """
    original_len = len(content)

    # Replace reference definitions: [imageN]: <data:image/...>
    content = _BASE64_REF_RE.sub(r"[\1]: [image removed]", content)

    # Replace inline images: ![alt](data:image/...)
    content = _BASE64_INLINE_RE.sub("[image removed]", content)

    stripped = original_len - len(content)
    if stripped > 0:
        logger.info(f"Stripped {stripped:,} bytes of embedded image data")

    return content


def _read_consolidate_state(output_dir: Path) -> dict:
    """Read consolidate state from fetcher-state.json."""
    from calendar_fetcher.state import read_state_file

    return read_state_file(output_dir).get("consolidate_state", {})


def _write_consolidate_state(output_dir: Path, state: dict) -> None:
    """Write consolidate state to fetcher-state.json, preserving other keys."""
    from calendar_fetcher.state import write_state_key

    write_state_key(output_dir, "consolidate_state", state)


def _read_existing_tabs(output_doc_id: str) -> dict[str, str]:
    """Read output doc, return map of tab_title -> tab_id."""
    response = run_gws(
        "docs",
        "documents",
        "get",
        params={"documentId": output_doc_id, "includeTabsContent": True},
    )
    tabs = response.get("tabs", [])
    return {
        tab["tabProperties"]["title"]: tab["tabProperties"]["tabId"]
        for tab in tabs
        if "tabProperties" in tab
    }


def _create_tab(output_doc_id: str, title: str, content: str) -> str:
    """Create a new tab and insert content. Returns tab_id.

    Uses two separate batchUpdate calls because insertText needs
    the tabId returned from addDocumentTab.
    """
    create_response = run_gws_write(
        "docs",
        "documents",
        "batchUpdate",
        params={"documentId": output_doc_id},
        json_body={
            "requests": [
                {"addDocumentTab": {"tabProperties": {"title": title}}},
            ]
        },
    )
    tab_id = create_response["replies"][0]["addDocumentTab"]["tabProperties"]["tabId"]

    _insert_text(output_doc_id, tab_id, content)

    return tab_id


# Linux MAX_ARG_STRLEN limits each argv string to 128KB (32 pages).
# The --json value is one argv string, so text content must leave room
# for JSON wrapping overhead (~200 bytes).
_MAX_TEXT_BYTES = 100 * 1024


def _insert_text(output_doc_id: str, tab_id: str, content: str) -> None:
    """Insert text into a tab, chunking if content exceeds ARG_MAX."""
    encoded_size = len(content.encode("utf-8"))
    if encoded_size <= _MAX_TEXT_BYTES:
        run_gws_write(
            "docs",
            "documents",
            "batchUpdate",
            params={"documentId": output_doc_id},
            json_body={
                "requests": [
                    {
                        "insertText": {
                            "endOfSegmentLocation": {"tabId": tab_id},
                            "text": content,
                        }
                    },
                ]
            },
        )
        return

    # Chunk content and insert sequentially.
    # Each chunk appends to end-of-segment so order is preserved.
    offset = 0
    while offset < len(content):
        # Find a chunk boundary at _MAX_TEXT_BYTES worth of UTF-8.
        # Slice by characters, check encoded size.
        end = min(offset + _MAX_TEXT_BYTES, len(content))
        chunk = content[offset:end]
        while len(chunk.encode("utf-8")) > _MAX_TEXT_BYTES and end > offset + 1:
            end -= 1024
            chunk = content[offset:end]

        logger.debug(
            f"Inserting chunk {offset}-{end} " f"({len(chunk.encode('utf-8'))} bytes)"
        )
        run_gws_write(
            "docs",
            "documents",
            "batchUpdate",
            params={"documentId": output_doc_id},
            json_body={
                "requests": [
                    {
                        "insertText": {
                            "endOfSegmentLocation": {"tabId": tab_id},
                            "text": chunk,
                        }
                    },
                ]
            },
        )
        offset = end


def _delete_tab(output_doc_id: str, tab_id: str) -> None:
    """Delete a tab from the output doc."""
    run_gws_write(
        "docs",
        "documents",
        "batchUpdate",
        params={"documentId": output_doc_id},
        json_body={
            "requests": [
                {"deleteTab": {"tabId": tab_id}},
            ]
        },
    )


def consolidate(output_dir: Path, output_doc_id: str) -> tuple[int, int, int]:
    """Consolidate fetched Google Docs into a single output document.

    Returns (created, updated, skipped) counts.
    """
    doc_map = _scan_doc_artifacts(output_dir)
    if not doc_map:
        logger.info("No Google Doc artifacts found to consolidate")
        return (0, 0, 0)

    logger.info(f"Found {len(doc_map)} unique Google Docs to consolidate")

    existing_tabs = _read_existing_tabs(output_doc_id)

    state = _read_consolidate_state(output_dir)
    tab_states = state.get("tabs", {})

    created = 0
    updated = 0
    skipped = 0

    for file_id, info in sorted(doc_map.items()):
        tab_exists = file_id in existing_tabs
        tab_state = tab_states.get(file_id, {})
        saved_mtime = tab_state.get("source_mtime")

        local_newer = saved_mtime is None or float(saved_mtime) < info.local_mtime

        if tab_exists and not local_newer:
            logger.debug(f"Skipping unchanged doc: {file_id}")
            skipped += 1
            continue

        header = _build_metadata_header(info)
        content = info.local_path.read_text(encoding="utf-8")
        content = _strip_embedded_images(content)
        full_content = header + "\n" + content

        if tab_exists:
            logger.info(f"Updating tab for changed doc: {file_id}")
            _delete_tab(output_doc_id, existing_tabs[file_id])
            tab_id = _create_tab(output_doc_id, file_id, full_content)
            updated += 1
        else:
            logger.info(f"Creating tab for new doc: {file_id}")
            tab_id = _create_tab(output_doc_id, file_id, full_content)
            created += 1

        tab_states[file_id] = {
            "tab_id": tab_id,
            "source_mtime": str(info.local_mtime),
        }

    new_state = {
        "last_run": datetime.now(timezone.utc).isoformat(),
        "output_doc_id": output_doc_id,
        "tabs": tab_states,
    }
    _write_consolidate_state(output_dir, new_state)

    logger.info(
        f"Consolidation complete: "
        f"{created} created, {updated} updated, {skipped} skipped"
    )

    return (created, updated, skipped)
