# Generated By: Claude Code (Claude Opus 4.6)

"""Reusable date parsing utilities for calendar-fetcher."""

import re
from datetime import date, datetime

_STRIKETHROUGH_RE = re.compile(r"~~.*?~~")
_MD_INLINE_RE = re.compile(r"[*_`]")

_DATE_PATTERNS: list[tuple[re.Pattern[str], list[str]]] = [
    (
        re.compile(r"[A-Z][a-z]+\.?\s+\d{1,2},\s+\d{4}"),
        ["%B %d, %Y", "%b %d, %Y", "%b. %d, %Y"],
    ),
    (
        re.compile(r"\d{4}-\d{2}-\d{2}"),
        ["%Y-%m-%d"],
    ),
]


def strip_markdown_formatting(text: str) -> str:
    """Remove markdown inline formatting from text.

    Strips ~~strikethrough~~ blocks entirely, then removes *, _, and
    backtick characters. Useful for cleaning heading text before date parsing.
    """
    text = _STRIKETHROUGH_RE.sub("", text)
    text = _MD_INLINE_RE.sub("", text)
    return text.strip()


def parse_human_date(text: str) -> date | None:
    """Parse a human-readable date from text that may contain surrounding content.

    Supported formats:
        - "April 30, 2026" (full month name)
        - "Apr 30, 2026" (abbreviated month)
        - "2026-04-30" (ISO)

    Returns the parsed date, or None if no recognizable date is found.
    """
    for pattern, formats in _DATE_PATTERNS:
        match = pattern.search(text)
        if match:
            date_str = match.group(0)
            for fmt in formats:
                try:
                    return datetime.strptime(date_str, fmt).date()
                except ValueError:
                    continue
    return None
