# Generated By: Claude Code (Claude Opus 4.6)

"""Drive API client for downloading and exporting Google Workspace files."""

import logging
from pathlib import Path

from calendar_fetcher.gws import GWSError, run_gws

logger = logging.getLogger(__name__)


def get_file_metadata(file_id: str) -> dict | None:
    """Get metadata for a Drive file.

    Args:
        file_id: The Drive file ID

    Returns:
        Metadata dict with id, name, mimeType fields, or None on error
    """
    try:
        return run_gws(
            "drive",
            "files",
            "get",
            params={"fileId": file_id, "fields": "id,name,mimeType"},
        )
    except GWSError as e:
        logger.warning(f"Failed to access file {file_id}: {e}")
        return None


def _export_file(
    file_id: str,
    output_path: str,
    mime_type: str,
    *,
    description: str = "file",
) -> str | None:
    """Export a Google Workspace file via Drive API.

    Args:
        file_id: The Drive file ID
        output_path: Where to write the exported file
        mime_type: MIME type to export as
        description: Human-readable description for error logging

    Returns:
        Output path on success, None on error
    """
    try:
        run_gws(
            "drive",
            "files",
            "export",
            params={"fileId": file_id, "mimeType": mime_type},
            output_file=output_path,
        )
        return output_path
    except GWSError as e:
        logger.warning(f"Failed to export {description} {file_id}: {e}")
        return None


def export_doc_as_markdown(file_id: str, output_path: str) -> str | None:
    """Export a Google Doc as markdown via Drive API.

    Args:
        file_id: The document ID
        output_path: Where to write the markdown file

    Returns:
        Output path on success, None on error
    """
    return _export_file(
        file_id, output_path, "text/markdown", description="doc as markdown"
    )


def fetch_sheet_tabs(file_id: str) -> list[dict]:
    """Get list of sheet tabs from a Google Sheets file.

    Args:
        file_id: The spreadsheet ID

    Returns:
        List of tab property dicts, or empty list on error
    """
    try:
        response = run_gws(
            "sheets",
            "spreadsheets",
            "get",
            params={"spreadsheetId": file_id, "fields": "sheets.properties"},
        )
        sheets = response.get("sheets", [])
        return [sheet["properties"] for sheet in sheets]
    except GWSError as e:
        logger.warning(f"Failed to fetch sheet tabs for {file_id}: {e}")
        return []


def fetch_sheet_tab_data(file_id: str, tab_name: str, output_path: str) -> str | None:
    """Export a single sheet tab as CSV.

    Args:
        file_id: The spreadsheet ID
        tab_name: The tab name (currently unused, exports entire sheet as CSV)
        output_path: Where to write the CSV file

    Returns:
        Output path on success, None on error
    """
    return _export_file(
        file_id, output_path, "text/csv", description=f"sheet tab {tab_name}"
    )


def export_slides_as_pdf(file_id: str, output_path: str) -> str | None:
    """Export Google Slides as PDF.

    Args:
        file_id: The presentation ID
        output_path: Where to write the PDF file

    Returns:
        Output path on success, None on error
    """
    return _export_file(
        file_id, output_path, "application/pdf", description="slides as PDF"
    )


def list_folder_files(folder_id: str) -> set[str]:
    """List files in a Google Drive folder.

    Args:
        folder_id: The folder ID

    Returns:
        Set of filenames in the folder, or empty set on error
    """
    try:
        response = run_gws(
            "drive",
            "files",
            "list",
            params={
                "q": f'"{folder_id}" in parents',
                "fields": "files(name)",
                "pageSize": 1000,
            },
        )
        files = response.get("files", [])
        return {file["name"] for file in files}
    except GWSError as e:
        logger.warning(f"Failed to list files in folder {folder_id}: {e}")
        return set()


def upload_file(local_path: Path, folder_id: str) -> str | None:
    """Upload a file to a Google Drive folder.

    Args:
        local_path: Path to local file to upload
        folder_id: The destination folder ID

    Returns:
        Drive file ID on success, None on failure

    Note:
        This is a placeholder implementation. The exact gws CLI syntax
        for file upload needs to be determined. See Task 15 for investigation.
        TODO: Implement actual upload once gws CLI syntax is confirmed.
    """
    logger.warning(
        f"upload_file not yet implemented: would upload {local_path} to {folder_id}"
    )
    return None


def upload_new_files(output_dir: Path, folder_id: str, *, dryrun: bool = False) -> int:
    """Upload new files from output directory to Drive folder.

    Args:
        output_dir: Local directory containing files to upload
        folder_id: The destination folder ID
        dryrun: If True, log what would be uploaded but don't upload

    Returns:
        Count of files uploaded (0 in dryrun mode)
    """
    # Get existing files in the folder
    existing_files = list_folder_files(folder_id)

    # Find files to upload
    files_to_upload = []
    for file_path in output_dir.rglob("*"):
        if file_path.is_file():
            if file_path.name not in existing_files:
                files_to_upload.append(file_path)

    # Handle dryrun mode
    if dryrun:
        for file_path in files_to_upload:
            logger.info(f"[dryrun] Would upload: {file_path.name}")
        return 0

    # Upload new files
    upload_count = 0
    for file_path in files_to_upload:
        result = upload_file(file_path, folder_id)
        if result is not None:
            upload_count += 1
            logger.info(f"Uploaded {file_path.name} to folder {folder_id}")
        else:
            logger.warning(f"Failed to upload {file_path.name}")

    return upload_count
