# Generated By: Claude Code (Claude Opus 4.6)

"""Exporter orchestration for calendar-fetcher."""

import json
import logging
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path

from calendar_fetcher import drive_client, meet_client, metadata, section_extractor
from calendar_fetcher.config import EXPORT_MIME_MAP, MAX_WORKERS
from calendar_fetcher.gws import GWSError
from calendar_fetcher.models import Artifact, CalendarEvent, MeetingRecord
from calendar_fetcher.naming import build_filename, extract_date

logger = logging.getLogger(__name__)


def _is_local_fresh(output_path: Path, file_id: str) -> bool:
    """Check if local file exists and is at least as new as the Drive version."""
    if not output_path.exists():
        return False
    file_metadata = drive_client.get_file_metadata(file_id)
    if not file_metadata or "modifiedTime" not in file_metadata:
        return True  # can't determine, keep local
    drive_mtime = datetime.fromisoformat(file_metadata["modifiedTime"])
    if drive_mtime.tzinfo is None:
        drive_mtime = drive_mtime.replace(tzinfo=timezone.utc)
    local_mtime = datetime.fromtimestamp(output_path.stat().st_mtime, tz=timezone.utc)
    if local_mtime >= drive_mtime:
        return True
    logger.info(f"Re-downloading updated file: {output_path.name}")
    return False


def _apply_section_extraction(output_path: Path, event_date: str) -> None:
    """Extract the date-specific section from an exported meeting notes file.

    Reads the file, attempts to detect date-heading structure and extract the
    section matching event_date. Overwrites only if extraction produced
    different (shorter) content. No-op if no date structure is detected or
    the target date is not found.
    """
    try:
        content = output_path.read_text(encoding="utf-8")
        extracted = section_extractor.extract_section(content, event_date)
        if extracted is not None and extracted != content:
            output_path.write_text(extracted, encoding="utf-8")
            logger.info(f"Extracted section for {event_date} from {output_path.name}")
    except Exception:
        logger.warning(
            f"Section extraction failed for {output_path.name}, keeping full content",
            exc_info=True,
        )


def process_artifact(
    artifact: Artifact,
    output_dir: Path,
    date: str,
    meeting_title: str,
    *,
    dryrun: bool = False,
) -> Artifact:
    """Process a single artifact: download/export to output directory.

    Args:
        artifact: The artifact to process
        output_dir: Directory to write files to
        date: Date string (YYYY-MM-DD) for filename
        meeting_title: Meeting title for filename
        dryrun: If True, log what would happen but don't download

    Returns:
        The artifact with local_file or note fields updated
    """
    # Check if MIME type is supported
    if artifact.mime_type not in EXPORT_MIME_MAP:
        artifact.note = f"Skipped: unsupported type ({artifact.mime_type or 'unknown'})"
        logger.debug(
            f"Skipping {artifact.title or artifact.type}: "
            f"unsupported MIME type {artifact.mime_type or 'unknown'}"
        )
        return artifact

    ext = EXPORT_MIME_MAP[artifact.mime_type]

    # Build base filename
    base_filename = build_filename(
        date=date,
        meeting_title=meeting_title,
        document_title=artifact.title,
        document_id=artifact.drive_file_id or "unknown",
        ext=ext,
    )

    if dryrun:
        print(f"Would download: {artifact.title} → {base_filename}")
        return artifact

    if not artifact.drive_file_id:
        artifact.note = "No drive file ID"
        logger.warning(f"Skipping {artifact.title}: no drive file ID")
        return artifact

    file_id = artifact.drive_file_id

    try:
        if artifact.mime_type == "application/vnd.google-apps.document":
            # Google Docs: export directly as markdown
            output_path = output_dir / base_filename
            if _is_local_fresh(output_path, file_id):
                logger.debug(f"Skipping fresh file: {output_path}")
                artifact.local_file = str(output_path)
            else:
                result = drive_client.export_doc_as_markdown(file_id, str(output_path))
                if result:
                    logger.debug(f"Exported doc to {output_path}")
                    artifact.local_file = str(output_path)
                else:
                    artifact.note = "Failed to export doc as markdown"
            if artifact.local_file:
                _apply_section_extraction(Path(artifact.local_file), date)

        elif artifact.mime_type == "application/vnd.google-apps.spreadsheet":
            # Google Sheets: export each tab as CSV
            first_file = _process_google_sheet(
                artifact, file_id, output_dir, date, meeting_title, ext
            )
            artifact.local_file = first_file

        elif artifact.mime_type == "application/vnd.google-apps.presentation":
            # Google Slides: export as PDF
            output_path = output_dir / base_filename
            if _is_local_fresh(output_path, file_id):
                logger.debug(f"Skipping fresh file: {output_path}")
                artifact.local_file = str(output_path)
            else:
                result = drive_client.export_slides_as_pdf(file_id, str(output_path))
                if result:
                    logger.debug(f"Exported slides to {output_path}")
                    artifact.local_file = str(output_path)
                else:
                    artifact.note = "Failed to export slides"

    except GWSError as e:
        artifact.note = str(e)
        logger.warning(f"Failed to process {artifact.title}: {e}")

    return artifact


def _process_google_sheet(
    artifact: Artifact,
    file_id: str,
    output_dir: Path,
    date: str,
    meeting_title: str,
    ext: str,
) -> str | None:
    """Process a Google Sheet: export each tab as CSV.

    Returns the path to the first file written, or None on error.
    """
    tabs = drive_client.fetch_sheet_tabs(file_id)
    if not tabs:
        artifact.note = "No tabs found in sheet"
        return None

    first_file = None
    for tab in tabs:
        tab_name = tab["title"]
        filename = build_filename(
            date=date,
            meeting_title=meeting_title,
            document_title=artifact.title,
            document_id=file_id,
            ext=ext,
            tab_name=tab_name,
        )
        output_path = output_dir / filename

        if _is_local_fresh(output_path, file_id):
            logger.debug(f"Skipping fresh file: {output_path}")
        else:
            result = drive_client.fetch_sheet_tab_data(
                file_id, tab_name, str(output_path)
            )
            if result:
                logger.debug(f"Exported sheet tab to {output_path}")
            else:
                logger.warning(f"Failed to export tab {tab_name}")
                continue

        if first_file is None:
            first_file = str(output_path)

    return first_file


def process_event(
    event: CalendarEvent, output_dir: Path, *, dryrun: bool = False
) -> MeetingRecord:
    """Process a single calendar event: download artifacts and write metadata.

    Args:
        event: The calendar event to process
        output_dir: Directory to write files to
        dryrun: If True, log what would happen but don't download

    Returns:
        MeetingRecord with all artifacts and metadata
    """
    logger.info(f"Processing event: {event.summary}")

    # Extract date from start time
    date = extract_date(event.start)

    # Collect all artifacts
    all_artifacts = list(event.attachments)

    # Fetch Meet data if available
    meet_api_response: dict[str, object] = {}
    if event.meet_code:
        meet_artifacts, meet_api_response = meet_client.get_all_meet_data(
            event.meet_code
        )
        all_artifacts.extend(meet_artifacts)

    # Process each artifact
    for artifact in all_artifacts:
        process_artifact(artifact, output_dir, date, event.summary, dryrun=dryrun)

    # Build meeting record
    record = MeetingRecord(
        event=event,
        artifacts=all_artifacts,
        meet_api_response=meet_api_response,
    )

    # Write metadata
    if not dryrun:
        metadata_dict = metadata.build_meeting_metadata(record)
        filename = metadata.metadata_filename(record)
        metadata.write_metadata(metadata_dict, output_dir, filename)

    return record


def process_events(
    events: list[CalendarEvent], output_dir: Path, *, dryrun: bool = False
) -> list[MeetingRecord]:
    """Process all events: download artifacts and write metadata.

    Args:
        events: List of calendar events to process
        output_dir: Directory to write files to
        dryrun: If True, log what would happen but don't download

    Returns:
        List of MeetingRecords
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    records = []

    failed_events = 0
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as pool:
        futures = {
            pool.submit(process_event, event, output_dir, dryrun=dryrun): event
            for event in events
        }
        for future in as_completed(futures):
            try:
                records.append(future.result())
            except Exception:
                failed_events += 1
                event = futures[future]
                logger.exception(f"Unexpected error processing event: {event.summary}")

    # Print summary
    total_artifacts = sum(len(r.artifacts) for r in records)
    downloaded = sum(
        1 for r in records for a in r.artifacts if a.local_file is not None
    )
    skipped = sum(
        1
        for r in records
        for a in r.artifacts
        if a.note is not None and a.note.startswith("Skipped:")
    )
    failed_artifacts = sum(
        1
        for r in records
        for a in r.artifacts
        if a.note is not None and not a.note.startswith("Skipped:")
    )

    parts = [
        f"Processed {len(events)} events, {total_artifacts} artifacts",
        f"({downloaded} downloaded",
    ]
    if skipped:
        parts.append(f"{skipped} skipped")
    if failed_artifacts:
        parts.append(f"{failed_artifacts} failed")
    if failed_events:
        parts.append(f"{failed_events} events errored")
    logger.info(", ".join(parts) + ")")

    return records


def apply_section_extraction_to_dir(output_dir: Path) -> int:
    """Apply section extraction to all Google Doc markdown files in a directory.

    Reads .meta.json files to find artifacts with local_file paths, extracts the
    event date from the metadata, and applies section extraction to each file.

    Returns count of files where extraction was applied.
    """
    count = 0
    for meta_file in sorted(output_dir.glob("*.meta.json")):
        try:
            with open(meta_file, encoding="utf-8") as f:
                meta = json.load(f)
        except (json.JSONDecodeError, OSError):
            logger.warning(f"Skipping malformed metadata: {meta_file}")
            continue

        event_date = extract_date(meta.get("start", ""))
        if not event_date:
            continue

        for artifact in meta.get("artifacts", []):
            if not isinstance(artifact, dict):
                continue
            local_file = artifact.get("local_file")
            if not local_file:
                continue
            path = Path(local_file)
            if not path.exists() or not path.suffix == ".md":
                continue

            before = path.read_text(encoding="utf-8")
            _apply_section_extraction(path, event_date)
            if path.read_text(encoding="utf-8") != before:
                count += 1

    return count
