# Generated By: Claude Code (Claude Opus 4.6)

"""Exporter orchestration for calendar-fetcher."""

import logging
from pathlib import Path

from calendar_fetcher import drive_client, meet_client, metadata
from calendar_fetcher.config import EXPORT_MIME_MAP
from calendar_fetcher.gws import GWSError
from calendar_fetcher.models import Artifact, CalendarEvent, MeetingRecord
from calendar_fetcher.naming import build_filename, extract_date

logger = logging.getLogger(__name__)


def process_artifact(
    artifact: Artifact,
    output_dir: Path,
    date: str,
    meeting_title: str,
    *,
    dryrun: bool = False,
) -> Artifact:
    """Process a single artifact: download/export to output directory.

    Args:
        artifact: The artifact to process
        output_dir: Directory to write files to
        date: Date string (YYYY-MM-DD) for filename
        meeting_title: Meeting title for filename
        dryrun: If True, log what would happen but don't download

    Returns:
        The artifact with local_file or note fields updated
    """
    # Check if MIME type is supported
    if artifact.mime_type not in EXPORT_MIME_MAP:
        artifact.note = f"Skipped: unsupported type ({artifact.mime_type or 'unknown'})"
        logger.debug(
            f"Skipping {artifact.title or artifact.type}: "
            f"unsupported MIME type {artifact.mime_type or 'unknown'}"
        )
        return artifact

    ext = EXPORT_MIME_MAP[artifact.mime_type]

    # Build base filename
    base_filename = build_filename(
        date=date,
        meeting_title=meeting_title,
        document_title=artifact.title,
        document_id=artifact.drive_file_id or "unknown",
        ext=ext,
    )

    if dryrun:
        print(f"Would download: {artifact.title} → {base_filename}")
        return artifact

    if not artifact.drive_file_id:
        artifact.note = "No drive file ID"
        logger.warning(f"Skipping {artifact.title}: no drive file ID")
        return artifact

    file_id = artifact.drive_file_id

    try:
        if artifact.mime_type == "application/vnd.google-apps.document":
            # Google Docs: export directly as markdown
            output_path = output_dir / base_filename
            if output_path.exists():
                logger.debug(f"Skipping existing file: {output_path}")
                artifact.local_file = str(output_path)
            else:
                result = drive_client.export_doc_as_markdown(file_id, str(output_path))
                if result:
                    logger.debug(f"Exported doc to {output_path}")
                    artifact.local_file = str(output_path)
                else:
                    artifact.note = "Failed to export doc as markdown"

        elif artifact.mime_type == "application/vnd.google-apps.spreadsheet":
            # Google Sheets: export each tab as CSV
            first_file = _process_google_sheet(
                artifact, file_id, output_dir, date, meeting_title, ext
            )
            artifact.local_file = first_file

        elif artifact.mime_type == "application/vnd.google-apps.presentation":
            # Google Slides: export as PDF
            output_path = output_dir / base_filename
            if output_path.exists():
                logger.debug(f"Skipping existing file: {output_path}")
                artifact.local_file = str(output_path)
            else:
                result = drive_client.export_slides_as_pdf(file_id, str(output_path))
                if result:
                    logger.debug(f"Exported slides to {output_path}")
                    artifact.local_file = str(output_path)
                else:
                    artifact.note = "Failed to export slides"

    except GWSError as e:
        artifact.note = str(e)
        logger.warning(f"Failed to process {artifact.title}: {e}")

    return artifact


def _process_google_sheet(
    artifact: Artifact,
    file_id: str,
    output_dir: Path,
    date: str,
    meeting_title: str,
    ext: str,
) -> str | None:
    """Process a Google Sheet: export each tab as CSV.

    Returns the path to the first file written, or None on error.
    """
    tabs = drive_client.fetch_sheet_tabs(file_id)
    if not tabs:
        artifact.note = "No tabs found in sheet"
        return None

    first_file = None
    for tab in tabs:
        tab_name = tab["title"]
        filename = build_filename(
            date=date,
            meeting_title=meeting_title,
            document_title=artifact.title,
            document_id=file_id,
            ext=ext,
            tab_name=tab_name,
        )
        output_path = output_dir / filename

        if output_path.exists():
            logger.info(f"Skipping existing file: {output_path}")
        else:
            result = drive_client.fetch_sheet_tab_data(
                file_id, tab_name, str(output_path)
            )
            if result:
                logger.debug(f"Exported sheet tab to {output_path}")
            else:
                logger.warning(f"Failed to export tab {tab_name}")
                continue

        if first_file is None:
            first_file = str(output_path)

    return first_file


def process_event(
    event: CalendarEvent, output_dir: Path, *, dryrun: bool = False
) -> MeetingRecord:
    """Process a single calendar event: download artifacts and write metadata.

    Args:
        event: The calendar event to process
        output_dir: Directory to write files to
        dryrun: If True, log what would happen but don't download

    Returns:
        MeetingRecord with all artifacts and metadata
    """
    logger.info(f"Processing event: {event.summary}")

    # Extract date from start time
    date = extract_date(event.start)

    # Collect all artifacts
    all_artifacts = list(event.attachments)

    # Fetch Meet data if available
    meet_api_response: dict[str, object] = {}
    if event.meet_code:
        meet_artifacts, meet_api_response = meet_client.get_all_meet_data(
            event.meet_code
        )
        all_artifacts.extend(meet_artifacts)

    # Process each artifact
    for artifact in all_artifacts:
        process_artifact(artifact, output_dir, date, event.summary, dryrun=dryrun)

    # Build meeting record
    record = MeetingRecord(
        event=event,
        artifacts=all_artifacts,
        meet_api_response=meet_api_response,
    )

    # Write metadata
    if not dryrun:
        metadata_dict = metadata.build_meeting_metadata(record)
        filename = metadata.metadata_filename(record)
        metadata.write_metadata(metadata_dict, output_dir, filename)

    return record


def process_events(
    events: list[CalendarEvent], output_dir: Path, *, dryrun: bool = False
) -> list[MeetingRecord]:
    """Process all events: download artifacts and write metadata.

    Args:
        events: List of calendar events to process
        output_dir: Directory to write files to
        dryrun: If True, log what would happen but don't download

    Returns:
        List of MeetingRecords
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    records = []

    for event in events:
        record = process_event(event, output_dir, dryrun=dryrun)
        records.append(record)

    # Print summary
    total_artifacts = sum(len(r.artifacts) for r in records)
    downloaded = sum(
        1 for r in records for a in r.artifacts if a.local_file is not None
    )
    skipped = sum(
        1
        for r in records
        for a in r.artifacts
        if a.note is not None and a.note.startswith("Skipped:")
    )
    failed = sum(
        1
        for r in records
        for a in r.artifacts
        if a.note is not None and not a.note.startswith("Skipped:")
    )

    parts = [
        f"Processed {len(events)} events, {total_artifacts} artifacts",
        f"({downloaded} downloaded",
    ]
    if skipped:
        parts.append(f"{skipped} skipped")
    if failed:
        parts.append(f"{failed} failed")
    logger.info(", ".join(parts) + ")")

    return records
