# Generated By: Claude Code (Claude Opus 4.6)

"""Shared gws CLI runner for all Google API calls."""

import json
import logging
import subprocess
import sys

from calendar_fetcher.config import EXIT_ERROR

logger = logging.getLogger(__name__)

# Full scope URLs that gws auth status returns.
# Keyed by a human-readable name for error messages.
REQUIRED_SCOPE_URLS = {
    "calendar": "https://www.googleapis.com/auth/calendar.readonly",
    "docs": "https://www.googleapis.com/auth/documents.readonly",
    "drive": "https://www.googleapis.com/auth/drive.readonly",
    "meet": "https://www.googleapis.com/auth/meetings.space.readonly",
}

# For upload mode, drive needs read-write instead of readonly.
DRIVE_WRITE_SCOPE = "https://www.googleapis.com/auth/drive"


class GWSError(Exception):
    """Raised when a gws CLI command fails."""


def run_gws(
    *args: str,
    params: dict | None = None,
    output_file: str | None = None,
    format: str = "json",
) -> dict:
    """Run a gws CLI command and return parsed JSON output."""
    cmd = ["gws", *args, "--format", format]
    if params is not None:
        cmd.extend(["--params", json.dumps(params)])
    if output_file is not None:
        cmd.extend(["-o", output_file])

    logger.debug(f"Running: {' '.join(cmd)}")
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    except subprocess.TimeoutExpired:
        raise GWSError(f"gws {' '.join(args)} timed out after 60 seconds")

    if result.returncode != 0:
        stderr_lower = result.stderr.lower()
        if "timeout" in stderr_lower or "timed out" in stderr_lower:
            logger.warning(f"Timeout on gws {' '.join(args)}, retrying once")
            try:
                result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
            except subprocess.TimeoutExpired:
                raise GWSError(f"gws {' '.join(args)} timed out after 60 seconds")
        if result.returncode != 0:
            raise GWSError(
                f"gws {' '.join(args)} failed (exit {result.returncode}): "
                f"{result.stderr.strip()}"
            )

    if not result.stdout.strip():
        return {}
    return json.loads(result.stdout)


def check_auth_scopes(*, upload: bool = False) -> None:
    """Verify gws auth has the required scopes. Exits on failure."""
    try:
        status = run_gws("auth", "status")
    except GWSError as e:
        print(f"Error: Cannot check auth status: {e}", file=sys.stderr)
        _print_auth_help(upload=upload)
        raise SystemExit(EXIT_ERROR)

    granted_scopes = set(status.get("scopes", []))

    missing = []
    for name, scope_url in REQUIRED_SCOPE_URLS.items():
        # Special handling for drive in upload mode
        if name == "drive" and upload:
            # Need read-write scope, not readonly
            if DRIVE_WRITE_SCOPE not in granted_scopes:
                missing.append("drive (read-write, currently readonly)")
        else:
            if scope_url not in granted_scopes:
                missing.append(name)

    if missing:
        print(
            f"Error: Missing required scopes: {', '.join(sorted(missing))}",
            file=sys.stderr,
        )
        _print_auth_help(upload=upload)
        raise SystemExit(EXIT_ERROR)

    logger.debug("Auth scopes verified")


def _print_auth_help(*, upload: bool = False) -> None:
    """Print gws auth login command with full scope URLs."""
    scopes = list(REQUIRED_SCOPE_URLS.values())
    if upload:
        # Replace drive.readonly with drive (read-write)
        scopes = [
            DRIVE_WRITE_SCOPE if s == REQUIRED_SCOPE_URLS["drive"] else s
            for s in scopes
        ]
    scope_str = ",".join(scopes)
    print(
        f"Run 'gws auth login --scopes {scope_str}' to authenticate.",
        file=sys.stderr,
    )
