# Generated By: Claude Code (Claude Opus 4.6)

"""Shared gws CLI runner for all Google API calls."""

import json
import logging
import subprocess
import sys
import time

from calendar_fetcher.config import EXIT_ERROR

logger = logging.getLogger(__name__)

# Full scope URLs that gws auth status returns.
# Keyed by a human-readable name for error messages.
REQUIRED_SCOPE_URLS = {
    "calendar": "https://www.googleapis.com/auth/calendar.readonly",
    "docs": "https://www.googleapis.com/auth/documents.readonly",
    "drive": "https://www.googleapis.com/auth/drive.readonly",
    "meet": "https://www.googleapis.com/auth/meetings.space.readonly",
}

# For upload mode, drive needs read-write instead of readonly.
DRIVE_WRITE_SCOPE = "https://www.googleapis.com/auth/drive"

# For consolidate mode, docs needs read-write instead of readonly.
DOCS_WRITE_SCOPE = "https://www.googleapis.com/auth/documents"


class GWSError(Exception):
    """Raised when a gws CLI command fails."""


_QUOTA_BACKOFF_SCHEDULE = [5, 10, 15]
_MAX_QUOTA_RETRIES = 10


def _run_gws_cmd(cmd: list[str], label: str) -> dict:
    """Execute a gws command with timeout retry, quota backoff, and JSON parsing."""
    for attempt in range(_MAX_QUOTA_RETRIES + 1):
        logger.debug(f"Running: {' '.join(cmd)}")
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
        except subprocess.TimeoutExpired:
            raise GWSError(f"gws {label} timed out after 60 seconds")

        if result.returncode != 0:
            stderr_lower = result.stderr.lower()

            # Quota exceeded — backoff: 5s, 10s, then 15s steady
            if "quota" in stderr_lower and attempt < _MAX_QUOTA_RETRIES:
                schedule_idx = min(attempt, len(_QUOTA_BACKOFF_SCHEDULE) - 1)
                wait = _QUOTA_BACKOFF_SCHEDULE[schedule_idx]
                logger.warning(
                    f"Quota exceeded on gws {label}, "
                    f"waiting {wait}s before retry "
                    f"({attempt + 1}/{_MAX_QUOTA_RETRIES})"
                )
                time.sleep(wait)
                continue

            # Timeout in stderr — retry once
            if "timeout" in stderr_lower or "timed out" in stderr_lower:
                logger.warning(f"Timeout on gws {label}, retrying once")
                try:
                    result = subprocess.run(
                        cmd, capture_output=True, text=True, timeout=60
                    )
                except subprocess.TimeoutExpired:
                    raise GWSError(f"gws {label} timed out after 60 seconds")

            if result.returncode != 0:
                raise GWSError(
                    f"gws {label} failed (exit {result.returncode}): "
                    f"{result.stderr.strip()}"
                )

        if not result.stdout.strip():
            return {}
        return json.loads(result.stdout)

    raise GWSError(f"gws {label} failed after {_MAX_QUOTA_RETRIES} quota retries")


def run_gws(
    *args: str,
    params: dict | None = None,
    output_file: str | None = None,
    format: str = "json",
) -> dict:
    """Run a gws CLI command and return parsed JSON output."""
    cmd = ["gws", *args, "--format", format]
    if params is not None:
        cmd.extend(["--params", json.dumps(params)])
    if output_file is not None:
        cmd.extend(["-o", output_file])
    return _run_gws_cmd(cmd, " ".join(args))


def run_gws_write(
    *args: str,
    params: dict | None = None,
    json_body: dict | None = None,
    format: str = "json",
) -> dict:
    """Run a gws CLI command with a JSON request body (--json flag)."""
    cmd = ["gws", *args, "--format", format]
    if params is not None:
        cmd.extend(["--params", json.dumps(params)])
    if json_body is not None:
        cmd.extend(["--json", json.dumps(json_body)])
    return _run_gws_cmd(cmd, " ".join(args))


def check_auth_scopes(*, upload: bool = False, consolidate: bool = False) -> None:
    """Verify gws auth has the required scopes. Exits on failure."""
    try:
        status = run_gws("auth", "status")
    except GWSError as e:
        print(f"Error: Cannot check auth status: {e}", file=sys.stderr)
        _print_auth_help(upload=upload, consolidate=consolidate)
        raise SystemExit(EXIT_ERROR)

    granted_scopes = set(status.get("scopes", []))

    missing = []
    for name, scope_url in REQUIRED_SCOPE_URLS.items():
        # Special handling for docs in consolidate mode
        if name == "docs" and consolidate:
            if DOCS_WRITE_SCOPE not in granted_scopes:
                missing.append("docs (read-write, currently readonly)")
            continue
        # Special handling for drive in upload mode
        if name == "drive" and upload:
            # Need read-write scope, not readonly
            if DRIVE_WRITE_SCOPE not in granted_scopes:
                missing.append("drive (read-write, currently readonly)")
        else:
            if scope_url not in granted_scopes:
                missing.append(name)

    if missing:
        print(
            f"Error: Missing required scopes: {', '.join(sorted(missing))}",
            file=sys.stderr,
        )
        _print_auth_help(upload=upload, consolidate=consolidate)
        raise SystemExit(EXIT_ERROR)

    logger.debug("Auth scopes verified")


def _print_auth_help(*, upload: bool = False, consolidate: bool = False) -> None:
    """Print gws auth login command with full scope URLs."""
    scopes = list(REQUIRED_SCOPE_URLS.values())
    if consolidate:
        scopes = [
            DOCS_WRITE_SCOPE if s == REQUIRED_SCOPE_URLS["docs"] else s for s in scopes
        ]
    if upload:
        # Replace drive.readonly with drive (read-write)
        scopes = [
            DRIVE_WRITE_SCOPE if s == REQUIRED_SCOPE_URLS["drive"] else s
            for s in scopes
        ]
    scope_str = ",".join(scopes)
    print(
        f"Run 'gws auth login --scopes {scope_str}' to authenticate.",
        file=sys.stderr,
    )
