# Generated By: Claude Code (Claude Opus 4.6)

"""Meet API client for fetching conference records, transcripts, and recordings."""

import logging

from calendar_fetcher.gws import run_gws
from calendar_fetcher.models import Artifact

logger = logging.getLogger(__name__)


def get_conference_record(meet_code: str) -> dict | None:
    """Fetch conference record by meet code.

    Returns first conference record dict, or None if not found.
    """
    response = run_gws(
        "meet",
        "conferenceRecords",
        "list",
        params={"filter": f'space.meeting_code="{meet_code}"'},
    )
    records = response.get("conferenceRecords", [])
    return records[0] if records else None


def get_transcripts(conference_id: str) -> list[Artifact]:
    """Fetch transcripts for a conference.

    Returns list of transcript Artifacts.
    """
    response = run_gws(
        "meet",
        "conferenceRecords",
        "transcripts",
        "list",
        params={"parent": conference_id},
    )
    transcripts = response.get("transcripts", [])

    artifacts = []
    for transcript in transcripts:
        docs_dest = transcript.get("docsDestination", {})
        document_id = docs_dest.get("document")
        export_uri = docs_dest.get("exportUri")

        if export_uri and document_id:
            artifacts.append(
                Artifact(
                    type="transcript",
                    title="Transcript",
                    source_url=export_uri,
                    drive_file_id=document_id,
                    mime_type="application/vnd.google-apps.document",
                )
            )

    return artifacts


def get_recordings(conference_id: str) -> list[Artifact]:
    """Fetch recordings for a conference.

    Returns list of recording Artifacts.
    """
    response = run_gws(
        "meet",
        "conferenceRecords",
        "recordings",
        "list",
        params={"parent": conference_id},
    )
    recordings = response.get("recordings", [])

    artifacts = []
    for recording in recordings:
        drive_dest = recording.get("driveDestination", {})
        file_id = drive_dest.get("file")
        export_uri = drive_dest.get("exportUri")

        if export_uri and file_id:
            artifacts.append(
                Artifact(
                    type="recording",
                    title="Recording",
                    source_url=export_uri,
                    drive_file_id=file_id,
                    note="Recording download may be restricted by organization policy",
                )
            )

    return artifacts


def get_participants(conference_id: str) -> list[dict]:
    """Fetch participants for a conference.

    Returns list of raw participant dicts. Each participant includes
    signedinUser.displayName and signedinUser.user from the Meet API.
    """
    response = run_gws(
        "meet",
        "conferenceRecords",
        "participants",
        "list",
        params={"parent": conference_id},
    )
    return response.get("participants", [])


def get_all_meet_data(meet_code: str) -> tuple[list[Artifact], dict]:
    """Fetch all Meet data for a meeting code.

    Returns (artifacts_list, api_response_dict). Participant identity
    is available directly from the Meet API response (signedinUser)
    and from the Calendar API attendees — no People API lookup needed.
    """
    conference_record = get_conference_record(meet_code)
    if not conference_record:
        logger.info(f"No conference record found for meet code: {meet_code}")
        return ([], {})

    conference_id = conference_record["name"]

    transcripts_artifacts = get_transcripts(conference_id)
    recordings_artifacts = get_recordings(conference_id)
    participants = get_participants(conference_id)

    api_response = {
        "conference_record": conference_record,
        "transcripts": (
            {"transcripts": [t.__dict__ for t in transcripts_artifacts]}
            if transcripts_artifacts
            else {}
        ),
        "recordings": (
            {"recordings": [r.__dict__ for r in recordings_artifacts]}
            if recordings_artifacts
            else {}
        ),
        "participants": participants,
    }

    all_artifacts = transcripts_artifacts + recordings_artifacts

    return (all_artifacts, api_response)
