# Generated By: Claude Code (Claude Opus 4.6)

"""Meet API client for fetching conference records, transcripts, and recordings."""

import logging

from calendar_fetcher.cache import FileCache
from calendar_fetcher.gws import GWSError, run_gws
from calendar_fetcher.models import Artifact

logger = logging.getLogger(__name__)


def get_conference_record(meet_code: str) -> dict | None:
    """Fetch conference record by meet code.

    Args:
        meet_code: The meeting code (e.g., "abc-defg-hij")

    Returns:
        First conference record dict, or None if not found
    """
    response = run_gws(
        "meet",
        "conferenceRecords",
        "list",
        params={"filter": f'space.meeting_code="{meet_code}"'},
    )
    records = response.get("conferenceRecords", [])
    return records[0] if records else None


def get_transcripts(conference_id: str) -> list[Artifact]:
    """Fetch transcripts for a conference.

    Args:
        conference_id: The conference record ID (e.g., "conferenceRecords/abc-123")

    Returns:
        List of transcript Artifacts
    """
    response = run_gws(
        "meet",
        "conferenceRecords",
        "transcripts",
        "list",
        params={"parent": conference_id},
    )
    transcripts = response.get("transcripts", [])

    artifacts = []
    for transcript in transcripts:
        docs_dest = transcript.get("docsDestination", {})
        document_id = docs_dest.get("document")
        export_uri = docs_dest.get("exportUri")

        if export_uri and document_id:
            artifacts.append(
                Artifact(
                    type="transcript",
                    title="Transcript",
                    source_url=export_uri,
                    drive_file_id=document_id,
                    mime_type="application/vnd.google-apps.document",
                )
            )

    return artifacts


def get_recordings(conference_id: str) -> list[Artifact]:
    """Fetch recordings for a conference.

    Args:
        conference_id: The conference record ID (e.g., "conferenceRecords/abc-123")

    Returns:
        List of recording Artifacts
    """
    response = run_gws(
        "meet",
        "conferenceRecords",
        "recordings",
        "list",
        params={"parent": conference_id},
    )
    recordings = response.get("recordings", [])

    artifacts = []
    for recording in recordings:
        drive_dest = recording.get("driveDestination", {})
        file_id = drive_dest.get("file")
        export_uri = drive_dest.get("exportUri")

        if export_uri and file_id:
            artifacts.append(
                Artifact(
                    type="recording",
                    title="Recording",
                    source_url=export_uri,
                    drive_file_id=file_id,
                    note="Recording download may be restricted by organization policy",
                )
            )

    return artifacts


def get_participants(conference_id: str) -> list[dict]:
    """Fetch participants for a conference.

    Args:
        conference_id: The conference record ID (e.g., "conferenceRecords/abc-123")

    Returns:
        List of raw participant dicts
    """
    response = run_gws(
        "meet",
        "conferenceRecords",
        "participants",
        "list",
        params={"parent": conference_id},
    )
    return response.get("participants", [])


def resolve_participant(
    participant_name: str, *, cache: FileCache | None = None
) -> dict | None:
    """Resolve participant identity via People API.

    Args:
        participant_name: The participant resource name
            (e.g., "conferenceRecords/abc/participants/12345")
        cache: Optional FileCache for caching participant data

    Returns:
        Dict with "name" and "email" keys, or None on error
    """
    # Extract numeric ID from participant name
    # Format: conferenceRecords/abc/participants/12345 -> 12345
    try:
        numeric_id = participant_name.split("/")[-1]
    except (AttributeError, IndexError):
        logger.warning(
            f"Could not extract ID from participant name: {participant_name}"
        )
        return None

    # Check cache first
    if cache is not None:
        cached = cache.get(numeric_id)
        if cached is not None:
            return cached

    try:
        response = run_gws(
            "people",
            "people",
            "get",
            params={
                "resourceName": f"people/{numeric_id}",
                "personFields": "names,emailAddresses",
            },
        )

        # Extract name and email
        name = None
        email = None

        names = response.get("names", [])
        if names:
            name = names[0].get("displayName")

        emails = response.get("emailAddresses", [])
        if emails:
            email = emails[0].get("value")

        resolved = {"name": name, "email": email}

        # Store in cache if available
        if cache is not None and resolved is not None:
            cache.set(numeric_id, resolved)

        return resolved

    except GWSError as e:
        logger.warning(f"Error resolving participant {participant_name}: {e}")
        return None


def get_all_meet_data(
    meet_code: str, *, cache: FileCache | None = None
) -> tuple[list[Artifact], dict]:
    """Fetch all Meet data for a meeting code.

    Orchestrates calls to get conference record, transcripts, recordings,
    and participants, and resolves participant identities.

    Args:
        meet_code: The meeting code (e.g., "abc-defg-hij")
        cache: Optional FileCache for caching participant data

    Returns:
        Tuple of (artifacts_list, api_response_dict) where api_response_dict contains:
        - conference_record: The conference record dict
        - transcripts: Raw transcripts response
        - recordings: Raw recordings response
        - participants: List of participant dicts with resolved_identity added
    """
    # Get conference record
    conference_record = get_conference_record(meet_code)
    if not conference_record:
        logger.info(f"No conference record found for meet code: {meet_code}")
        return ([], {})

    conference_id = conference_record["name"]

    # Fetch transcripts and recordings (these return Artifacts)
    transcripts_artifacts = get_transcripts(conference_id)
    recordings_artifacts = get_recordings(conference_id)

    # Fetch participants (returns raw dicts)
    participants = get_participants(conference_id)

    # Resolve participant identities
    for participant in participants:
        participant_name = participant.get("name", "")
        resolved = resolve_participant(participant_name, cache=cache)
        participant["resolved_identity"] = resolved

    # Build API response dict
    api_response = {
        "conference_record": conference_record,
        "transcripts": (
            {"transcripts": [t.__dict__ for t in transcripts_artifacts]}
            if transcripts_artifacts
            else {}
        ),
        "recordings": (
            {"recordings": [r.__dict__ for r in recordings_artifacts]}
            if recordings_artifacts
            else {}
        ),
        "participants": participants,
    }

    # Combine all artifacts
    all_artifacts = transcripts_artifacts + recordings_artifacts

    return (all_artifacts, api_response)
