# Generated By: Claude Code (Claude Opus 4.6)

"""Metadata generation and management for calendar-fetcher."""

import json
import logging
from datetime import date, datetime, timezone
from pathlib import Path

from calendar_fetcher.calendar_client import parse_event
from calendar_fetcher.config import STATE_FILENAME
from calendar_fetcher.models import MeetingRecord
from calendar_fetcher.naming import extract_date, slugify

logger = logging.getLogger(__name__)


def build_meeting_metadata(record: MeetingRecord) -> dict:
    """Build metadata dict from a MeetingRecord.

    Returns a dict containing event metadata, artifacts, and API responses.
    Excludes None values from artifact dicts.
    """
    artifacts = []
    for artifact in record.artifacts:
        artifact_dict = {
            "type": artifact.type,
            "title": artifact.title,
            "source_url": artifact.source_url,
        }
        # Only include optional fields if they have values
        if artifact.drive_file_id is not None:
            artifact_dict["drive_file_id"] = artifact.drive_file_id
        if artifact.local_file is not None:
            artifact_dict["local_file"] = artifact.local_file
        if artifact.mime_type is not None:
            artifact_dict["mime_type"] = artifact.mime_type
        if artifact.source is not None:
            artifact_dict["source"] = artifact.source
        if artifact.note is not None:
            artifact_dict["note"] = artifact.note
        artifacts.append(artifact_dict)

    return {
        "event_id": record.event.event_id,
        "calendar_id": record.event.calendar_id,
        "summary": record.event.summary,
        "start": record.event.start,
        "end": record.event.end,
        "recurring_event_id": record.event.recurring_event_id,
        "meet_code": record.event.meet_code,
        "artifacts": artifacts,
        "api_responses": {
            "calendar": record.event.api_response,
            "meet": record.meet_api_response,
        },
    }


def metadata_filename(record: MeetingRecord) -> str:
    """Generate metadata filename for a meeting record.

    Format: {date}_{meeting-title}.meta.json
    Date is extracted from event start (YYYY-MM-DD).
    """
    date = extract_date(record.event.start)
    title_slug = slugify(record.event.summary)
    return f"{date}_{title_slug}.meta.json"


def build_index_entry(metadata: dict, metadata_file: str) -> dict:
    """Build concise index entry from metadata dict.

    Returns dict with date, summary, event_id, metadata_file, and
    list of downloaded files.
    """
    downloaded_files = [
        artifact["local_file"]
        for artifact in metadata["artifacts"]
        if artifact.get("local_file") is not None
    ]

    return {
        "date": extract_date(metadata["start"]),
        "summary": metadata["summary"],
        "event_id": metadata["event_id"],
        "metadata_file": metadata_file,
        "downloaded_files": downloaded_files,
    }


def write_metadata(metadata: dict, output_dir: Path, filename: str) -> Path:
    """Write metadata dict as JSON to output_dir/filename.

    Creates output_dir if it doesn't exist.
    Returns the path written.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / filename

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)

    logger.info(f"Wrote metadata to {output_path}")
    return output_path


def build_and_write_index(output_dir: Path) -> Path:
    """Build and write index.json from all .meta.json files in output_dir.

    Reads all metadata sidecars, builds index entries, sorts by date descending,
    and writes index.json.

    Returns the path to index.json.
    """
    index_entries = []

    # Find all .meta.json files
    for meta_file in sorted(output_dir.glob("*.meta.json")):
        try:
            with open(meta_file, encoding="utf-8") as f:
                metadata = json.load(f)
        except json.JSONDecodeError:
            logger.warning(f"Skipping malformed metadata file: {meta_file}")
            continue
        entry = build_index_entry(metadata, meta_file.name)
        index_entries.append(entry)

    # Sort by date descending
    index_entries.sort(key=lambda e: e["date"], reverse=True)

    # Write index
    index_path = output_dir / "index.json"
    with open(index_path, "w", encoding="utf-8") as f:
        json.dump(index_entries, f, indent=2)

    logger.info(f"Wrote index with {len(index_entries)} entries to {index_path}")
    return index_path


def refresh_all_metadata(output_dir: Path) -> int:
    """Refresh all metadata files from their api_responses.

    Re-extracts top-level fields from api_responses.calendar and writes
    updated sidecar files.

    Returns count of files refreshed.
    """
    count = 0

    for meta_file in sorted(output_dir.glob("*.meta.json")):
        try:
            with open(meta_file, encoding="utf-8") as f:
                metadata = json.load(f)
        except json.JSONDecodeError:
            logger.warning(f"Skipping malformed metadata file: {meta_file}")
            continue

        # Extract updated fields from calendar API response via parse_event
        calendar_response = metadata["api_responses"]["calendar"]
        parsed = parse_event(calendar_response, metadata["calendar_id"])

        metadata["summary"] = parsed.summary
        metadata["start"] = parsed.start
        metadata["end"] = parsed.end
        metadata["recurring_event_id"] = parsed.recurring_event_id

        # Write updated metadata
        with open(meta_file, "w", encoding="utf-8") as f:
            json.dump(metadata, f, indent=2)

        logger.info(f"Refreshed {meta_file.name}")
        count += 1

    logger.info(f"Refreshed {count} metadata files")
    return count


def write_fetch_state(output_dir: Path) -> Path:
    """Write fetch state with current UTC timestamp.

    Returns the path to the state file.
    """
    state_path = output_dir / STATE_FILENAME
    state = {"modified_on": datetime.now(timezone.utc).isoformat()}

    with open(state_path, "w", encoding="utf-8") as f:
        json.dump(state, f, indent=2)

    logger.debug(f"Wrote fetch state to {state_path}")
    return state_path


def read_fetch_state(output_dir: Path) -> date | None:
    """Read last fetch date from state file.

    Returns the date portion of modified_on, or None if the state file
    is missing or malformed.
    """
    state_path = output_dir / STATE_FILENAME
    if not state_path.exists():
        return None

    try:
        with open(state_path, encoding="utf-8") as f:
            state = json.load(f)
        modified_on = state.get("modified_on")
        if not modified_on:
            return None
        return datetime.fromisoformat(modified_on).date()
    except (json.JSONDecodeError, ValueError, KeyError):
        return None
