# Generated By: Claude Code (Claude Opus 4.6)

"""Dataclasses for calendar-fetcher domain objects."""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class Artifact:
    """A downloadable artifact associated with a calendar event."""

    type: str  # "attachment", "transcript", "recording"
    title: str
    source_url: str
    drive_file_id: str | None = None
    local_file: str | None = None
    mime_type: str | None = None
    source: str | None = None  # "attached" or "description_link"
    note: str | None = None


@dataclass
class CalendarEvent:
    """A Google Calendar event with its extracted metadata."""

    event_id: str
    calendar_id: str
    summary: str
    start: str
    end: str
    description: str = ""
    recurring_event_id: str | None = None
    meet_code: str | None = None
    attachments: list[Artifact] = field(default_factory=list)
    api_response: dict = field(default_factory=dict)


@dataclass
class MeetingRecord:
    """Combined record for a meeting: calendar event + Meet data + artifacts."""

    event: CalendarEvent
    artifacts: list[Artifact] = field(default_factory=list)
    meet_api_response: dict = field(default_factory=dict)
