# Generated By: Claude Code (Claude Opus 4.6)

"""File naming utilities for calendar-fetcher."""

import re


def extract_date(timestamp: str) -> str:
    """Extract YYYY-MM-DD from an ISO timestamp string."""
    if len(timestamp) < 10:
        return ""
    return timestamp[:10]


def slugify(text: str) -> str:
    """Convert text to a URL-safe slug.

    - Lowercase
    - Underscores become dashes
    - Spaces become dashes
    - Strip non-alphanumeric except dashes
    - Collapse consecutive dashes
    """
    text = text.lower()
    text = text.replace("_", "-")
    text = re.sub(r"[^a-z0-9\-\s]", "", text)
    text = re.sub(r"[\s]+", "-", text)
    text = re.sub(r"-+", "-", text)
    text = text.strip("-")
    return text


def build_filename(
    date: str,
    meeting_title: str,
    document_title: str,
    document_id: str,
    ext: str,
    *,
    tab_name: str | None = None,
) -> str:
    """Build a flat-directory filename.

    Format: {date}_{meeting}_{doc}_{id}.{ext}
    With tab: {date}_{meeting}_{doc}_{id}_{tab}.{ext}
    """
    parts = [
        date,
        slugify(meeting_title),
        slugify(document_title),
        document_id,
    ]
    if tab_name is not None:
        parts.append(slugify(tab_name))
    return "_".join(parts) + f".{ext}"
