# Generated By: Claude Code (Claude Opus 4.6)

"""File naming utilities for calendar-fetcher."""

import re


def extract_date(timestamp: str) -> str:
    """Extract YYYY-MM-DD from an ISO timestamp string."""
    if len(timestamp) < 10:
        return ""
    return timestamp[:10]


def slugify(text: str) -> str:
    """Convert text to a URL-safe slug.

    - Lowercase
    - Underscores become dashes
    - Spaces become dashes
    - Strip non-alphanumeric except dashes
    - Collapse consecutive dashes
    """
    text = text.lower()
    text = text.replace("_", "-")
    text = re.sub(r"[^a-z0-9\-\s]", "", text)
    text = re.sub(r"[\s]+", "-", text)
    text = re.sub(r"-+", "-", text)
    text = text.strip("-")
    return text


def build_filename(
    date: str,
    meeting_title: str,
    document_title: str,
    document_id: str,
    ext: str,
    *,
    tab_name: str | None = None,
    max_length: int = 255,
) -> str:
    """Build a flat-directory filename.

    Format: {date}_{meeting}_{doc}_{id}.{ext}
    With tab: {date}_{meeting}_{doc}_{id}_{tab}.{ext}

    Truncates meeting and document title slugs to stay within max_length.
    """
    meeting_slug = slugify(meeting_title)
    doc_slug = slugify(document_title)
    tab_slug = slugify(tab_name) if tab_name is not None else None

    # Fixed-length portions: date, document_id, ext, separators
    fixed_len = len(date) + 1 + len(document_id) + 1 + len(ext)
    if tab_slug is not None:
        fixed_len += 1 + len(tab_slug)

    # Budget remaining space for meeting_slug and doc_slug (plus 2 separators)
    budget = max_length - fixed_len - 2
    if budget < 2:
        budget = 2

    half = budget // 2
    meeting_slug = meeting_slug[:half].rstrip("-")
    doc_slug = doc_slug[:budget - len(meeting_slug)].rstrip("-")

    parts = [date, meeting_slug, doc_slug, document_id]
    if tab_slug is not None:
        parts.append(tab_slug)
    return "_".join(parts) + f".{ext}"
