# Generated By: Claude Code (Claude Opus 4.6)

"""Extract date-specific sections from meeting-notes-style markdown documents."""

import logging
import re
from collections import Counter
from datetime import date

from calendar_fetcher.date_utils import parse_human_date, strip_markdown_formatting

logger = logging.getLogger(__name__)

_HEADING_RE = re.compile(r"^(#{1,6})\s+(.*?)\s*$")


def _parse_heading_date(text: str) -> date | None:
    """Parse a date from a markdown heading's text content."""
    cleaned = strip_markdown_formatting(text)
    return parse_human_date(cleaned)


def _find_date_heading_level(lines: list[str]) -> int | None:
    """Auto-detect the heading level used for date sections.

    Returns the heading level (1-6) that contains the most parseable
    dates, or None if no date headings are found.
    """
    level_counts: Counter[int] = Counter()
    for line in lines:
        m = _HEADING_RE.match(line)
        if m and _parse_heading_date(m.group(2)):
            level_counts[len(m.group(1))] += 1
    if not level_counts:
        return None
    return level_counts.most_common(1)[0][0]


def extract_section(content: str, target_date: str) -> str | None:
    """Extract preamble + target-date section from meeting notes markdown.

    Args:
        content: Full markdown document content.
        target_date: Date string in YYYY-MM-DD format.

    Returns:
        Extracted content (preamble + matching section) if the document
        has date-heading structure and the target date is found.
        None otherwise (caller should keep full content).
    """
    lines = content.split("\n")
    section_level = _find_date_heading_level(lines)
    if section_level is None:
        return None

    target = date.fromisoformat(target_date)
    prefix = "#" * section_level

    date_headings: list[tuple[int, date]] = []
    for i, line in enumerate(lines):
        m = _HEADING_RE.match(line)
        if m and len(m.group(1)) == section_level:
            parsed = _parse_heading_date(m.group(2))
            if parsed:
                date_headings.append((i, parsed))

    if not date_headings:
        return None

    preamble_end = date_headings[0][0]
    preamble_lines = lines[:preamble_end]
    while preamble_lines and preamble_lines[-1].strip() in ("", "---"):
        preamble_lines.pop()
    preamble = "\n".join(preamble_lines).rstrip()

    match_idx = None
    for i, (line_num, heading_date) in enumerate(date_headings):
        if heading_date == target:
            match_idx = i
            break

    if match_idx is None:
        return None

    start = date_headings[match_idx][0]
    end = (
        date_headings[match_idx + 1][0]
        if match_idx + 1 < len(date_headings)
        else len(lines)
    )

    section_lines = lines[start:end]
    while section_lines and section_lines[-1].strip() in ("", "---", f"{prefix} "):
        section_lines.pop()
    section = "\n".join(section_lines)

    if preamble:
        return preamble + "\n\n---\n\n" + section
    return section
