# Generated By: Claude Code (Claude Opus 4.6)

"""Shared state file access for fetcher-state.json."""

import json
import logging
from pathlib import Path

from calendar_fetcher.config import STATE_FILENAME

logger = logging.getLogger(__name__)


def read_state_file(output_dir: Path) -> dict:
    """Read and return the full state file contents.

    Returns empty dict if the file is missing or malformed.
    """
    state_path = output_dir / STATE_FILENAME
    if not state_path.exists():
        return {}
    try:
        with open(state_path, encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return {}


def write_state_key(output_dir: Path, key: str, value: object) -> Path:
    """Write a single key into the state file, preserving other keys.

    Returns the path to the state file.
    """
    state_path = output_dir / STATE_FILENAME
    existing = read_state_file(output_dir)
    existing[key] = value
    with open(state_path, "w", encoding="utf-8") as f:
        json.dump(existing, f, indent=2)
    return state_path
