# Generated By: Claude Code (Claude Opus 4.6)

.PHONY: pipx pipx-uninstall

PROJECT_NAME ?= calendar-fetcher

pipx:  ## Install globally via pipx
	python3 -m pipx install . --force

pipx-uninstall:  ## Uninstall global pipx install
	python3 -m pipx uninstall $(PROJECT_NAME)
